### PR TITLE
fix the return type for `getLogs`

### PR DESCRIPTION
**Pull request by greged93**
The return type for `getLogs` should match the type from `getFilterChanges` and `getFilterLogs` as per https://github.com/ethereum/execution-apis/blob/main/src/eth/filter.yaml.

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
> Returns an array of all logs matching filter with given id.

this is also how filterchanges::logs serializes, so there's no need to wrap the array?

**Comment by greged93** [comment]
indeed there is no actual changes to serialization, just more of a consistency fix.

**Comment by mattsse** [comment]
hmm, don't think we need to do this because now this can return not only logs, this doesn't matter for server side, but we use the interface for client as well and this would make it less convenient to test.
so I think a Vec of Log is appropriate here, looking at #4323 again, the same argument could be made there and perhaps we should change that to again

**Comment by greged93** [comment]
Ok makes sense, I can revert 4323 then if you want in this PR and remove my changes if that works for you

**Pull request closed without merging**
