### PR TITLE
feat: implement trace_getBalanceChangesInBlock

### PR DESCRIPTION
**Pull request by ryanschneider**
This is my very experimental, very naive attempt at implementing https://github.com/paradigmxyz/reth/issues/3139, with some major caveats:

- It's in the `trace` namespace, not `eth` or as mentioned in that issue possibly `reth`.
- I've only tested it w/ a couple blocks on Sepolia, and things look sane, but it's pretty clear I'm just poking around at things and finding what appears to work vs doing what's objectively the best way.
- I'd love to remove the extra allocations of the inner `.collect` inside the `trace_block_with` callback.
- During my experiments, inside the callback I seem to get the same data from `state` or `db.accounts`, not sure if there's something I'm overlooking as to the difference between those two.
- Importantly, this does not include any balance changes for block rewards, etc. where IMO it really should (and thus this might mean this approach really is a no-go).
- `reth_provider::PostState` seems very promising but I'm not sure how to get to that from the RPC layer.
- Also as mentioned on #3139 using `table::AccountChangeSet` might be smarter.

Anyways, I'm 99% certain this PR is not the right way to go, but figured it'd be a good place to dig into _why_ it's bad. :)

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
okay, I finally looked at this, sorry for the delay.

this was looking great already.

I implemented a missing check so we only record accounts that actually have a balance change, this currently requires comparing against the initial state.

But I wasn't sure what exactly constitutes a balance change, should the final set include:
a) only accounts that have a different balance after the block
b) all accounts that have a different balance after a transaction

b) can be more than a) for example

Tx1: A has balance X and sends some funds V to somewhere
A.balance after TX1 is -(V+gas)
Tx2: B sends V+gas to A

now A has the same balance as before Tx1

**Comment by ryanschneider** [comment]
Thanks for the feedback @mattsse, I like your change, and it should eliminate another issue I saw during my testing that I forgot to list, which was that I was seeing precompile contracts showing up in the list (though w/ 0 balance).  I don't believe there are any precompiles that accept/hold a balance but I guess if they ever actually did then yes they should show up.

Also it'd be great to pull the reward tracing code from https://github.com/paradigmxyz/reth/blob/4c7f980c774c77db48abdb119028d6a94cf24952/crates/rpc/rpc/src/trace.rs#L418-L447 into a stand-alone function that can be called here as well.

And as others have already mentioned, I think the intent is that this is ultimately `reth_getBalanceChangesInBlock` rather than living in the `trace` namespace, but I wasn't comfortable enough w/ the code yet to go around changing privacy levels or creating a new module.

Anyways, I'll try to find some time later this week to do another pass on this, but in the meantime if you or anyone else wants to add more to it by all means please do!

**Comment by mattsse** [comment]
> Also it'd be great to pull the reward tracing code from

good point.

I'd be okay with merging this and then iterating on it, wdyt?

**Comment by ryanschneider** [comment]
> But I wasn't sure what exactly constitutes a balance change

FWIW it looks like erigon iterates over the block's `AccountChangeSet` and only includes accounts where old and new balances differ.  In many ways I still feel like this might be the saner way to approach this RPC than using tracing, but I'm not familar enough w/ reth's data access code yet, curious your opinion on that.

I really wish the [execution-api repo](https://github.com/ethereum/execution-apis) also included more _intent_ around the RPCs rather than just their schema (somewhat moot point since atm I don't believe there's an entry for this RPC), but I wonder if we should actually open a PR over there to try to get teams to agree on the semantics of the RPC?

With the existing RPC name, I think it's reasonable to only include accounts w/ actual net balance changes, but functionality wise I could see the usefulness of a more general RPC that tracks any account changes (including nonce etc) in the block, so personally I'm a bit torn.

**Comment by ryanschneider** [comment]
> I'd be okay with merging this and then iterating on it, wdyt?

_personally_ I'd say let's remove the actual RPC handler (https://github.com/paradigmxyz/reth/pull/3516/files#diff-7196d9ec8a02ec1bb5d7992fef9543e70133c998bf3e18cbb4f7fbbdb7e55c28R639-R646) before merging since it's not quite up to public release yet IMO.

I know you're still 0.x so have leeway but IMO it's better to err on the side of caution and not expose RPCs until they are "1.0" since it's likely that as soon as they are available someone somewhere will start relying on them.

**Comment by ryanschneider** [comment]
@mattse ok I haven't tested this at all yet, just got it to compile but what about this `AccountChangeSet` based approach:

```rust
impl<Provider, Pool, Network> EthApi<Provider, Pool, Network>
where
    Provider: AccountExtReader + BlockReaderIdExt + StateProviderFactory + 'static,
{
    pub(crate) fn balances_changes_in_block(
        &self,
        block_id: impl Into<BlockId>,
    ) -> EthResult<Option<HashMap<Address, U256>>> {
        let block_id = block_id.into();
        let Some(block_number) = self.provider().block_number_for_id(block_id)? else {
            return Err(EthApiError::UnknownBlockNumber)
        };

        let changed_accounts =
            self.provider().changed_accounts_with_range(block_number..=block_number)?;
        let state = self.provider().state_by_block_id(block_id)?;

        if changed_accounts.is_empty() {
            return Ok(None);
        }

        return changed_accounts.iter().try_fold(Some(HashMap::new()), |hash_map, &account| {
            let Some(balance) = state.account_balance(account)? else {
                return Err(EthApiError::InternalEthError)
            };
            let mut hash_map = hash_map.unwrap();
            hash_map.insert(account, balance);
            Ok(Some(hash_map))
        });
    }
}
```

My thought is to add this to `crates/rpc/rpc/src/eth/api/` as `mod changes`.  I'll keep working on it but curious your thoughts.  If it works it seems like it should be more efficient since it doesn't require replaying the txs or recalculating the block rewards.  I think it will still require your delta checks though, since its entirely possible a account ends up in `AccountChangeSet` for non-balance-related changes.

Which then leads me to thing maybe a simpler primitive is `fn account_changes_in_block(&self, block_id) -> EthResult<Vec<Account>>` which we could then filter with something like your delta code for the actual RPC, how does that sound?

**Comment by ryanschneider** [comment]
Ok I think I have something promising, I've open a separate draft PR to discuss so as not to derail things here too far: https://github.com/paradigmxyz/reth/pull/3768

**Comment by rakita** [comment]
Hello, `AccountChangeSet` is the way forward, it contains all needed information, we just need to fetch it. Let me look at pr

**Comment by ryanschneider** [comment]
I definitely think we should close this in favor of #3768, the only advantage I can think of for the trace-based approach is that it could work on hypothetical blocks for e.g. block producers, but in that case it'd probably be better if the API took a block body instead of a block_id (and it still needs to be updated to support rewards and withdrawals).

**Comment by ryanschneider** [comment]
Closing in favor of https://github.com/paradigmxyz/reth/pull/3768.

**Pull request closed without merging**
