### PR TITLE
feat: add state root validation on new insert

### LINKED ISSUE #2542: Verify state root in blockchain tree on insert
### Describe the feature

https://github.com/paradigmxyz/reth/blob/29ce8aab433e4733dace90a47ef44d3fa481124b/crates/blockchain-tree/src/chain.rs#L134-L134

currently does not check state root

```
./hive --client reth --sim ethereum/engine --sim.limit "/Invalid Transition Payload"
```

Also

```
./hive --client reth --sim ethereum/engine --sim.limit "/Invalid PrevRandao"
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mattsse**
closes #2542

~~this currently does not work in tests because:~~

> "Unable to compute state root on top of historical block"

~~I don't fully understand the canonical fork stuff, but I would expect that:~~

https://github.com/paradigmxyz/reth/blob/dc4648a1fe3eaa7b40e5ae79bcefd7840942fa0f/crates/blockchain-tree/src/chain.rs#L150-L151

~~does not point to a historical block?~~

This works now as expected

> status: Invalid { validation_error: "Block state root (0x36aea347459e5ae60df4584a8b6b481bc3e1e137a2b9516b790d2d98abb254ab) is different from expected: (0xc079bf33a11cd29bd8427a0bfce75b58274db76022a32a64b7aa0fce88441280)

@rakita this now causes a test failure where we insert simple blocks because the root does not match, not sure what to do about this

### CODE REVIEW

**Comment by rakita** [comment]
The root should match I think.

One of the problems is from HistoryStateProvider here:
https://github.com/paradigmxyz/reth/blob/5598ecb9c9062573e2ee378294d57654a3377071/crates/storage/provider/src/providers/state/historical.rs#L95-L99

And it makes sense, if we want to calculate the merkle tree of the block that connects not to the tip but to the one of blocks before, first step would be to rewind the changes from the tip and then apply the new side block that we want to calculate root.
pinging @rkrasiuk just to confirm this.

We can maybe ignore this case if block does not extends the tip?

**Comment by rakita** [comment]
I dont get where the block state root is coming from, this test in BlockchainTree of block1 and block2 has correct hashes and it is different from the error one.
I searched code and can't find anything.

**Comment by Rjected** [comment]
Introduced:
 * `validate_and_execute_canonical` (validates state root, assumes the chain is extending the canonical tip)
 * `validate_and_execute_sidechain` (does not validate state root, assumes the chain is extending a sidechain)

Had some lifetime issues when trying to reuse code in `validate_and_execute_canonical` / `validate_and_execute_sidechain`, so there is some code duplication.

**Review by mattsse — COMMENTED** [review]
sick work, this looks great!

I have added a few notes in my review that I think are useful.

**Pull request merged**
