### PR TITLE
ci: docker release workflow

### PR DESCRIPTION
**Pull request by onbjerg**
Based off of #2677

Still WIP.

- Releases the following multiarch images on tag push (in the `vx.y.z` format):
  - latest (maxperf profile)
  - latest-dev (debug-fast profile)
  - vx.y.z (maxperf profile)
  - vx.y.z-dev (debug-fast profile)
- Releases the following multiarch images on main push (no tag):
  - latest-unstable (maxperf profile)
  - latest-unstable-dev (debug-fast profile)

### CODE REVIEW

**Comment by gakonst** [comment]
@onbjerg what should we do with this?

**Comment by gakonst** [comment]
Roger - anything blocking now?

**Comment by gakonst** [comment]
(@onbjerg bump on this)

**Comment by onbjerg** [comment]
New one in #2985 that finally builds locally but still has to pass CI test which is very slow because of no cache

**Pull request closed without merging**
