### PR TITLE
feat: write pruning config if --full is present

### LINKED ISSUE #7923: Write pruning config to `reth.toml` when `--full` is specified
### Describe the feature

Currently when you sync with `--full`, and then run `reth node` without `--full` (usually by mistake), everything will seem to run normally until the pipeline fails with `stage is missing static file data` during execution. Stage commands, lacking a `--full` option, often also fail.

We should instead use the pruning config, if it exists, in `reth.toml`. We should also write to this when the user specifies `--full`. This way, the stage commands do not need a `--full` argument, since they should also read from the reth config.

We could also warn the user if they attempt to run without `--full`, but have an existing pruning config, that this is a full node

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lakshya-sky**
Closes #7923

* Save prune config to reth.toml.
* warn if prune config present but run with --full.

### CODE REVIEW

**Review by mattsse — CHANGES_REQUESTED** [review]
I believe this should do it

can we add a simple test case for this using the LaunchContext struct

similar test setup as these

https://github.com/paradigmxyz/reth/blob/7b2dbd5daed9cda1a11f1b6ff599d2d7e93fa0e2/crates/config/src/config.rs#L342-L348

**Comment by lakshya-sky** [comment]
Changed code structure from previous commit. 
* added method to save config for `reth_config::Config`.
* moved concerned logic to a new static method in `LaunchContext`.
* added tests.

**Review by Rjected — APPROVED** [review]
this makes sense to me, iirc we want to replace confy eventually but this works for now

**Review by mattsse — APPROVED** [review]
lgtm, ty

**Pull request merged**
