### PR TITLE
chore(db): make database error codes signed

### LINKED ISSUE #1160: Change database errors to use signed integers
### Describe the feature

Currently [`reth_interfaces::db::Error`](https://github.com/paradigmxyz/reth/blob/13eea35c63967f948cd9043cf6088fe09728985e/crates/interfaces/src/db.rs#L3) uses `u32` to store the database error code, and `libmdbx-rs`'s `Error` [performs the conversion](https://github.com/paradigmxyz/reth/blob/13eea35c63967f948cd9043cf6088fe09728985e/crates/storage/libmdbx-rs/src/error.rs#L99). The underlying C implementation uses [signed integers](https://github.com/paradigmxyz/reth/blob/13eea35c63967f948cd9043cf6088fe09728985e/crates/storage/libmdbx-rs/mdbx-sys/libmdbx/mdbx.h#L1801), which makes it difficult to find the cause of errors.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MegaRedHand**
Closes: https://github.com/paradigmxyz/reth/issues/1160

This PR modifies _libmdbx-rs_'s `Error` to use signed error codes instead of unsigned.

Although, maybe `db::Error` should wrap a _libmdbx-rs_ `Error`, so the error messages translate the error code with `mdbx_strerror` to a more meaningful message.

### CODE REVIEW

**Comment by gakonst** [comment]
> Although, maybe db::Error should wrap a libmdbx-rs Error, so the error messages translate the error code with mdbx_strerror to a more meaningful message.

I think this is the right solution. Just having the number isn't useful, would like to see the string repr of it

**Comment by MegaRedHand** [comment]
Made the change. This makes _reth-interface_ depend on _reth-libmdbx_ though.

**Review by gakonst — CHANGES_REQUESTED** [review]
Yeah I think making the core `reth_interfaces` type be actually the MDBX type is a no-go, and agree the dependency is not right. Need to think about this.

**Review by rakita — APPROVED** [review]
lgtm,
@gakonst ping

**Review by gakonst — APPROVED** [review]

**Review by gakonst — APPROVED** [review]

**Comment by gakonst** [comment]
Thx @MegaRedHand !!

**Pull request merged**
