### PR TITLE
Add Ephemery support: Genesis function

### PR DESCRIPTION
**Pull request by terezaburianova**
This is WIP implementation of the Ephemery testnet genesis function implementation, according to #4340 .

### CODE REVIEW

**Comment by mattsse** [comment]
given that lighthouse signaled support

https://github.com/sigp/lighthouse/issues/4664

I think we can include that as well

**Comment by yorickdowne** [comment]
@mattsse Still in the backlog? Would be cool to have, though not essential.

**Comment by T-ess** [comment]
> @mattsse Still in the backlog? Would be cool to have, though not essential.

Will get to it this month. Need to polish the code, fix broken tests + write new ones, get feedback from Reth team (and fix the functionality based on that, these are changes that touch some base functionality) and fix any conflicts before merge, otherwise the functionality should be almost ready for Reth.

**Comment by yorickdowne** [comment]
@T-ess Pinging you on this. Did it ever make it in?

**Pull request closed without merging**
