### PR TITLE
ci: upgrade to geth 1.12.0-e501b3b0

### LINKED ISSUE #2873: Upgrade to geth 1.12.0-e501b3b0 in integration tests
### Describe the feature

Update `GETH_BUILD` to `1.12.0-e501b3b0` in the integration workflow and ensure that the tests pass.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by chirag-bgh**
Closes #2873

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
lgtm, is latest release build:

https://geth.ethereum.org/downloads

**Comment by mattsse** [comment]
@Rjected looks like this is deprecated now?

https://github.com/paradigmxyz/reth/blob/43f421d0b60723b5aee13095d38edc3781f8bc15/crates/staged-sync/tests/sync.rs#L90-L96

**Comment by Rjected** [comment]
Yeah, the `threads` param was deprecated
https://github.com/ethereum/go-ethereum/pull/27178/files#diff-9886da3412b43831145f62cec6e895eb3613a175b945e5b026543b7463454603L400

So this needs a change in ethers first: https://github.com/gakonst/ethers-rs/pull/2452

**Comment by Rjected** [comment]
Alright, now this needs a new ethers release and updates to our usage of `enable_mining` I think

**Comment by onbjerg** [comment]
Marking as blocked until we bump ethers

**Pull request merged**
