### PR TITLE
refactor(bin/reth): simply the code to walk key/value pairs

### PR DESCRIPTION
**Pull request by jsvisa**
simply the code to walk/list the key/value pairs

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
personally, I don't think this is simpler and makes it harder to read

wdyt @onbjerg ? I'm indifferent to this

**Comment by onbjerg** [comment]
yea imo not rly easier to read, mostly because of the combined condition

**Comment by onbjerg** [comment]
thank you for opening the PR, though, we always appreciate input on readability 😊

**Comment by jsvisa** [comment]
Sorry for it. At first glance, I wanted to merge the two statements into one, but it seems not working in Rust.

```rust
            if filter.reverse {
                Ok(cursor
                    .walk_back(None)?
                    .skip(filter.skip)
                    .filter_map(map_filter)
                    .take(filter.len)
                    .collect::<Vec<(_, _)>>())
            } else {
                Ok(cursor
                    .walk(None)?
                    .skip(filter.skip)
                    .filter_map(map_filter)
                    .take(filter.len)
                    .collect::<Vec<(_, _)>>())
            }

```

into 

```rust
    let mut walk = if filter.reverse {
        cursor.walk_back(None)?
    } else {
        cursor.walk(None)?
    };

    Ok(walk
        .skip(filter.skip)
        .filter_map(map_filter)
        .take(filter.len)
        .collect::<Vec<(_, _)>>())
```

But the compiler said the `if else`'s type is different, not working :)

So then I found some lines before the `if if if` can merge one :)

**Pull request closed without merging**
