### PR TITLE
fix(eth-wire): fix disconnect reason rlp decoding

### LINKED ISSUE #501: Incorrect disconnect reason RLP decoding
We will often get the following error when running the node:

```
2022-12-17T03:06:08.189138Z ERROR net::session: failed to receive message err=P2PStreamError(Rlp(Custom("disconnect reason should have 4 bytes")))
```

or this type of error:
```
2022-12-13T22:02:41.474824Z  WARN Outgoing pending session failed error=Some(P2PStreamError(Rlp(UnexpectedList)))
```

Disconnect reasons can appear snappy encoded or non-snappy encoded, and they can appear encoded as a single byte or encoded as a list. All encodings should be supported.

### PR DESCRIPTION
**Pull request by Rjected**
This currently tests decoding a set of known disconnect reason encodings, and checks that we can decode a disconnect reason from geth.

Traces for more decoding errors are also added.

Fixes #501 

TODO:
 - [x] fix disconnect reason decoding

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
nice, lgtm

**Comment by mattsse** [comment]
got this when testing locally

```
2022-12-17T20:28:14.276830Z ERROR net::session: failed to receive message err=P2PStreamError(Rlp(LeadingZero)) remote_peer_id=0x3fb71dafd5dc469fefcd31c3b99bf3554f20ca8420b172f4252504262b0a50ecb4371d75558821686415f24a1c3309be03477cd827700c67928d54c10f939cad
test connect::test_geth_disconnect ... ok
```

looks like a decoding issue @Rjected ?

**Comment by Rjected** [comment]
yeah that's definitely a decoding issue, maybe another possible disconnect format? I can try to repro and check the hex

**Comment by mattsse** [comment]
oh maybe this is not quite right:

https://github.com/paradigmxyz/reth/blob/34d6a62e61bbaa5a3d61708c10086662b6bc9368/crates/net/eth-wire/src/disconnect.rs#L134-L140

because rlp(u8) can be longer than 1 byte?

**Comment by Rjected** [comment]
Yeah we definitely need more tests, I'm aware sure of any disconnect reason greater than `0x7f` though so I think it's unlikely the u8 would be encoded as multiple bytes

**Comment by mattsse** [comment]
hmm, right.

looks related to this pr though.

also the encode fn has

```
 vec![*self as u8].encode(out); 
```

which encodes as list, but decode does not?

**Comment by Rjected** [comment]
well, it should skip over any rlp list header, so the decoding should support that format

I also ran it with `reth_eth_wire=trace` and got this:
```
2022-12-17T21:24:22.892312Z  WARN reth_eth_wire::p2pstream: Failed to decode disconnect message from peer err=LeadingZero msg=01010000
```

looks geth is encoding the reason as a zero byte here (instead of `0x80`)? this is also not valid rlp? but I guess we need to decode it anyways?

**Comment by Rjected** [comment]
also hmm, there is another error with the geth disconnect test, we are getting:
```
2022-12-17T21:57:29.942409Z ERROR net::session: failed to receive message err=P2PStreamError(Disconnected(UselessPeer)) remote_peer_id=0x3ebc27eb60789c27362096c7c7138dac17e799498a048efc3ee201ee553c51c7ab8c99d9e0d8183b7bfb14033e89369e53d80fa2acf4870c755296782d230d5e
```

instead of a `SessionEstablished` event

**Comment by mattsse** [comment]
I'm really having a hard time understanding the specialized encoding decoding for disconnectreason tbh

what reason is this supposed to be:

```
[crates/net/eth-wire/src/disconnect.rs:132] &buf = [
    1,
    0,
    0,
]

```

also this comment is not accurate, right? because we're doing `rlp([self as u8])`

https://github.com/paradigmxyz/reth/blob/c695062f1369a495fb0b47bb63f41d778469dfa2/crates/net/eth-wire/src/disconnect.rs#L109-L113

**Comment by onbjerg** [comment]
> well, it should skip over any rlp list header, so the decoding should support that format
> 
> I also ran it with `reth_eth_wire=trace` and got this:
> 
> ```
> 2022-12-17T21:24:22.892312Z  WARN reth_eth_wire::p2pstream: Failed to decode disconnect message from peer err=LeadingZero msg=01010000
> ```
> 
> looks geth is encoding the reason as a zero byte here (instead of `0x80`)? this is also not valid rlp? but I guess we need to decode it anyways?

Mirroring here from Discord, RLP encodes non-list integers below 0x7f as their raw value and geth's disconnect reasons are all below that, so 0 would be encoded as just 0 (presumably)

**Comment by onbjerg** [comment]
> well, it should skip over any rlp list header, so the decoding should support that format
> 
> I also ran it with `reth_eth_wire=trace` and got this:
> 
> ```
> 2022-12-17T21:24:22.892312Z  WARN reth_eth_wire::p2pstream: Failed to decode disconnect message from peer err=LeadingZero msg=01010000
> ```
> 
> looks geth is encoding the reason as a zero byte here (instead of `0x80`)? this is also not valid rlp? but I guess we need to decode it anyways?

Mirroring here from OOB, RLP encodes non-list integers below 0x7f as their raw value and geth's disconnect reasons are all below that, so 0 would be encoded as just 0 (presumably)

**Review by mattsse — APPROVED** [review]
lgtm now

can followup with the unexpected disconnect separately.

any way to reproduce this @Rjected?

**Comment by Rjected** [comment]
unfortunately have not been able to reproduce except for that one time

**Comment by mattsse** [comment]
this was related to #520 
geth responds with `DisconnectRequested` when it sees an incoming `DisconnectRequested` which was not caught due to misconfigured `disconnecting` state

**Pull request merged**
