### PR TITLE
chore: add missing match arms in mdbx Error::to_err_code

### PR DESCRIPTION
**Pull request by lambdaclass-user**
This PR improves the error messages from the `libmdbx-rs` crate. It adds missing match arms for some mdbx errors, which resulted in `unreachable!()` when printing. Also adds a custom message for the `Error::DecodeErrorLenDiff` variant.

### CODE REVIEW

**Comment by gakonst** [comment]
Before merging this, when did you encounter this bug?

**Comment by lambdaclass-user** [comment]
I encountered it while adding tests to https://github.com/paradigmxyz/reth/pull/704
I can't reproduce it though.

**Review by onbjerg — COMMENTED** [review]
I think we should remove the `unreachable!()` statement to make sure we exhaust the pattern match the next time around

**Comment by lambdaclass-user** [comment]
The `Error::DecodeErrorLenDiff` variant has no _mdbx_ error code as far as i know. How should we treat it? I was thinking of returning a `Result<u32, Error>` in `to_err_code`, but i'm not sure how we would handle the `Err` in `From<Error> for u32`.

**Comment by onbjerg** [comment]
Hmm, not sure. I think this is fine for now then. Thanks :smile:

**Review by onbjerg — APPROVED** [review]

**Pull request merged**
