### PR TITLE
chore: remove optimism feature from optimism crate

### LINKED ISSUE #11116: Feature audit: `optimism`
### Describe the feature

A lot of optimism crates have an optimism feature that enables optimism features in common crates. The optimism specific crates should just have these enabled by default, and not have them gated by an `optimism` feature.

For example, `reth-evm-optimism` has this feature which is pointless, it should just enable `optimism` in all the subcrates by default:

https://github.com/paradigmxyz/reth/blob/2684594ec163ec8553b633356960a9711fd2b688/crates/optimism/evm/Cargo.toml#L44-L50

We should go over all op-reth specific crates and remove the `optimism` feature, and instead enable the `optimism` feature on common subcrates by default in these

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by 0xkrane**
closes https://github.com/paradigmxyz/reth/issues/11116

made an attempt to remove the feature across the board and then update any op-reth tests that use this feature

### CODE REVIEW

**Comment by 0xkrane** [comment]
@onbjerg did we have a resolution on where we should/shouldn't remove this feature? saw @emhane replied in the thread so pinging both of you to understand if there are things i should be weary of

will resolve conflicts in the mean time

**Comment by 0xkrane** [comment]
some tests pass locally but fail in CI., for example `can_handle_blobs`:

```
cargo test --package reth-node-ethereum --test e2e -- blobs::can_handle_blobs --exact --show-output 
```

also not sure why the `lint/book` stuff is failing, don't think this PR touches it

**Comment by 0xkrane** [comment]
all issues seem to be downstream of:

```
    /// Returns the receipt root for all recorded receipts.
    /// Note: this function calculated Bloom filters for every receipt and created merkle trees
    /// of receipt. This is a expensive operation.
    pub fn receipts_root_slow(&self, _block_number: BlockNumber) -> Option<B256> {
        #[cfg(feature = "optimism")]
        panic!("This should not be called in optimism mode. Use `optimism_receipts_root_slow` instead.");
        #[cfg(not(feature = "optimism"))]
        self.receipts.root_slow(
            self.block_number_to_index(_block_number)?,
            reth_primitives::proofs::calculate_receipt_root_no_memo,
        )
    }
```

this seems to be called with optimism feature on instead of off

**Comment by onbjerg** [comment]
we should remove it from the crates that are specifically for optimism as it does not make sense to use them without the feature at all

**Comment by 0xkrane** [comment]
sorry have been busy! will come back to this PR this week.

**Comment by hai-rise** [comment]
@0xkrane I can help if you need an extra hand on this 🙏.

**Comment by mattsse** [comment]
sorry this drifted too much and this will become a non issue shortly

**Pull request closed without merging**
