### PR TITLE
test: `eth_getProof` without storage proof

### LINKED ISSUE #3634: Improve serde test coverage for rpc-types
### Describe the feature

a lot of types in the `rpc-types` don't have serde test coverage

## TODO

* get some sample responses from other nodes (alchemy, infura): for example `cast rpc eth_getBlockByNumber "latest" false --rpc-url "https://eth-mainnet.alchemyapi.io/v2/f"` 
* add serde rountrip tests with reth types:
  1. deserialize sample response
  2. serialize into serde_json::Value, assert that sample response (as Value) is a match

bonus points for adjusting order of reth fields to match other clients (sample response) 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by supernovahs**
Tests for eth_getProof without storage proof . Please let me know if the test is alright.  Then I will work on more tests.
Thx

Closes #3634

### CODE REVIEW

**Comment by supernovahs** [comment]
@mattsse Could u take a look at the commit please?
I'll then work on more tests 
Thx

**Comment by onbjerg** [comment]
cc @mattsse

**Review by mattsse — APPROVED** [review]
nice!

tysm

**Comment by mattsse** [comment]
@supernovahs ty!

for more common things, we should also add a note how we got the sample from, for example the json request that gave us the sample response

**Pull request merged**
