### PR TITLE
feat: tasks executor metrics in grafana

### LINKED ISSUE #8332: Integrate critical task metrics in grafana dashboard
### Describe the feature

we have these useful metrics but don't have them in the dashboard:

https://github.com/paradigmxyz/reth/blob/043b4a9cda8d738283b414897335c1863bfd34c2/crates/tasks/src/metrics.rs#L7-L19

## TODO
* integrate a graph in grafana similar to 

https://github.com/paradigmxyz/reth/blob/043b4a9cda8d738283b414897335c1863bfd34c2/etc/grafana/dashboards/reth-mempool.json#L1454-L1492

needs #8263

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by greged93**
Adds the `TaskExecutorMetrics` to Grafana. Resolves #8332.

### CODE REVIEW

**Review by Rjected — CHANGES_REQUESTED** [review]
Do you mind adding a screenshot to the PR description?

You also need to do "Export for sharing externally", the UIDs need to be a variable:
Screenshot 2024-10-16 at 6 01 52 PM

**Comment by greged93** [comment]
sure! here is the screenshot for the two dashboards:
Screenshot 2024-10-17 at 00 05 25

**Comment by greged93** [comment]
forgot to mention that I decided not to have the rate for the critical tasks, as this was not very interesting as there is very little change in the amount of critical tasks running.

**Review by Rjected — APPROVED** [review]
lgtm, thanks!

**Comment by onbjerg** [comment]
I'm not sure I understand the second panel, how is it stopping -2 tasks per second?

**Review by Rjected — CHANGES_REQUESTED** [review]
> I'm not sure I understand the second panel, how is it stopping -2 tasks per second?

Actually yeah, looking at it a second time, I don't think we should use the rate this way. Let's just use start, since they seem to just be the negative of each other?

**Review by onbjerg — COMMENTED** [review]
in the same go as @Rjected's comment, let's also rename the panels to have "tasks" in them, e.g. "Task executor critical tasks", "Task executor regular tasks":)

**Comment by greged93** [comment]
Will update! This was done because the issue itself mentioned adding the same metrics as the Tx and Rx messages, which use the rate

**Comment by greged93** [comment]
> since they seem to just be the negative of each other?

They are very close to each other, I think the diff in the rates when I was looking was usually round ~0.2 tasks/s at start up. 

> Let's just use start

So you only want a counter on the started tasks or what is currently displayed on the screen shot in blue i.e. the running tasks (= start - stop).

**Comment by greged93** [comment]
New screenshot
Screenshot 2024-10-18 at 10 05 13

**Review by Rjected — CHANGES_REQUESTED** [review]
only one nitpick, otherwise this looks good!

**Review by Rjected — APPROVED** [review]
lgtm!

**Review by mattsse — APPROVED** [review]

**Pull request merged**
