### PR TITLE
chore(primitives): Update keccak256 implementation

### PR DESCRIPTION
**Pull request by DaniPopes**
re-use keccak256 from ethers_core::utils

PS. excited for this :)

### CODE REVIEW

**Review by mattsse — CHANGES_REQUESTED** [review]
hmm, 

I'm leaning against this, because this now makes it harder to eventually phase out `ethers_core`

there is no real benefit in reusing the ethers_core function

wdyt @gakonst

**Comment by DaniPopes** [comment]
Some code was using ethers_core::keccak256 while other the primitives version, which is essentially the same code with an extra .into(); I can revert back to the current implementation of keccak256 while keeping the other changes

**Comment by mattsse** [comment]
sg, ideally everything should use the primitves fn

**Review by gakonst — APPROVED** [review]
LGTM - welcome to the reth repository, good to see you again :)

**Review by mattsse — APPROVED** [review]
ty!

**Pull request merged**
