### PR TITLE
fix(net): prevent bad loop if no peers available

### PR DESCRIPTION
**Pull request by mattsse**
The exit condition for the poll loop only checked if there are requests, but it also depends on whether there are available peers.

This adds another check for available peers.

### CODE REVIEW

**Review by gakonst — CHANGES_REQUESTED** [review]
LGTM - Can we test the case of no peers available terminating properly?

**Comment by mattsse** [comment]
adding a test

**Comment by mattsse** [comment]
> LGTM - Can we test the case of no peers available terminating properly?

adde

**Review by Rjected — APPROVED** [review]
ah yeah, the stream should be `Pending` if there are requests but no peers, lgtm!

**Pull request merged**
