### PR TITLE
feat(storage): increase min page size to 8KB

### PR DESCRIPTION
**Pull request by shekhirin**
See https://github.com/paradigmxyz/reth/issues/5228 for motivation

### CODE REVIEW

**Comment by gakonst** [comment]
breaking change?

**Comment by shekhirin** [comment]
> breaking change?

Currently checking, hope not

**Comment by shekhirin** [comment]
It's not a breaking change, syncing the mainnet to compare the database size with 4KB.

**Comment by joshieDo** [comment]
its not a breaking change, but it only has an effect on new syncs right?

**Comment by shekhirin** [comment]
> its not a breaking change, but it only has an effect on new syncs right?

correct, and in case of existing database we fallback to its page size

**Comment by onbjerg** [comment]
ootl here - why do we want to increase to 8k? afaik no system is native 8k so this would likely be weird for the os/suboptimal in most cases

**Comment by shekhirin** [comment]
@onbjerg from https://github.com/paradigmxyz/reth/issues/5228:
> If we increase the page size 2x to 8KB, it will mainly:
> - Allocate less overflow pages because large values will more likely fit into one page
> - Reduce the size of freelist, thus improving the search on inserts of large values
> 
> But it comes at a cost: not matching the OS page size means more I/O (Erigon estimates it at 10%) more.

**Comment by shekhirin** [comment]
Ok, both fresh sync with 8KB and running on a 4KB previously synced database work fine, so it's a backward-compatible change.

**Review by joshieDo — APPROVED** [review]

**Comment by shekhirin** [comment]
RPC benchmarks done with `flood trace_block`
```console
    ┌─────────────────┐
    │ success vs load │
    └─────────────────┘
      rate (rps)  │     4kb  │     8kb  │  4kb / 8kb
    ──────────────┼──────────┼──────────┼─────────────
             250  │  100.0%  │  100.0%  │     100.0%
             500  │   98.1%  │  100.0%  │      98.1%
           1,000  │  100.0%  │  100.0%  │     100.0%
           1,500  │   98.2%  │   97.9%  │     100.4%

    ┌────────────────────┐
    │ throughput vs load │
    └────────────────────┘
      rate (rps)  │  4kb (rps)  │  8kb (rps)  │  4kb / 8kb
    ──────────────┼─────────────┼─────────────┼─────────────
             250  │      249.6  │      249.7  │     100.0%
             500  │      489.6  │      499.1  │      98.1%
           1,000  │      998.4  │      998.4  │     100.0%
           1,500  │    1,440.7  │    1,440.1  │     100.0%

    ┌─────────────┐
    │ p90 vs load │
    └─────────────┘
      rate (rps)  │   4kb (s)  │   8kb (s)  │  4kb / 8kb
    ──────────────┼────────────┼────────────┼─────────────
             250  │  0.037454  │  0.035055  │     106.8%
             500  │  0.142456  │  0.037905  │     375.8%
           1,000  │  0.047614  │  0.039912  │     119.3%
           1,500  │  0.721211  │  0.685840  │     105.2%
```

**Comment by shekhirin** [comment]
Canonical commit time: 4KB vs 8KB page size. Significant difference, 8KB is 40-50% (100-150ms) slower on average

image

**Pull request closed without merging**
