### PR TITLE
chore: rm deposit contract config for op

### PR DESCRIPTION
**Pull request by mattsse**
does not exist for op, can be removed

ref https://github.com/paradigmxyz/reth/pull/11415

### CODE REVIEW

**Review by joshieDo — APPROVED** [review]
@shekhirin op doesnt need this right?

**Review by shekhirin — APPROVED** [review]
LGTM

**Comment by shekhirin** [comment]
Can we check the codepath for full node? What will the receipts pruning do

**Comment by mattsse** [comment]
https://github.com/paradigmxyz/reth/blob/d5ddb4129d3464d0f5cbfdd7547528bdb278cd59/crates/node/core/src/args/pruning.rs#L106-L111

for op this would never delete receipts, unsure if correct @shekhirin ?

**Comment by shekhirin** [comment]
@mattsse if there's no deposit contract, then we will prune `MINIMUM_PRUNING_DISTANCE` which seems to be fine?

**Comment by mattsse** [comment]
yeah this seems fine

**Pull request merged**
