### PR TITLE
ci: automatically set pr labels upon open

### LINKED ISSUE #6637: Automatically set pr labels upon open
### Describe the feature

Update actions to set labels on PRs that have "close #XXXX" in the description. Labels on the PR should match labels on the issue. This action should run when a PR is opened. If the PR doesn't have "close #XXXX" in the description, it doesn't get labeled.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AbnerZheng**
close https://github.com/paradigmxyz/reth/issues/6637

### CODE REVIEW

**Comment by AbnerZheng** [comment]
Looks like the action has to be given permissions to update label of PR. I tested it upon my project, and since I am the owner, the permission is granted by default.
ref https://github.com/AbnerZheng/reth/pull/11

**Review by mattsse — APPROVED** [review]
oh this is pretty cool and useful.

pending tests

**Comment by AbnerZheng** [comment]
It doesn't work right now, requiring to grant permission for the permission.

see error message here: https://github.com/paradigmxyz/reth/actions/runs/8670674936/job/23778971393

**Review by onbjerg — CHANGES_REQUESTED** [review]
can we move the script out to its own file in the .github folder, like we do in foundry-rs/foundry? it makes it easier to work with

**Comment by onbjerg** [comment]
cc @gakonst on the perms

**Comment by AbnerZheng** [comment]
> can we move the script out to its own file in the .github folder, like we do in foundry-rs/foundry? it makes it easier to work with

Done, and I have tested the extract script upon my project, and it successfully label the PR. 
https://github.com/AbnerZheng/reth/pull/12

**Review by onbjerg — APPROVED** [review]

**Pull request merged**
