### PR TITLE
fix: convert empty topic vec to vec None

### LINKED ISSUE #3851: Log filter is broken when a topic is empty
### Describe the bug

When calling `eth_getLogs` with such a filter:
```json
{
  "topics": [
    ["0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925"],
    [],
    ["0x0000000000000000000000000c17e776cd218252adfca8d4e761d3fe757e9778"],
  ]
}
```
The topics filter is completely ignored, all logs from the block range are returned.

However, it works when instead of `[]` we pass `[null]`, although it should be equivalent.

NB: I don't have a Reth instance running to test, I tested against the shared RPC URL during the Reth presentation at EthCC ;)

### Steps to reproduce

This can be tested w/
```bash
curl <RETH_RPC> -H "Content-Type: application/json" --data '{"method":"eth_getLogs","params":[{"fromBlock": "0xfc359e", "toBlock": "0xfc359e", "topics": [["0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925"], [], ["0x0000000000000000000000000c17e776cd218252adfca8d4e761d3fe757e9778"]]}],"id":1,"jsonrpc":"2.0"}' | jq '.result'
```

### Node logs

_No response_

### Platform(s)

_No response_

### What version/commit are you on?

_No response_

### What database version are you on?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by mattsse**
Closes #3851

topics are super cursed

this fixes a bug where an empty vec messed with the flatten logic, that always expects a value: [null]

this maps [] to [null] which behave identically

### CODE REVIEW

**Review by Rjected — APPROVED** [review]
lgtm, yeah looks kind of cursed

**Comment by ngotchac** [comment]
I find the definition of the topics type a bit convoluted. Currently it's defined as:
```rust
type Topic = ValueOrArray<Option<H256>>;
type Topics = [Option<Topic>; 4];
```

It would make more sense IMO to have
```rust
type Topic = HashSet<H256>;
```

We would only ever use `ValueOrArray<Option<H256>>` in de-serialization, to create an `Option<HashSet<H256>>`. We shouldn't really care, after de-serialization, whether it was passed as a value or an array. We want to know if there was a filter (the `Option` part), and if so, the values we want to filter on (as an `HashMap` to easily check contained values).

WDYT?

**Comment by ngotchac** [comment]
I have an implementation available here if you want to have a look: https://github.com/paradigmxyz/reth/compare/main...ngotchac:reth:ngotchac/fix-events-topics-filter

I'm not sure whether it's wanted, but if it is, I'd be glad to open a PR :)

**Comment by mattsse** [comment]
Only using the cursed options in deserde makes sense to make
I'll take a look at this thanks

**Comment by mattsse** [comment]
Would love to look at a Pr of yours

**Pull request merged**
