### PR TITLE
perf: add an LRU cache for EVM objects

### PR DESCRIPTION
**Pull request by onbjerg**
**WIP** Sometimes I will add longer messages to the bodies of the commits to explain the current state, but this is likely to take a few days since some larger refactors are needed to bring this to an ideal state.. As such, there are bound to be a lot of nits, so I'd like to keep the in-progress reviews scoped to just larger changes (i.e. direction), then we can take the nits later :smile: 

@mattsse The crate I use for the cache uses `lru` internally, but I wonder if it is worth (performance wise) to fork it and use `schnellru` instead? Do you know if the advertised improvement in `schnellru` is generally applicable? W-TinyLFU is essentially 2 internal LRUs + a counting mechanism and a bloom filter, so it might not be a lot of work to fork

Based off of #2076, since `ExecutorCache` is meant to be generic, and the only way to read from the cache in a way that would not break most of reth is by implementing a custom `revm` database. Ideally, we would be able to use `PostState` + the cache as the database backing, but the `PostStateProvider` was changed in a way where it is not useable outside of the blockchain tree.

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
this is great.

this adds a new provider type that wraps another provider and a cache.
so a lookup is
check cache -> Hit -> return else fetch, insert, return

re cache, the schnellru claims up to 2x faster lookups because of the underlying map (indexmap), but would this be significant here?

the code however https://github.com/asyncth/wtinylfu could be easily ported to schnellru I believe (same interface)
wouldn't be surprised if it's just: replace the type and add some generic bounds

**Comment by gakonst** [comment]
@onbjerg what is missing for getting this over the line?

**Comment by gakonst** [comment]
@onbjerg the merge conflict looks scary but IIRC you had already started working on this rebase? good to move forward with this given we merged blcok level indexing

**Comment by onbjerg** [comment]
Closing this and splitting unrelated changes into new PRs, while copying over the cache work on a clean branch based off of master

**Pull request closed without merging**
