### PR TITLE
chore(net): expose max concurrent `GetPooledTransactions` reqs in cli

### PR DESCRIPTION
**Pull request by emhane**
Exposes `GetPooledTransactions` requests concurrency parameters in cli

### CODE REVIEW

**Comment by rkrasiuk** [comment]
@emhane semicolons ... please 🙏

**Review by mattsse — COMMENTED** [review]
something went wrong here

perhaps it's easier to close this and reopen again

**Comment by emhane** [comment]
> something went wrong here
> 
> perhaps it's easier to close this and reopen again

you need to be more specific for me to follow. what went wrong?

**Review by mattsse — APPROVED** [review]
last time I reviewed this, this had a changeset of 2k slocs

but looks this was just a rebasing issue

**Pull request merged**
