### PR TITLE
chore(net): move `reth_eth_wire::DisconnectReason` to `reth-eth-wire-types`

### PR DESCRIPTION
**Pull request by emhane**
Ref https://github.com/paradigmxyz/reth/issues/10002

### CODE REVIEW

**Comment by emhane** [comment]
unsure why I get this error @Rjected @mattsse @DaniPopes ?

```
error[E0277]: the trait bound `reth_eth_wire_types::DisconnectReason: arbitrary::Arbitrary<'_>` is not satisfied
   --> crates/net/eth-wire/src/p2pstream.rs:654:16
    |
654 |     Disconnect(DisconnectReason),
    |                ^^^^^^^^^^^^^^^^ the trait `arbitrary::Arbitrary<'_>` is not implemented for `reth_eth_wire_types::DisconnectReason`
```

**Review by mattsse — CHANGES_REQUESTED** [review]
supportive, you're just missing eth-wire-types with arbitrary enabled as dev dep like

https://github.com/paradigmxyz/reth/blob/05f391d1b4506106c6e25a513d9b6ebdcdebc153/crates/net/eth-wire/Cargo.toml#L43-L43

**Comment by emhane** [comment]
> reth-primitives = { workspace = true, features = ["arbitrary"] }

it is already

**Review by mattsse — APPROVED** [review]

**Comment by mattsse** [comment]
the arb tests are usually feature gated like this `#[cfg(any(test, feature = "arbitrary"))]` which requires dev dep with arb feature for `test`

@emhane I assume this can also be moved 

https://github.com/paradigmxyz/reth/blob/f1cd10a3170f8b2e2a9afd15349863a3445dee67/crates/net/eth-wire/src/p2pstream.rs#L644-L648

**Pull request merged**
