### PR TITLE
feat: add subpool transaction streams

### PR DESCRIPTION
**Pull request by mattsse**
add convenience stream type for filtering new transactions by pool

ref #3649

### CODE REVIEW

**Comment by fomotrader** [comment]
Would be good for historical purposes to maybe explain the reasoning for needing different pools? Do they return different types of transactions or the same type? 

Is this done to help us prepare for EIP-4844?

- `basefee-pool`
- `queued-pool`
- `basefee sub-pool`

**Comment by mattsse** [comment]
this design is explained in the crate docs

**Comment by fomotrader** [comment]
Found it https://github.com/paradigmxyz/reth/blob/main/crates/transaction-pool/src/pool/txpool.rs#L69

**Comment by fomotrader** [comment]
So there are different pools to hold transactions in different states, very interesting as the distinction make whats happening in the txpool clear. 

Would you say txs in the queued pool could be viewed as invalid and therefore not be that useful? Wonder if it's better for a node to just drop them? I've seen cases where ruggers submit txs with large nonce gaps to create fake trading volume on pools.

**Comment by mattsse** [comment]
> Would you say txs in the queued pool could be viewed as invalid and therefore

they can't be included in the next block because an ancestor tx is missing or sender lacks funds for example, so yes invalid at this point in time from the pov of the node

> Wonder if it's better for a node to just drop them?

you can't drop them outright because they might still get valid/unblocked when the ancestor arrives, for example, the node receives tx n+1 before tx n

I believe the tx are ranked by distance, so those are dropped first

**Comment by fomotrader** [comment]
This looks good to me, any ideas when you'll merge it, I'd like to use it in https://github.com/paradigmxyz/reth/pull/3649

**Review by onbjerg — APPROVED** [review]
lgtm

**Pull request merged**
