### PR TITLE
feat(CI): add timeout to CI

### LINKED ISSUE #4727: Add CI jobs timeout
### Describe the feature

The default timeout is 6hrs, it probably should be 30 or 60 minutes

### Additional context

See this failure: https://github.com/paradigmxyz/reth/actions/runs/6264391349/job/17010983086

### PR DESCRIPTION
**Pull request by tcoratger**
Should resolve #4727.

### CODE REVIEW

**Comment by DaniPopes** [comment]
Can we do this for tests too?

**Review by DaniPopes — CHANGES_REQUESTED** [review]
Can we add these to tests workflows too?

**Comment by tcoratger** [comment]
> Can we add these to tests workflows too?

@DaniPopes Yes sure, I've just extended, tell me if this is better or if you see other places with this should be set like that? For me this seems good like that, I've pushed the timeout to 60 minutes at the most critical places.

**Comment by DaniPopes** [comment]
It's missing integration I think
Also a tip @tcoratge use "resolve" or similar keywords so the issue gets automatically closed on merge: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

**Comment by tcoratger** [comment]
> It's missing integration.yml I think then we're good Also a tip @tcoratge use "resolve" or similar keywords so the issue gets automatically closed on merge: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

Done, thanks for the tip, I don't know why I was thinking that "solve" did the same job but I should have checked if the issues closed automatically...

**Review by DaniPopes — APPROVED** [review]

**Pull request merged**
