### PR TITLE
feat: add `pending|queued` txs pool helpers 

### LINKED ISSUE #12091: Add more helpers to get transactions by state and sender
### Describe the feature

we currently have:

https://github.com/paradigmxyz/reth/blob/fa59bd512e877e4677890b5c154b80816c07480e/crates/transaction-pool/src/traits.rs#L270-L279

and https://github.com/paradigmxyz/reth/blob/fa59bd512e877e4677890b5c154b80816c07480e/crates/transaction-pool/src/traits.rs#L349-L353

but we don't have 
* `get_{pending|queued}_transactions_by_sender(s)`

## TODO
* add missing functions

This should be solved via layered functions and not defaults because more performant, eg:

https://github.com/paradigmxyz/reth/blob/fa59bd512e877e4677890b5c154b80816c07480e/crates/transaction-pool/src/lib.rs#L447-L449

calls

https://github.com/paradigmxyz/reth/blob/fa59bd512e877e4677890b5c154b80816c07480e/crates/transaction-pool/src/pool/mod.rs#L682-L685

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lean-apple**
Closes https://github.com/paradigmxyz/reth/issues/12091.

Add 2 helpers `get_pending_transactions_by_sender` and `get_queued_transactions_by_sender`.

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
lgtm

**Comment by mattsse** [comment]
needs `cargo +nightly fmt`

can't do it myself, because opened from main branch

**Comment by lean-apple** [comment]
> needs `cargo +nightly fmt`
> 
> can't do it myself, because opened from main branch

AH I 

> needs `cargo +nightly fmt`
> 
> can't do it myself, because opened from main branch

Done

**Comment by lean-apple** [comment]
Any reason why the `compact-codec / compact-codec ` is failing @mattsse  ?

**Comment by mattsse** [comment]
unrelated failure

**Pull request merged**
