### PR TITLE
`ensure_difficulty_valid` using canonical rules for `Header`

### PR DESCRIPTION
**Pull request by tcoratger**
## Description
This pull request introduces the complete implementation of the `ensure_difficulty_valid` function for the `Header` module. Additionally, it includes a unit test to validate the correct behavior of the function under different hardfork scenarios.

## Changes Made
- Added the implementation of the `ensure_difficulty_valid` function in the `Header` module.
- Introduced unit tests to verify the correctness of the new function.

## Why
- The `ensure_difficulty_valid` function is a crucial component of the header validation process, ensuring adherence to Ethereum's canonical difficulty rules.
- The addition of this function enhances the overall reliability and correctness of the Ethereum header validation.

## Testing
- Unit tests have been added to cover different scenarios, including cases under Byzantium and Muir Glacier hardforks.

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
not that familiar with these consensus checks, defer to @Rjected and @rakita

**Comment by rakita** [comment]
imo I wouldn't include it as it is considered a legacy, less logic to check.

**Comment by tcoratger** [comment]
> imo I wouldn't include it as it is considered a legacy, less logic to check.

@rakita Are we sure of that because when we look at the yellow paper it is one of the conditions (the second on the list) which defines a header block as valid or not in the same way as the gas limit greater than 5000 for example and which is itself tested in the consensus check.

image

On the other hand, I saw a similar calculation system that was done on the Go node (https://github.com/ethereum/go-ethereum/blob/cd0770ea6855a7704059aa7c591d0e83dcb21231/consensus/ethash/consensus.go#L345-L403) so I figured it was useful to add here. Perhaps it would be better to have a simple utility function that would calculate the difficulty rather than integrating that into the validation? But I have a doubt because it also seems important to me to check that even if I agree that it involves additional validation steps and therefore necessarily calculation costs.

**Comment by rakita** [comment]
> > imo I wouldn't include it as it is considered a legacy, less logic to check.
> 
> @rakita Are we sure of that because when we look at the yellow paper it is one of the conditions (the second on the list) which defines a header block as valid or not in the same way as the gas limit greater than 5000 for example and which is itself tested in the consensus check.
> 
> image
> 
> On the other hand, I saw a similar calculation system that was done on the Go node (https://github.com/ethereum/go-ethereum/blob/cd0770ea6855a7704059aa7c591d0e83dcb21231/consensus/ethash/consensus.go#L345-L403) so I figured it was useful to add here. Perhaps it would be better to have a simple utility function that would calculate the difficulty rather than integrating that into the validation? But I have a doubt because it also seems important to me to check that even if I agree that it involves additional validation steps and therefore necessarily calculation costs.

It got deprecated with the merge, and with PoS the tip of the chain gets voted on so the chain is verified from the tip to the genesis. That verification does not have a purpose, if it was not that complex it would be fine but as it is not, imo I would not include it.

The only possible place where this can be usable is in tests, but afaik even there we didn't find a need for it.

**Comment by tcoratger** [comment]
> > > imo I wouldn't include it as it is considered a legacy, less logic to check.
> > 
> > 
> > @rakita Are we sure of that because when we look at the yellow paper it is one of the conditions (the second on the list) which defines a header block as valid or not in the same way as the gas limit greater than 5000 for example and which is itself tested in the consensus check.
> > image
> > On the other hand, I saw a similar calculation system that was done on the Go node (https://github.com/ethereum/go-ethereum/blob/cd0770ea6855a7704059aa7c591d0e83dcb21231/consensus/ethash/consensus.go#L345-L403) so I figured it was useful to add here. Perhaps it would be better to have a simple utility function that would calculate the difficulty rather than integrating that into the validation? But I have a doubt because it also seems important to me to check that even if I agree that it involves additional validation steps and therefore necessarily calculation costs.
> 
> It got deprecated with the merge, and with PoS the tip of the chain gets voted on so the chain is verified from the tip to the genesis. That verification does not have a purpose, if it was not that complex it would be fine but as it is not, imo I would not include it.
> 
> The only possible place where this can be usable is in tests, but afaik even there we didn't find a need for it.

Np, feel free to close :)

**Comment by Rjected** [comment]
thank you for the effort, but I think we want to omit difficulty checks because PoW is deprecated and that information now does not need to be verified, so I'm going to close this

**Pull request closed without merging**
