### PR TITLE
Add `queued_outgoing_messages` panel for grafana

### PR DESCRIPTION
**Pull request by syjn99**
This PR Addresses #12254. Added `queued_outgoing_messages` per second next to `Incoming Gossip and Requests` panel. The expression looks like:
```plain
"rate(reth_network_queued_outgoing_messages{instance=\"$instance\"}[$__rate_interval])"
```

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
this does a lot more than adding a new panel, so not sure how to best review this 

can we limit this pr to the additional panel?

@Rjected

**Comment by syjn99** [comment]
@mattsse Seems like plugin version is bumped, and its diff is included. I pushed new commit so that reviewing this code would be much easier.

**Review by Rjected — COMMENTED** [review]
this looks good to me, do you mind adding a screenshot of the panel?

**Review by mattsse — APPROVED** [review]

**Comment by syjn99** [comment]
image

Here's a partial screenshot of the dashboard. New panel is next to `Incoming Gossip and Requests` panel. Ran clients for few hours, on [ephemery network](https://ephemery.dev/) with fuzzing with tx fuzzer. 
As there are no queued messages, the panel looks flat. Does this look good to you?

**Review by Rjected — APPROVED** [review]
nice lgtm

**Pull request merged**
