### PR TITLE
dev: add `requests` to `EthBuiltPayload`

### LINKED ISSUE #12070: Add requests as additional field to EthBuiltPayload
### Describe the feature

currently we extract the requests from the optional ExecutedBlock data:

https://github.com/paradigmxyz/reth/blob/5a5ec73c37d2f84e27db7bc86d5c7893f641ca87/crates/ethereum/engine-primitives/src/payload.rs#L149-L152

this is problematic because the `ExecutedBlock` is optional and not strictly required by the builder:

https://github.com/paradigmxyz/reth/blob/5a5ec73c37d2f84e27db7bc86d5c7893f641ca87/crates/ethereum/engine-primitives/src/payload.rs#L29-L30

## TODO
* add requests as an optional field instead and set when creating `EthBuiltPayload::new`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by greged93**
Adds an optional field `requests` to the `EthBuiltPayload`.

Resolves #12070

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
cool, this lgtm, pending @onbjerg

**Review by onbjerg — COMMENTED** [review]
we have something similar here that would be nice to get rid of: https://github.com/paradigmxyz/reth/blob/a87d654c55eacc8f4878affd671e08df7fa536a6/crates/e2e-test-utils/src/engine_api.rs#L65-L72

**Comment by greged93** [comment]
@onbjerg do you want to add `requests(&self)` on `BuiltPayload`?

**Comment by onbjerg** [comment]
yeah I think honestly that'd be great. I think we want it to be `Option<Requests>`, since some chains don't support requests, eg. optimism

**Comment by greged93** [comment]
sorry yes my bad, `Option<Requests>`

**Review by mattsse — APPROVED** [review]

**Pull request merged**
