### PR TITLE
fix: fix another out of bounds error

### PR DESCRIPTION
**Pull request by mattsse**
another hotfix for ref https://github.com/paradigmxyz/reth/issues/3278

this loop's logic was just wrong.

this at least gets rid of the out of bounds error

### CODE REVIEW

**Review by Rjected — APPROVED** [review]

**Review by onbjerg — CHANGES_REQUESTED** [review]
this is wrong too, because if `sum_gas_used < threshold_gas_used` on the first check, then the reward we should push to `rewards` is for `tx_index = 0`, not `tx_index = 1`

fix is to do `tx_index < transactions.len() - 1` (since we increment first thing in the loop). this is also how geth does it, ref https://github.com/ethereum/go-ethereum/blob/8c288b528d3c9653c84321387e78687ed02134d7/eth/gasprice/feehistory.go#L118-L126

**Comment by mattsse** [comment]
is this obsolete with #3288 ?

**Comment by onbjerg** [comment]
@mattsse yes, I reimplemented it from scratch, although I am testing against erigon rn (will finish tmrw) to see if we differ

**Comment by mattsse** [comment]
awesome, closing this then, not worth spending time on this

**Pull request closed without merging**
