### PR TITLE
docs(net): add bird's eye view docs

### PR DESCRIPTION
**Pull request by mattsse**
add high level docs 

Note: the mermaid diagram currently fails to render for some reason, however on mermaid.live it works just fine...

ref https://github.com/paradigmxyz/reth/issues/446

### CODE REVIEW

**Comment by gakonst** [comment]
Tracking in https://github.com/mersinvald/aquamarine/issues/28 and I think could be nice to make aquamarine work with https://github.com/mersinvald/aquamarine/issues/27 too.

**Comment by frehberg** [comment]
https://github.com/mersinvald/aquamarine/pull/29 may solve the "fetching mermaid.min.js from remote unpack"

**Comment by mersinvald** [comment]
https://github.com/mersinvald/aquamarine/pull/29 is merged, please upgrade to 0.2.0

**Comment by gakonst** [comment]
appreciate you folks.

**Pull request merged**
