### PR TITLE
fix: mandatory `to` for EIP-4844

### LINKED ISSUE #7273: Make txeip4844 to mandatory
### Describe the feature

Per https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4844.md#blob-transaction:
> The field `to` deviates slightly from the semantics with the exception that it MUST NOT be `nil` and therefore must always represent a 20-byte address. This means that blob transactions cannot have the form of a create transaction.

ref https://github.com/alloy-rs/alloy/pull/355

ref https://github.com/ethereum/go-ethereum/blob/ba2dd9385c2a51134e520083dc732787a813b107/core/types/tx_blob.go#L38-L38

compared to

https://github.com/ethereum/go-ethereum/blob/ba2dd9385c2a51134e520083dc732787a813b107/core/types/tx_dynamic_fee.go#L34-L34

## TODO

change:

https://github.com/paradigmxyz/reth/blob/0ca853fbb00e837030663b470cd5fa86395efa5c/crates/primitives/src/transaction/eip4844.rs#L57-L57

to Address

cc @klkvr 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by klkvr**
Closes #7273

Changes `TransactionKind` to `Address`

Currently `EthApi::send_transaction` will throw `ConflictingFeeFieldsInRequest` not only in case of conflicting fee fields but also when blob transaction is missing blob fields or `to`, perhaps this error should be more specific?

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
great, 
I'm okay with the rpc error.

@joshieDo please investigate if this breaks compact decoding on existing dbs

**Comment by joshieDo** [comment]
As it is, it does. At the moment `main` will only read 20 bytes to decompress an address if `TransactionKind` is `Call`.

However, we could replicate this behaviour by manually implementing `Compact` for Address and replicating the same behaviour. Only read 20 bytes if the address is not 0x0

**Comment by mattsse** [comment]
> As it is, it does. At the moment `main` will only read 20 bytes to decompress an address if `TransactionKind` is `Call`.
> 
> However, we could replicate this behaviour by manually implementing `Compact` for Address and replicating the same behaviour. Only read 20 bytes if the address is not 0x0

sorry, not following yet, Address is already Compact.

all blob txs have `Kind::Call`

**Comment by mattsse** [comment]
friendly bump @joshieDo

**Comment by joshieDo** [comment]
### context:
`Compact` encodes to `<bitflags><buffer>`.

`TransactionKind` occupies 1 bit on the bitflag header of this transaction type.

On decoding, if the bit is set: we read 20 bytes, otherwise we don't. 

### issue:
If we replace this type by only `Address`, old transactions will still have that bit. I'm not sure how big is the bitflags header, it may have no impact. if the bitflag occupies 2 bytes

But if in the future we add a new field to this type that uses some bitflag, then old transactions would read that bit even though it's unrelated.

**Comment by mattsse** [comment]
superseded by #8291

**Pull request closed without merging**
