### PR TITLE
clippy: add `if_not_else` clippy lint

### PR DESCRIPTION
**Pull request by tcoratger**
@mattsse let me know what you think about this one:

> Negations reduce the readability of statements.

### CODE REVIEW

**Review by mattsse — APPROVED** [review]

**Comment by mattsse** [comment]
smol conflict

**Comment by tcoratger** [comment]
> smol conflict

@mattsse fixed

**Review by mattsse — APPROVED** [review]

**Comment by shekhirin** [comment]
Just so I know, are you doing these fixes automatically via `clippy fix`? Some of these changes are a bit invasive and touch untrivial logic (like https://github.com/paradigmxyz/reth/pull/10524/files#diff-102c8ff04a628fe92ccef5f8d0ac6eef702ad248c7a2b8e59e65cf12bb05287f), but if it's done automatically, then it's okay with me 🙂

**Comment by tcoratger** [comment]
> Just so I know, are you doing these fixes automatically via `clippy fix`? Some of these changes are a bit invasive and touch untrivial logic (like https://github.com/paradigmxyz/reth/pull/10524/files#diff-102c8ff04a628fe92ccef5f8d0ac6eef702ad248c7a2b8e59e65cf12bb05287f), but if it's done automatically, then it's okay with me 🙂

Yeah most of them via clippy fix and the other ones via the terminal suggestion, copy and paste when clippy fix doesn't work

**Pull request merged**
