### PR TITLE
add minor improvements

### PR DESCRIPTION
**Pull request by tcoratger**

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
lgtm, pending @Rjected

**Comment by Blaeaea** [comment]
> lgtm, pending @Rjected

```rust
 Self::Valid(transaction) => transaction,
            Self::ValidWithSidecar { transaction, .. } => transaction,
            Self::Valid(transaction) | Self::ValidWithSidecar { transaction, .. } => transaction,
 ```

This is pretty not readable for someone who is reading the code. I think this should be changed

**Review by Rjected — APPROVED** [review]
lgtm, `total_size` is an improvement

**Comment by tcoratger** [comment]
> > lgtm, pending @Rjected
> 
> ```rust
>  Self::Valid(transaction) => transaction,
>             Self::ValidWithSidecar { transaction, .. } => transaction,
>             Self::Valid(transaction) | Self::ValidWithSidecar { transaction, .. } => transaction,
> ```
> 
> This is pretty not readable for someone who is reading the code. I think this should be changed
> 
> I do prefer the first implementation rather the second one, which is not human readable.
> 
> The goal is to make a clear code, not something hard.

For me this is really equivalent in term of readability @Blaeaea, with the or statement, pretty clear to me, but up to you @mattsse @Rjected? I believe that this is what is promoted everywhere else in the rest of the codebase hence this refactoring when I saw it, but if I have to revert, I revert, tell me?

**Comment by Rjected** [comment]
> > > lgtm, pending @Rjected
> > 
> > 
> > ```rust
> >  Self::Valid(transaction) => transaction,
> >             Self::ValidWithSidecar { transaction, .. } => transaction,
> >             Self::Valid(transaction) | Self::ValidWithSidecar { transaction, .. } => transaction,
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is pretty not readable for someone who is reading the code. I think this should be changed
> > I do prefer the first implementation rather the second one, which is not human readable.
> > The goal is to make a clear code, not something hard.
> 
> For me this is really equivalent in term of readability @Blaeaea, with the or statement, pretty clear to me, but up to you @mattsse @Rjected? I believe that this is what is promoted everywhere else in the rest of the codebase hence this refactoring when I saw it, but if I have to revert, I revert, tell me?

I think this is fine and readable, going to merge now!

**Pull request merged**
