### PR TITLE
perf(db): `decode` and `decompress` directly from borrowed data instead

### PR DESCRIPTION
**Pull request by joshieDo**
Change `decode<B: Into<Bytes>>(...)` to `decode<B: AsRef<[u8]>>(...)`
Change `decompress<B: Into<Bytes>>(...)` to `decompress<B: AsRef<[u8]>>(...)`

But the real change is in the way we get our data from `libmdbx-rs`. 

So far, if a page is [dirty](https://libmdbx.dqdkfa.ru/group__c__statinfo.html#ga71ec584464114d2924b71eeb6b80e3fb), `libmdbx-rs` copies it right away. (`allocation 1`) 
https://github.com/paradigmxyz/reth/blob/main/crates/storage/libmdbx-rs/src/codec.rs#L31-L39

We then take that data and as far as I can see, we **always** decode it right away as well. Which involves further allocations.  So why not skip `allocation 1` whether it's dirty or not ? 

### Before:
image

### After:
image

It should make all stages faster, especially ones that spend most of their time reading from the db:

### Benchmarks

image

### CODE REVIEW

**Comment by gakonst** [comment]
@onbjerg PTAL and merge if good

**Review by rakita — APPROVED** [review]
lgtm

**Review by onbjerg — APPROVED** [review]
In general LGTM, but I am unsure why we need the feature flag? Should we not just use this everywhere?

**Comment by gakonst** [comment]
> In general LGTM, but I am unsure why we need the feature flag? Should we not just use this everywhere?

Yeah I think probably just a bit scary to remove that code? We hsould be using this everywhere

**Comment by joshieDo** [comment]
yeah that was the rationale, but open to remove the flag

**Pull request merged**
