### PR TITLE
Set namespace in one place

### PR DESCRIPTION
**Pull request by FilipLaurentiu**
Set namespace value property for the derive macro for each JSON-RPC Namespace.

This is easier to read and easier to fork and change the prefix. E.g "eth_" -> "ovm_"

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
> This is easier to read and easier to fork and change the prefix. E.g "eth_" -> "ovm_"

I don't necessarily agree on the former, but the latter conveniences me.

This has a nice side effect, which is that searching for a particular method implementation by its name, such as "eth_syncing", now only shows the actual impl and not the definition, which is very convenient. Because we added the full method name the impl's docs.

> E.g "eth_" -> "ovm_"

perhaps we can even find a solution for this so it is configurable

**Comment by FilipLaurentiu** [comment]
> > This is easier to read and easier to fork and change the prefix. E.g "eth_" -> "ovm_"
> 
> I don't necessarily agree on the former, but the latter conveniences me.
> 
> This has a nice side effect, which is that searching for a particular method implementation by its name, such as "eth_syncing", now only shows the actual impl and not the definition, which is very convenient. Because we added the full method name the impl's docs.
> 
> > E.g "eth_" -> "ovm_"
> 
> perhaps we can even find a solution for this so it is configurable

Setting the value in a configurable file seems very convenient, not sure how to do it.
But only the `eth_` namespace will take advantage of it in case of a fork

**Comment by mattsse** [comment]
https://github.com/paradigmxyz/reth/actions/runs/5223282659/jobs/9429951842?pr=3084

this doesn't seem to work as expected

**Comment by mattsse** [comment]
looks like this is missing:

https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc-api/src/engine.rs#L103-L106

**Comment by FilipLaurentiu** [comment]
> looks like this is missing:
> 
> https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc-api/src/engine.rs#L103-L106

I missed that, sry https://github.com/paradigmxyz/reth/pull/3084/commits/57109429d2b87a4ef4736147ce9aa1a3225774ce

**Comment by mattsse** [comment]
I'm still encountering this

> thread 'main' panicked at 'No conflicts: MethodAlreadyRegistered("call")', /Users/Matthias/git/rust/reth/crates/rpc/rpc-builder/src/lib.rs:773:35

**Comment by mattsse** [comment]
if you run the node and log the `methods` at that line you'll that they don't have a prefix

no idea why though

**Comment by mattsse** [comment]
ah omg lol

> #[cfg_attr(not(feature = "client"), rpc(server))]

**Comment by FilipLaurentiu** [comment]
> ah omg lol
> 
> > #[cfg_attr(not(feature = "client"), rpc(server))]
> 
> there are two mutually exclusive derive attributes because of the client feature, and we're missing the `namespace` argument here...

```
#[cfg_attr(not(feature = "client"), rpc(server))]
#[cfg_attr(feature = "client", rpc(server, client))]
#[rpc(namespace = "eth")]
#[async_trait]
pub trait EthApi {
```
This seems to work and is much cleaner

**Comment by mattsse** [comment]
agree,
I can't remember why I did the mutual exclusive server,client thing in the first place but I think it was because it failed to compile on an older version

**Comment by FilipLaurentiu** [comment]
> > ah omg lol
> > > #[cfg_attr(not(feature = "client"), rpc(server))]
> > 
> > 
> > there are two mutually exclusive derive attributes because of the client feature, and we're missing the `namespace` argument here...
> 
> ```
> #[cfg_attr(not(feature = "client"), rpc(server))]
> #[cfg_attr(feature = "client", rpc(server, client))]
> #[rpc(namespace = "eth")]
> #[async_trait]
> pub trait EthApi {
> ```
> 
> This seems to work and is much cleaner

Run some tests and doesn't seems to work so I add the namespace for both attributes :disappointed: @mattsse  https://github.com/paradigmxyz/reth/pull/3084/commits/b3acd6126fb9d9681886dc69e29284ed57ccfd28

**Pull request merged**
