### PR TITLE
Feat: devmode launcher implementation

### LINKED ISSUE #10104: add devmode launcher implementation
with the new orchestrator trait design, we can now implement a proper devmode orchestrator directly on top of the auto-seal-consensus implementation and we no longer need to mimic the engine API internally:

https://github.com/paradigmxyz/reth/blob/eda161af2c4cb3457eed9d3b81b9b2e5f55db313/crates/consensus/auto-seal/src/task.rs#L159-L163

## TODO
* Add `DevOrchestrator` implementation that drives the MiningTask and advances the node
https://github.com/paradigmxyz/reth/blob/eda161af2c4cb3457eed9d3b81b9b2e5f55db313/crates/consensus/auto-seal/src/task.rs#L83-L89
* This should start as a duplicated implementation of `MiningTask` that emits new `ExecutedBlock`
* the `DevOrchestrator` then uses that block to advance the chain by persisting the block, similar to 

https://github.com/paradigmxyz/reth/blob/eda161af2c4cb3457eed9d3b81b9b2e5f55db313/crates/engine/tree/src/tree/mod.rs#L541-L544

see for reference:

https://github.com/paradigmxyz/reth/blob/eda161af2c4cb3457eed9d3b81b9b2e5f55db313/crates/ethereum/node/src/launch.rs#L259-L259

### PR DESCRIPTION
**Pull request by malik672**
closes #10104

### CODE REVIEW

**Comment by malik672** [comment]
@mattsse

**Review by mattsse — CHANGES_REQUESTED** [review]
all of this should go in a separate file to not pollute the existing code.

I'd even prefer a new crate for now because we need more stuff from the engine crate https://github.com/paradigmxyz/reth/blob/1f5fb90bc83dd48d38e2f376790125d68ba92f3e/crates/engine/tree/Cargo.toml#L2-L2

what we need is like an `Orchestrator` that is a stream that advances the chain by polling the mining mode.
It would actually be great if we could leverage the existing payloadbuilder stack for this and trigger a payload based on the MindingMode

lmk if I should provide step by step instructions

I think first we want a fresh crate for this, then a minimal mining task that is ideally wired with a PayloadBuilderHandle and a miningmode

**Comment by malik672** [comment]
ok, will do that and probably ask for help in the next pr

**Comment by malik672** [comment]
> all of this should go in a separate file to not pollute the existing code.
> 
> I'd even prefer a new crate for now because we need more stuff from the engine crate
> 
> https://github.com/paradigmxyz/reth/blob/1f5fb90bc83dd48d38e2f376790125d68ba92f3e/crates/engine/tree/Cargo.toml#L2-L2
> 
> what we need is like an `Orchestrator` that is a stream that advances the chain by polling the mining mode. It would actually be great if we could leverage the existing payloadbuilder stack for this and trigger a payload based on the MindingMode
> 
> lmk if I should provide step by step instructions
> 
> I think first we want a fresh crate for this, then a minimal mining task that is ideally wired with a PayloadBuilderHandle and a miningmode

@mattsse what should i name the new crate ?

**Comment by mattsse** [comment]
maybe dev-node or smth

**Comment by malik672** [comment]
@mattsse can I get some instructions?

**Comment by malik672** [comment]
@mattsse made some new changes

**Comment by mattsse** [comment]
marking as complted via #11703

**Pull request closed without merging**
