### PR TITLE
chore: clean up remaining uses of ethers-core

### PR DESCRIPTION
**Pull request by DaniPopes**

### CODE REVIEW

**Review by gakonst — APPROVED** [review]

**Comment by gakonst** [comment]
How do we intend to phase out that type?

**Comment by DaniPopes** [comment]
@gakonst Given that we only need a small fraction of all the chains and methods in NamedChain, and this enum is the only thing use ethers-core for (outside of tests), I think we should make our own temporary NamedChain enum in reth-primitives

**Comment by gakonst** [comment]
Seems fine w me -- do we want to move parts of this in [`alloy-rs/chains`](https://github.com/alloy-rs/chains/)?

**Comment by DaniPopes** [comment]
No I don't think so, at least not yet

**Pull request merged**
