### PR TITLE
Split MevApi trait into two #11036

### PR DESCRIPTION
**Pull request by 0xriazaka**

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
great

**Comment by mattsse** [comment]
imports need to be adapted, please dont open prs from your fork main branch

**Comment by emhane** [comment]
> please dont open prs from your fork main branch

git remote add riazaka git@github.com:0xriazaka/reth.git
git push riazaka

**Comment by 0xriazaka** [comment]
> > please dont open prs from your fork main branch
> 
> git remote add riazaka [git@github.com](mailto:git@github.com):0xriazaka/reth.git git push riazaka

**Comment by 0xriazaka** [comment]
> > please dont open prs from your fork main branch
> 
> git remote add riazaka [git@github.com](mailto:git@github.com):0xriazaka/reth.git git push riazaka

should i do another pr with this way?

**Comment by emhane** [comment]
> > > please dont open prs from your fork main branch
> > 
> > 
> > git remote add riazaka [git@github.com](mailto:git@github.com):0xriazaka/reth.git git push riazaka
> 
> should i do another pr with this way?

no this was helpful for matze on to how push changes to your main branch :)

**Pull request merged**
