### PR TITLE
chore(sdk): Add `NodePrimitives::BlockHeader` and `NodePrimitives::BlockBody`

### PR DESCRIPTION
**Pull request by emhane**
Based on https://github.com/paradigmxyz/reth/pull/12683

Ref https://github.com/paradigmxyz/reth/issues/12358

### CODE REVIEW

**Review by mattsse — CHANGES_REQUESTED** [review]
hmm, why do we need this if the header and body type are already defined in the block type?

**Comment by emhane** [comment]
> hmm, why do we need this if the header and body type are already defined in the block type?

it makes it a lot easier to access the header type...one could argue the same about transition too otherwise

**Comment by mattsse** [comment]
I suspect this would make things harder when enforcing bounds because then we need to restrict `Header` to `Block::Header`.

don't think we should do this

**Comment by emhane** [comment]
> I suspect this would make things harder when enforcing bounds because then we need to restrict `Header` to `Block::Header`.
> 
> don't think we should do this

we have the same problem with signed tx, must be restricted to `Self::Block: Block<Body: Body<Transaction: Self::SignedTx>>`

**Comment by emhane** [comment]
I don't see why this is a problem when `NetworkPrimitives` does this exactly...

**Comment by emhane** [comment]
can't figure out what's wrong with the features here https://github.com/paradigmxyz/reth/actions/runs/11921032967/job/33224297145?pr=12647

**Review by mattsse — APPROVED** [review]
seems okay, I guess this would make accessing the type more convenient.

pending ci

**Pull request merged**
