### PR TITLE
 Refactor: use fully-qualified paths in Compact derives(Deon Branch)

### PR DESCRIPTION
**Pull request by 0xDeon**

### CODE REVIEW

**Comment by DanielEmmanuel1** [comment]
@mattsse All done, create a new PR from Deon branch

**Review by mattsse — APPROVED** [review]
lgtm, ty

closes #11862

**Comment by DanielEmmanuel1** [comment]
@mattsse Is it okay if i apply for other issues, is that allowed?

**Comment by mattsse** [comment]
sure, but please no more unrelated doc changes :)

**Comment by DanielEmmanuel1** [comment]
Sure, duly noted

**Pull request merged**
