### PR TITLE
Move and rename ```BeaconConsensus``` to ```EthBeaconConsensus```

### LINKED ISSUE #8137: Move and rename BeaconConsensus
### Describe the feature

https://github.com/paradigmxyz/reth/blob/f281bbdccda2e08b1d5db651f25c7735ea1d63ed/crates/consensus/beacon-core/src/lib.rs#L22-L22

should be renamed to `EthBeaconConsensus`
and moved to crates/ethereum/consensus

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rupam-04**
Closes #8137

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
ty

**Comment by rupam-04** [comment]
> ty

apparently someone was working on it already so I closed my PR

**Comment by willco-1** [comment]
ah i see it was approved. i will pick up another issue, sorry for the confusion

**Comment by rupam-04** [comment]
> ah i see it was approved. i will pick up another issue, sorry for the confusion

no problem, all the best and happy contributing

**Review by mattsse — APPROVED** [review]

**Pull request merged**
