### PR TITLE
fix(tree): retain `max(additional, max_reorg_depth)` block hashes

### PR DESCRIPTION
**Pull request by shekhirin**
The actual number of canonical hashes we need to retain in memory is the maximum of how many is required for reorg (64) and for EVM execution (256). So it's 256.

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
hmm, I get 64+256 but why the tree needs this I'm not convinced, because they should still be in the database and therefore available during execution?

**Comment by onbjerg** [comment]
seconding matt, if the block is not covered by max_reorg_depth, then it is present in the db

**Comment by rakita** [comment]
@mattsse @onbjerg It is inside db, but with this, it is cached in memory. In general, clients cache block hash values. if desired we can go without it.

**Comment by shekhirin** [comment]
@rakita I can't find the place where we check the cache in implementations of `DatabaseRef::block_hash`, is it used now?

**Comment by rakita** [comment]
> @rakita I can't find the place where we check the cache in implementations of `DatabaseRef::block_hash`, is it used now?

We clone the hashmap, as it is small, and use it inside I think `BundleStateDataProvider`

**Comment by shekhirin** [comment]
> > @rakita I can't find the place where we check the cache in implementations of `DatabaseRef::block_hash`, is it used now?
> 
> We clone the hashmap, as it is small, and use it inside I think `BundleStateDataProvider`

ah, I was still looking at the outdated revm API 😄 I see it now, thanks.

**Comment by shekhirin** [comment]
@mattsse @onbjerg I added the comments explaining the need for `256`, lmk if my understanding is wrong.

**Review by mattsse — APPROVED** [review]
okay, I get it now,

my issue was that it wasn't obvious to me where we're passing the canonical hashes to the state provider.

I think worth adding a note to this type as well

https://github.com/paradigmxyz/reth/blob/d846199525f459d1d1d74e9ff50fcb853903d46e/crates/blockchain-tree/src/canonical_chain.rs#L4-L12

**Review by mattsse — APPROVED** [review]

**Pull request merged**
