### PR TITLE
feat(trie): read-only root calculation

### PR DESCRIPTION
**Pull request by rkrasiuk**
This PR extract all write operations from the state root calculation. This is needed in order to be able to compute state root with read-only transaction, for instance, for payload building.

All operations are buffered in `TrieUpdates` and flushed if needed. Alternatively, root calculation can be called without a buffer and all updates will be omitted. 

This PR also introduces checkpoints for state root calculation. Computation is checkpointed in order to avoid keeping database updates in memory and enabling intermediate commits.

### CODE REVIEW

**Comment by rkrasiuk** [comment]
Converted back to draft because for this to work, the cursors over hashed tables need to be abstracted away.

**Review by gakonst — COMMENTED** [review]
Yep we need an abstraction to make the hashes cursors read from memory to pass them hashed state from the blockchain tree

**Review by gakonst — APPROVED** [review]
We reviewed this together on a call and this is good to go when we have confirmed that:
1. Hive passes (cc @Rjected)
3. Mainnet or Sepolia syncs both full/incremental

Full send. We're almost there :) cc @mattsse you should be unblocked on the remaining work for merkle root building soon, combined with #2288

**Comment by Rjected** [comment]
There's a failure in one of the `eth_createAccessList` tests it seems like:
this PR + hive: https://github.com/paradigmxyz/reth/actions/runs/4759013384/jobs/8458269107
main + hive: https://github.com/paradigmxyz/reth/actions/runs/4759097858/jobs/8458083596

The failure:
```diff
response differs from expected:
 {
   "id": 1,
   "jsonrpc": "2.0",
   "result": {
     "accessList": [
       0: {
         "address": "0xbb00000000000000000000000000000000000000",
         "storageKeys": [
+          0: "0x0000000000000000000000000000000000000000000000000000000000000003",
           1: "0x0000000000000000000000000000000000000000000000000000000000000001",
         ]
       }
     ],
     "gasUsed": "0x6b0e"
   }
 }
```

For some reason the `+` line of the diff isn't showing up in hive, and I'm not sure why we're having a `createAccessList` failure when this PR doesn't seem to touch anything related to that on first glance. I'll do some digging to figure out what's wrong

**Comment by rkrasiuk** [comment]
Hive test passed after merging main
https://github.com/paradigmxyz/reth/actions/runs/4761790254/jobs/8463510010

This PR passed state root calculation on sepolia at height 3m and mainnet height 8m. Merging in good faith and opening follow up perf PRs

**Pull request merged**
