### PR TITLE
docs: code layout map

### PR DESCRIPTION
**Pull request by igaray**
Added a map of the codebase to layout.md 

The image source is a GraphML file generated in [yEd](https://www.yworks.com/products/yed) but renderable by any graphml compatible editor. 

The layout has been updated to include the storage refactor.

### CODE REVIEW

**Comment by igaray** [comment]
The graphml source and rendered version could be moved to the assets folder if desired, but I left them close to the relevant documentation.

**Review by mattsse — CHANGES_REQUESTED** [review]
I think, having something like this is very useful.
It provides a very good overview.

My concern at this point is that this will change a lot, making this no longer accurate.

If you're up for it, I would suggest modeling the high-level components individually as embedded mermaid diagrams, this would make it easier to maintain.
we also don't need every single component/detail here in a large diagram, but rather those that are important as standalone diagrams.

having this on a per-crate/component level and in the code itself, just makes it easier to maintain, see the existing mermaid diagrams for example.

**Comment by gakonst** [comment]
hey @igaray just checking in! any plans to break this down in smaller diagrams / mermaid etc., or should we assign someone else? I think @0xKitsune might be interested. thanks for putting in the initial work!!

**Comment by 0xKitsune** [comment]
> I think @0xKitsune might be interested. thanks for putting in the initial work but yeah things are prob gonna change a bunch and i'd prefer we start pushing for mermaid diagrams in line with the code...lmk!

If it is up for grabs, I would be happy to jump on it. I am looking at the next part of the docs to work on. At the moment, I'm just finishing up ramping on some materials related to the P2P protocol.

**Comment by gakonst** [comment]
I'd say go for it unless @igaray responds by the time you're done 🙏

**Comment by igaray** [comment]
Heyo o/ end of year was pretty crazy, I'll have a much more time now for all of this. 
I agree with everything @mattsse said, in fact I wish these diagrams could be autogenerated but that's just the world we live in. 

I'll start with one and we'll see how it goes, and for now I'll close this PR.

Thanks for the feedback!

**Comment by gakonst** [comment]
> I'll start with one and we'll see how it goes, and for now I'll close this PR.

Give Mermaid a try!

https://github.com/paradigmxyz/reth/blob/346d50ebf4e32610fbf966b96ed4a8462ee15971/crates/net/network/src/fetch/client.rs#L22

**Pull request closed without merging**
