### PR TITLE
refactor(txpool): replace discard_worst from macro to plain code

### LINKED ISSUE #6370: Use plain code instead of a macro in the txpool `discard_worst` method
> I think we can make the discard_worst loop nicer and get rid of the ugly macros if we basically do the same loop in the truncate functions anyway

yep definitely

_Originally posted by @Rjected in https://github.com/paradigmxyz/reth/issues/6368#issuecomment-1924919770_

### PR DESCRIPTION
**Pull request by jsvisa**
close #6370

### CODE REVIEW

**Comment by jsvisa** [comment]
working with trait system to make the compile pass :)

**Comment by jsvisa** [comment]
@mattsse I'm sorry, I try to define a new `SubPoolExt` trait, with the methods as below:

```rust
pub trait SubPoolExt<T: PoolTransaction> {
    fn len(&self) -> usize;
    fn size(&self) -> usize;
    fn truncate_pool(&mut self, limit: SubPoolLimit) -> Vec<Arc<ValidPoolTransaction<T>>>;
}
```

So I can define a new function `discard` to replace the old macro's logic:

https://github.com/paradigmxyz/reth/blob/8ffa2b8809f78c93fb2d38227dcbf4ed42e12633/crates/transaction-pool/src/pool/txpool.rs#L763-L808

Then in `discard_worest` I can invoke it like that:

https://github.com/paradigmxyz/reth/blob/8ffa2b8809f78c93fb2d38227dcbf4ed42e12633/crates/transaction-pool/src/pool/txpool.rs#L751-L761


But `cargo check` said I can't do like it:

```bash
error[E0499]: cannot borrow `*self` as mutable more than once at a time
   --> crates/transaction-pool/src/pool/txpool.rs:756:24
    |
756 |         removed.extend(self.discard(self.config.blob_limit.clone(), "blob", &mut self.blob_pool));
    |                        ^^^^^-------^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^-------------------^
    |                        |    |                                               |
    |                        |    |                                               first mutable borrow occurs here
    |                        |    first borrow later used by call
    |                        second mutable borrow occurs here

error[E0499]: cannot borrow `self.blob_pool` as mutable more than once at a time
   --> crates/transaction-pool/src/pool/txpool.rs:756:77
    |
756 |         removed.extend(self.discard(self.config.blob_limit.clone(), "blob", &mut self.blob_pool));
    |                        ---- ------- first borrow later used by call         ^^^^^^^^^^^^^^^^^^^ second mutable borrow occurs here
    |                        |
    |                        first mutable borrow occurs here

For more information about this error, try `rustc --explain E0499`.
error: could not compile `reth-transaction-pool` (lib) due to 2 previous errors

```

Could you please give me some tips on how to archive this, thanks in advance.

**Review by mattsse — COMMENTED** [review]
hmm, turns out this is not trivial to do and the macro is actually a decent solution to prevent code duplication.

unsure yet how to proceed with this

**Comment by jsvisa** [comment]
yeah, let's keep as what it is right now.

**Comment by mattsse** [comment]
I've decided that a macro is actually still the most appropriate solution here

@jsvisa sorry for wasting your time on this

**Comment by jsvisa** [comment]
> I've decided that a macro is actually still the most appropriate solution here
> 
> 
> 
> @jsvisa sorry for wasting your time on this

Don't worry, I have the same feelings 😀

**Pull request closed without merging**
