### PR TITLE
feat: empty list for post-merge blocks

### LINKED ISSUE #10176: Return empty list for post-merge blocks in `BlockchainProvider2::ommers`
Since we don't expect to have pre merge blocks in memory, `BlockchainProvider2::ommers` should make sure that it still returns an empty vec if we are post-merge.

The DB provider does this:
https://github.com/paradigmxyz/reth/blob/48d4c798f9a96aa50dfe11b9f45212e33669aec4/crates/storage/provider/src/providers/database/provider.rs#L2006-L2015

Meaning, with the current implementation, `BlockchainProvider2::ommers` will return `None` for in-memory blocks when the user provides a hash, since it won't be able to find the corresponding block number.

### PR DESCRIPTION
**Pull request by mvares**
Closes: #10176

### CODE REVIEW

**Comment by mvares** [comment]
@Rjected, can you check out? ❤️

**Review by Rjected — CHANGES_REQUESTED** [review]
I think we want a different approach that modifies the `BlockchainProvider2`'s implementation. For example, in the `DatabaseProvider` implementation, you can see these lines:
```rust
            // If the Paris (Merge) hardfork block is known and block is after it, return empty
            // ommers.
            if self.chain_spec.final_paris_total_difficulty(number).is_some() {
                return Ok(Some(Vec::new()))
            }
```

Which accomplishes returning an empty list for post-merge blocks. The issue with the `BlockchainProvider2` implementation is that it might pass a `Hash` to `DatabaseProvider::ommers`. This would cause this line to be run:
```rust
        if let Some(number) = self.convert_hash_or_number(id)? {
```

Which would fail for blocks that are only in-memory, and not in the DB. So we essentially want something like what we already have in the `DatabaseProvider` implementation, but in the `BlockchainProvider2` implementation

**Comment by mvares** [comment]
@Rjected, if I check if the ID provided was Hash, does it make sense to throw a `Vec::new`?

**Comment by fgimenez** [comment]
hey @mvares I'm taking over this issue because it is blocking other work, pls feel free to work on any other task, thanks a lot for your effort!

**Comment by emhane** [comment]
can this be closed in favour of https://github.com/paradigmxyz/reth/pull/10286 @fgimenez ?

**Pull request closed without merging**
