### PR TITLE
engine: small refactor in `TreeState` `remove_by_hash`

### PR DESCRIPTION
**Pull request by tcoratger**

### CODE REVIEW

**Review by rkrasiuk — COMMENTED** [review]
why? this introduces additional unneeded hashmap lookups

**Comment by tcoratger** [comment]
> why? this introduces additional unneeded hashmap lookups

@rkrasiuk This is possible I missed something here but I think this is exactly the same no? Just removing the need for `hash_map::Entry::Occupied` or `btree_map::Entry::Occupied` and directly getting a mutable reference to the value corresponding to the key.

Saw the comment of @mattsse on https://github.com/paradigmxyz/reth/pull/11701, but for my personal knowledge, do you think this was equivalent or leading to additional overhead?

**Comment by rkrasiuk** [comment]
when you have an entry, you maintain the reference to the entry in the collection. in your code, when you call remove, it triggers another search to find the entry in question through the collection. the change is not equivalent and introduces additional overhead on removal

**Comment by tcoratger** [comment]
> @tcoratger when you have an entry, you maintain the reference to the entry in the collection. in your code, when you call remove, it triggers another search to find the entry in question through the collection. the change is not equivalent and introduces additional overhead on removal

Ah yes you are right understood your point you are right! Thanks for the explanation :)

**Pull request closed without merging**
