### PR TITLE
refactor(evm): unify `BlockExecutionOutput` and rm `EthExecuteOutput`

### PR DESCRIPTION
**Pull request by tcoratger**

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
I'm not very happy with the execution type situation but this doesn't really improve things because this now makes the state optional in a type that should always have the state.

**Comment by tcoratger** [comment]
> I'm not very happy with the execution type situation but this doesn't really improve things because this now makes the state optional in a type that should always have the state.

What do you think about reverting the Option to how it was before and replacing the `None` in the only place where it is used in `execute_state_transitions` with a `Default::default()` i.e. a default state?

I think it's still better to avoid scattering several types since here the type does exactly the same thing as the already existing `BlockExecutionOutput` type, wdyt?

**Comment by tcoratger** [comment]
@mattsse Just fixed, let me know

**Comment by tcoratger** [comment]
@mattsse Is there anything else to do here?

**Review by mattsse — COMMENTED** [review]
this is only an internal type so better to be explicit about what this represents, 

the way this currently works is a bit verbose for a variety of reasons, but imo this changes isn't very meaningful and could even end up being a footgun incase the default state is used incorrectly

**Pull request closed without merging**
