### PR TITLE
perf: use hashmaps for non-sortable state

### PR DESCRIPTION
**Pull request by onbjerg**
Account and storage plain state is inherently random access during execution. Currently, we store these in a `BTreeMap`.

By name alone, one would assume that this would perform a binary search on lookup of values, but it does not. In fact, all inserts and lookups in `BTreeMaps` use linear search, which slows down both of these operations considerably when the collection is large enough (which it often is for us).

The only reason we would want to use `BTreeMap` here over `HashMap` is if we could use the auto-sorted property of the BTree to perform faster inserts into the database, but plain state cannot be inserted in a sorted fashion, so we do not need this property

This should theoretically boost performance of execution somewhat, assuming the default hashing algorithm is fast enough. In the future we could switch the hashing algorithm for something else that is performant on small keys, since keys in both maps are 256 bits or less

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
this makes sense to me,

perhaps @rakita has some insight into `std::HashMap` vs `hashbrown::HashMap` wrt perf

**Comment by onbjerg** [comment]
@mattsse std hashmap is a re-export of hashbrown :) https://doc.rust-lang.org/src/std/collections/hash/map.rs.html#6

**Review by rkrasiuk — COMMENTED** [review]
> plain state cannot be inserted in a sorted fashion, so we do not need this property

can you elaborate on this pls? currently, we are inserting it in a sorted fashion using a cursor

**Comment by onbjerg** [comment]
> can you elaborate on this pls? currently, we are inserting it in a sorted fashion using a cursor

we are not, we are using `insert`, not `append`. it is impossible for us to use `append` since what state is updated is random, so there is no reason to really sort it. `insert` will always perform a search regardless of if it is sorted or not

we *could* technically sort the keys to *reduce* the time `insert` would search, but i think given the keys are random, on average we probably won't save much time(?) since it is unlikely the keys are neighbors, so `insert` always has to go back and search on average

**Review by rkrasiuk — CHANGES_REQUESTED** [review]
i'd like this benched, so we render a decision on whether it's indeed faster based on hard numbers, since we've debunked similar theories (for inserting changesets) in the past

**Comment by onbjerg** [comment]
@rkrasiuk in fact, we did benchmark this together a while ago, and IIRC it was slightly faster than using `BTreeMaps` because of the lookups. we can bench again though

**Comment by rkrasiuk** [comment]
@onbjerg we do not use a simple insert, we use a cursor which presumably always walks forward

**Comment by rkrasiuk** [comment]
agree w/ @joshieDo, at the very least we need to sort the before inserting

**Comment by onbjerg** [comment]
@rkrasiuk no, it does not only walk forward. `insert` searches around, this is how it has always been. `append` has a requirement that it can only walk forward and that the data it inserts must be at the end of the table. `insert` has no such requirement.

**Comment by onbjerg** [comment]
@rkrasiuk sure, we can benchmark this, and then benchmark with sorts, and then without sorts. but we already did that in the past, and sorting them was slower. it took 20 seconds to sort all the plain state last time we tried.

**Comment by rkrasiuk** [comment]
@onbjerg that's simply not correct. you are saying that we use `tx::insert` whereas we use `cursor::insert`. the difference is that the cursor is already positioned on the value we wrote before and, for sorted collection, will only walk forward since every key is greater than the previous one

**Comment by onbjerg** [comment]
@rkrasiuk i am not saying that. i am saying it doesn't just magically skip to the next key it wants to be at, it has to go back up to find the relevant branch page unless we happen to figure out that the key is on the immediate next database page. otherwise the implication is that `cursor.insert` iterates over all values <= the key we want to insert which is not the case.

my point here is that even if we sort, we have to go back to consult with the branch pages. you can clearly see this on a perf grab too, e.g. of txlookup, where we *do* sort before using `cursor.insert`. it still ends up spending a lot of time searching.

**Pull request closed without merging**
