### PR TITLE
chore(trie): move hash builder to primitives

### PR DESCRIPTION
**Pull request by rkrasiuk**
Move `HashBuilder` and its dependencies to the `primitives` crate to use for root calculations. This PR has **no functional changes**

Ref #2488

### CODE REVIEW

**Review by onbjerg — APPROVED** [review]
lgtm, although I wish we just had a trie crate. CI is failing

**Comment by rkrasiuk** [comment]
it's a bench regression, dk, maybe compilation time somehow affects it ><

**Comment by onbjerg** [comment]
Oh, strange. lgtm

**Review by mattsse — APPROVED** [review]
lgtm, 

needs rebase

**Pull request merged**
