### PR TITLE
Add custom beacon withdrawals example

### PR DESCRIPTION
**Pull request by dapplion**
Adds an example of modifying a post-block execution step. Specifically, it modifies the beacon withdrawal processing logic: do a system call instead of minting native tokens.

I have made some structs and fns pub to reduce diff. Please let me know if there are more opportunities to minimize the diff. There's duplicated code between this custom executor, the op executor and the eth executor.

### CODE REVIEW

**Review by gakonst — COMMENTED** [review]
feels like we should expose a better API via NodeBuilder for overriding the pre/post hooks more granularly, and for new system contracts, given BSC also uses it

**Comment by dapplion** [comment]
> feels like we should expose a better API via NodeBuilder for overriding the pre/post hooks more granularly, and for new system contracts, given BSC also uses it

Let me know if I can help with that

**Review by emhane — APPROVED** [review]
lgtm

**Comment by dapplion** [comment]
@mattsse do you want to merge this in as-is, and have the satisfaction of reducing code once https://github.com/paradigmxyz/reth/issues/11274 lands? Or wait to merge https://github.com/paradigmxyz/reth/issues/11274 before this PR

**Comment by fgimenez** [comment]
hey @dapplion thanks a lot for your work! now that #11274 is closed I've taken the opportunity to rebase this PR on top of main and update it to use the new composable executor abstraction with strategies. 

In the `BlockExecutionStrategy` impl I have filled the pre and post block execution methods same as you had before, but not the actual block transaction execution logic method, not sure if that's ok for the functionality you want to highlight.  

pls take a look and let me know if you have any questions!

**Review by Rjected — APPROVED** [review]
cool! lgtm

**Review by mattsse — APPROVED** [review]

**Comment by dapplion** [comment]
🎉 thanks for updating it to the custom executor

**Pull request merged**
