### PR TITLE
chore: exclude examples from workspace and check them in a separate CI job

### LINKED ISSUE #8451: exclude examples from workspace and check them in a separate CI job
### Describe the feature

currently all examples are compiled as part of the workspace:

https://github.com/paradigmxyz/reth/blob/76b32c8b5f3b9937ca507c75b4ba53cb0c83915e/Cargo.toml#L86-L104

we should put them in the exclude_members section and have a dedicated CI job just for examples

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jackwener**
close #8451

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
ty!

mind taking a look at this @DaniPopes

**Comment by mattsse** [comment]
@jackwener the examples job fails because there's no manifest in examples

is there a way to run all of them with some wildcard argument @DaniPopes ?

**Comment by DaniPopes** [comment]
Looks like this is not possible. `exclude` will completely exclude them from any command, `--workspace` too. I think the only possible solution here is to keep them in members but not in default-members.

**Comment by mattsse** [comment]
we solved this via

https://github.com/paradigmxyz/reth/pull/8953

**Pull request closed without merging**
