### PR TITLE
feat(consensus): sync pipeline until tree includes head

### PR DESCRIPTION
**Pull request by rkrasiuk**
Constantly sync the pipeline until the `BlockchainTree` tip includes the head hash.

### <samp>🤖 Generated by Copilot at 2b955c8</samp>

This pull request introduces some changes to the consensus engine, the stages module, and the blockchain tree module. The main goals are to refactor the engine code to use a generic trait and a struct for managing different stages and forkchoice states, to add a way to test pipeline delays in the stages module, and to add a function to check the canonicality of a block hash in the blockchain tree module. The affected files are `crates/consensus/beacon/src/engine/mod.rs`, `crates/stages/src/test_utils/set.rs`, `crates/stages/src/test_utils/stage.rs`, and `crates/executor/src/blockchain_tree/mod.rs`.

### CODE REVIEW

**Comment by gakonst** [comment]
copilot:walkthrough

**Comment by gakonst** [comment]
@rkrasiuk is this still relevant after the recent fixes?

**Comment by rkrasiuk** [comment]
not relevant anymore

**Comment by gakonst** [comment]
Because the changes were included in another PR?

**Pull request closed without merging**
