### PR TITLE
feat(primitives): increase minimum pruning distance

### PR DESCRIPTION
**Pull request by shekhirin**
https://github.com/paradigmxyz/reth/blob/8b2ff4f652d7d8e6d678dc2c5eb7c4952af8966d/crates/primitives/src/prune/target.rs#L8-L13

### CODE REVIEW

**Comment by kaliubuntu0206** [comment]
@shekhirin Is this a breaking change and thus we need to update our nodes?

**Comment by shekhirin** [comment]
@kaliubuntu0206 I think it's not, but we still need to test it.

The node should run just fine with new minimum pruning distance, and start persisting more blocks in database for the full node. As for the custom configured pruned node, this change may break the existing configuration, but shouldn't require a resync anyway.

**Review by onbjerg — APPROVED** [review]
looks good to me! pending another review

**Comment by joshieDo** [comment]
Can't select them in the PR, but there are a few comments in the docs saying that pruning distance is 128. should be changed or replaced with the actually var, so we can change it in the future without changing the docs.

regex:
`.*run.*128`

**Review by joshieDo — APPROVED** [review]

**Comment by shekhirin** [comment]
testing on existing full node

**Pull request merged**
