### PR TITLE
chore: turn off `reth-revm` default features

### PR DESCRIPTION
**Pull request by xJonathanLEI**
I could be missing something but It looks like internal crates don't really need default features of `reth-revm` judging by the fact that they still compile with it turned off.

Without this patch it's impossible to turn off `reth-revm` default features from downstream applications as long as they also use some of its dependencies.

### CODE REVIEW

**Review by mattsse — CHANGES_REQUESTED** [review]
thanks, features are a bit delicate, we're currently evaluating at which level we want or need to enforce revm features,

imo we should do this on the `node` crate level

so disable default features for reth-revm and revm on workspace level and then enable them in the ethereum-node and optimism-node crate

**Comment by xJonathanLEI** [comment]
Thanks for the input. I was worried that directly turning it off like this might come with performance implications - like, it still compiles, but with some performance features turned off. I guess I did run directly into this potential issue.

In that case we can add feature switches alongside the dependency graph to allow fine-grained control? Just so that we can have the ability to turn it off downstream. Please lmk if I should proceed with this. Thanks!

**Comment by xJonathanLEI** [comment]
Updated `reth-node-ethereum` and `reth-node-optimism` to enable those disabled features.

Also I just realized that I need to have the ability to turn off `secp256k1` and `blst` on `revm` too, which is also currently hard-coded to be enabled. So I updated the code to include those.

**Comment by mattsse** [comment]
yeah exactly, we need disable defaults on workspace level and need to enable where we need them

**Comment by xJonathanLEI** [comment]
Looking into why CI is failing

**Comment by mattsse** [comment]
likely because the state test crate also needs the revm features

**Comment by xJonathanLEI** [comment]
> likely because the state test crate also needs the revm features

I don't think so as I can run `cargo build --all --all-targets` just fine, and it looks like some tests fail to _run_, but builds fine.

Anyway I will take a look at this later. Thanks for your time!

**Comment by mattsse** [comment]
trying to get this over the line now @xJonathanLEI 
ty for your patience 🙏

**Comment by xJonathanLEI** [comment]
@mattsse Thank you! I think there must be something wrong with my diffs though. The Ethereum state tests just keep failing. I might need to look into this.

**Comment by xJonathanLEI** [comment]
Quick note: this command reproduces the state test failure:

```console
cargo test --release -p ef-tests --features "asm-keccak ef-tests" general_state_tests::st_create2
```

**Comment by xJonathanLEI** [comment]
Got the minimal reproducer working. From `main`, just disable the `c-kzg` feature of `reth-revm`:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index afd8eb784..9df0d312e 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -375,7 +375,7 @@ reth-primitives-traits = { path = "crates/primitives-traits", default-features =
 reth-provider = { path = "crates/storage/provider" }
 reth-prune = { path = "crates/prune/prune" }
 reth-prune-types = { path = "crates/prune/types" }
-reth-revm = { path = "crates/revm" }
+reth-revm = { path = "crates/revm", default-features = false, features = ["std"] }
 reth-rpc = { path = "crates/rpc/rpc" }
 reth-rpc-api = { path = "crates/rpc/rpc-api" }
 reth-rpc-api-testing-util = { path = "crates/rpc/rpc-testing-util" }
```

This technically shouldn't have any impact on correctness - `kzg-rs` should be a drop-in replacement for `c-kzg`. Apparently this is not the case. I think this exposes some kind of bug either on `kzg-rs` itself, or in its use in `reth` or `revm`.

**Comment by xJonathanLEI** [comment]
Actually... no. Sorry I'm not quite familiar with the codebase so I was under the wrong impression that as long as you disable `c-kzg` it uses `kzg-rs` in-place.

What really happens is that the whole KZG precompile is disabled. So it's not surprising at all that state tests are failing.

**Comment by xJonathanLEI** [comment]
Rebased. CI is green now. Turned on the features on the `ef-tests` crate to make the state tests pass.

**Review by fgimenez — APPROVED** [review]
awesome, thx @xJonathanLEI ! we need the changes here for other PRs, so I've rebased on top of main and moved the `c-kzg` features from the `reth-revm` deps to `revm`, so that required `revm` features are grouped . All looking fine locally.

pending @mattsse

**Review by mattsse — APPROVED** [review]

**Pull request merged**
