### PR TITLE
Payload builder test utils

### PR DESCRIPTION
**Pull request by supernovahs**
Ref #4375 

Cyclic dependency 
https://github.com/supernovahs/reth/blob/9450db34f61e000b1844dc2a3b1f1d990a61cb32/crates/payload/builder/Cargo.toml#L20

https://github.com/supernovahs/reth/blob/9450db34f61e000b1844dc2a3b1f1d990a61cb32/crates/consensus/beacon/Cargo.toml#L20

### CODE REVIEW

**Comment by supernovahs** [comment]
How should I go about with this ? Since I cannot shift utils to builder .
thanks

**Comment by supernovahs** [comment]
As discussed with @mattsse ,  a new crate for testing. 
To do : 
1) Appropriate name for crate
2) Tests?

**Review by Rjected — CHANGES_REQUESTED** [review]
Just taking a look at this, this looks alright - I would change the crate name, maybe to `reth-builder-test-utils`, or `reth-payload-builder-test-utils`, and include it in the `payload` subdirectory. The `rpc-testing-util` crate is a good example

**Comment by mattsse** [comment]
agree.

this is currently blocked by #4377 
will get this over the line once merged

**Comment by supernovahs** [comment]
Made the changes.

**Comment by mattsse** [comment]
thanks, checking asap

**Review by mattsse — COMMENTED** [review]
I can see this as a starting point for a more sophisticated testing crate.

rn this doesn't do much yet so I don't think we should include it just yet.
I think ideally with more testing support in this new crate that is some kind of TestNode which we can use for testing rpc

**Comment by gakonst** [comment]
Plans for this? If not planning on getting in soon, we can close and re-consider later

**Comment by mattsse** [comment]
I've thought about this again, and with the upcoming builder solution #6447 
this will be much easier and we can write test tooling on top of that

**Pull request closed without merging**
