### PR TITLE
fix: poll logic when pipeline active

### LINKED ISSUE #3754: Continous timeout error between CL<>EL communication
### Describe the bug

Connection times out on CL when trying to reach EL. 

### Steps to reproduce

1. Run Reth
2. Run Lighthouse

### Node logs

```text
RETH logs:
2023-07-13T10:37:49.281359Z  WARN connection{remote_addr=127.0.0.1:52728 conn_id=199}: jsonrpsee_server::server: HTTP serve connection failed hyper::Error(IncompleteMessage)

Lighthouse:
Jul 13 10:42:12.776 WARN Execution engine call failed            error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out), service: exec
Jul 13 10:42:12.776 WARN Error whilst processing payload status  error: Api { error: HttpClient(url: http://localhost:8551/, kind: timeout, detail: operation timed out) }, service: exec
```

### Platform(s)

_No response_

### What version/commit are you on?

commit 99240906a844ae7a8b6b6032fc3b0f64dce22f25 (HEAD -> main, origin/main, origin/HEAD)

### What database version are you on?

Current database version: 1
Local database version: 1

### If you've built Reth from source, provide the full command you used

cargo install --locked --path bin/reth --bin reth

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by mattsse**
Closes #3754

the prune changes broke the poll logic when the pipeline is active

https://github.com/paradigmxyz/reth/pull/3566

in which case we were returning pending even if there still is work to do (available engine messages for example)

### CODE REVIEW

**Review by shekhirin — APPROVED** [review]
LGTM

**Review by gakonst — COMMENTED** [review]
Would tokio console or something help us detect this somehow if we were running it live and observed the insights from it?

**Comment by mattsse** [comment]
need to familiarize myself with tokio console features first, if it's possible to monitor certain tasks and their state

**Comment by gakonst** [comment]
cc @jonasbostoen as i saw you using tokio-console before, in case any input

**Review by rkrasiuk — APPROVED** [review]
good find!

**Pull request merged**
