### PR TITLE
transaction-pool: replace reth-primitive imports

### PR DESCRIPTION
**Pull request by estensen**
Progress on https://github.com/paradigmxyz/reth/issues/10749

Changed all where direct drop-in-replacement was possible

### CODE REVIEW

**Review by mattsse — APPROVED** [review]

**Comment by estensen** [comment]
@mattsse find an replace in VSCode doesn't trigger format on save. Any idea how to enable that?

**Comment by mattsse** [comment]
I run this mostly manually and have an alias for nfmt=cargo +nightly fmt
so before I commit I run nfmt --all, it's muscle memory at this point

**Comment by estensen** [comment]
Have you considered adding a pre-commit hook to avoid this from happening?

**Comment by mattsse** [comment]
we have not, not a big fan of pre commit hooks
missed fmt is also not a big deal

**Pull request merged**
