### PR TITLE
chore: reexport bytes & bump version to 1.4

### PR DESCRIPTION
**Pull request by rkrasiuk**
This PR reexports `bytes` crate from `reth-primitives` crate and minimizes the number of instances of direct dependencies on `bytes` crate.

**Why `bytes` crate version was upgraded to `1.4`?**

- Improved performance of `BytesMut::freeze` (https://github.com/tokio-rs/bytes/pull/592)
- Requirement for latest revm (https://github.com/bluealloy/revm/commit/578834056dd00a5fd90b4200309198dd01727cbe)

**Why is `bytes` reexport needed?**

- To minimize the number of changes needed for the next upgrade.

**Why `bytes` dependency remained in some crates?**

- Some crates do not have dependency on `reth-primitives` (`rpc/ipc`, `rlp`)
- Some crates use `main_codec` (including `reth-primitives`) which generates the code with `bytes::Buf` import
https://github.com/paradigmxyz/reth/blob/94674f9c1676d947565ea2f5d1b9a3bf22beac99/crates/storage/codecs/derive/src/compact/flags.rs#L50-L53
I've attempted generating a dynamic import path with [proc-macro-crate](https://docs.rs/proc-macro-crate/latest/proc_macro_crate/), but it failed to cover all usages

---
NOTE: Possible merge conflicts with #1393

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
can't remember if it was 1.3 or 1.4 that caused regression of the benchmarking job, IIRC it was 1.3 and we rolled back the cargo.lock bump.

let's see

**Comment by rakita** [comment]
I don't have any attachments to v1.4, I am fine to temporarily downgrade to v1.2 if there is a problem

**Comment by rkrasiuk** [comment]
@rakita tried pinning revm to `v1.2.1`, but the produced downstream dep error with ethers 😬

**Review by gakonst — APPROVED** [review]
Supportive, let's actually open an issue on Bytes upstream so that it's tracked.

**Pull request merged**
