### PR TITLE
test: use concrete type for arbitrary strategy

### PR DESCRIPTION
**Pull request by mattsse**
get rid of boxed strategy

h/t @DaniPopes

### CODE REVIEW

**Comment by DaniPopes** [comment]
@mattsse the strategy is `Vec<u8>`'s mapped to `Self`

```diff
diff --git a/crates/storage/db/src/tables/utils.rs b/crates/storage/db/src/tables/utils.rs
index 93705555..7a5e9d5d 100644
--- a/crates/storage/db/src/tables/utils.rs
+++ b/crates/storage/db/src/tables/utils.rs
@@ -1,16 +1,15 @@
-//! Small database table utilities and helper functions
+//! Small database table utilities and helper functions.
+
 use crate::{
     table::{Decode, Decompress, Table},
     DatabaseError,
 };
-
 use std::borrow::Cow;
 
+/// Implements the `Arbitrary` trait for types with fixed array types.
 #[macro_export]
-/// Implements the `Arbitrary` trait for types with fixed array
-/// types.
 macro_rules! impl_fixed_arbitrary {
-    ($name:tt, $size:tt) => {
+    ($name:ident, $size:tt) => {
         #[cfg(any(test, feature = "arbitrary"))]
         use arbitrary::{Arbitrary, Unstructured};
 
@@ -19,22 +18,20 @@ macro_rules! impl_fixed_arbitrary {
             fn arbitrary(u: &mut Unstructured<'a>) -> Result<Self, arbitrary::Error> {
                 let mut buffer = vec![0; $size];
                 u.fill_buffer(buffer.as_mut_slice())?;
-
                 Decode::decode(buffer).map_err(|_| arbitrary::Error::IncorrectFormat)
             }
         }
 
-        #[cfg(any(test, feature = "arbitrary"))]
-        use proptest::strategy::Strategy;
         #[cfg(any(test, feature = "arbitrary"))]
         impl proptest::prelude::Arbitrary for $name {
             type Parameters = ();
             type Strategy = proptest::strategy::Map<
-                proptest::collection::VecStrategy<$name>,
-                fn(<S as Strategy>::Value) -> T,
+                proptest::collection::VecStrategy<<u8 as proptest::arbitrary::Arbitrary>::Strategy>,
+                fn(Vec<u8>) -> Self,
             >;
 
             fn arbitrary_with(args: Self::Parameters) -> Self::Strategy {
+                use proptest::strategy::Strategy;
                 proptest::collection::vec(proptest::arbitrary::any_with::<u8>(args), $size)
                     .prop_map(move |vec| Decode::decode(vec).unwrap())
             }
```

**Comment by mattsse** [comment]
sorry but idk what this means, can't follow.

not sure how to interpret the diff

**Comment by DaniPopes** [comment]
It means I fixed it for you :)

**Comment by mattsse** [comment]
hehe,

tysm for this champ!

**Review by joshieDo — APPROVED** [review]

**Pull request merged**
