### PR TITLE
refactor(stages): `previous_stage` -> `target` in `ExecInput`

### PR DESCRIPTION
**Pull request by shekhirin**
Three main changes:
1. We didn't use the `StageId` part of `ExecInput.previous_stage` field, so I removed it.
2. `ExecInput.previous_stage` sounds confusing, because essentially it works the same as `UnwindInput.unwind_to` – the target block number we're trying to reach. So I renamed it to `ExecInput.target`.
3. `ExecInput.previous_stage` didn't respect the `Pipeline.max_block` even if it was known. Now, we pass it from the pipeline.

### CODE REVIEW

**Review by rkrasiuk — COMMENTED** [review]
supportive of this change

**Review by mattsse — APPROVED** [review]
makes sense to me!

pending @rkrasiuk

**Review by onbjerg — APPROVED** [review]
makes sense to me as well.

**Review by rkrasiuk — APPROVED** [review]
lgtm, let's go!

**Pull request merged**
