### PR TITLE
feat(storage): custom tables

### PR DESCRIPTION
**Pull request by Vid201**
Addresses #4546 

This is a first draft how to support custom tables. Any feedback highly appreciated (or if this approach is not good and some other is preffered)

Example in the action: 
- https://github.com/silius-rs/silius/blob/chore/reth_db/crates/mempool/src/database/tables.rs
- https://github.com/silius-rs/silius/blob/chore/reth_db/bin/silius/src/bundler.rs#L252

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
hmm, what's your use case for this? adding new tables to the existing DB?

we don't really want to open this up becomes then it becomes harder to transition to a new db in the future

**Comment by Vid201** [comment]
> hmm, what's your use case for this? adding new tables to the existing DB?
> 
> we don't really want to open this up becomes then it becomes harder to transition to a new db in the future

The use case is to use crate `reth_db` for database in our project. But we are not using the same tables as `reth` node, but we have some custom tables (https://github.com/silius-rs/silius/blob/chore/reth_db/crates/mempool/src/database/tables.rs)

If this is not the intended use of `reth_db`, no problem, we'll use something else

**Comment by mattsse** [comment]
reopening this, because this is still something we want to support and this is likely useful

**Review by mattsse — COMMENTED** [review]
I'm closing this now that we have a path forward here

ref #13130

**Comment by Vid201** [comment]
> I'm closing this now that we have a path forward here
> 
> ref #13130

Awesome! I'll take a look at new approach

**Comment by mattsse** [comment]
not quite there yet, but almost

**Pull request closed without merging**
