### PR TITLE
docs: add holesky to list of chains in cli docs

### PR DESCRIPTION
**Pull request by jgresham**

### CODE REVIEW

**Review by Rjected — COMMENTED** [review]
hey! looks good, but the other pages in `book/cli` also need holesky to be added - mind adding this there too?

**Comment by jgresham** [comment]
> hey! looks good, but the other pages in `book/cli` also need holesky to be added - mind adding this there too?

adding now!

**Review by Rjected — APPROVED** [review]
LGTM! thank you!

**Comment by jgresham** [comment]
ok @Rjected, no extra commit lines from whitespace now

**Comment by Rjected** [comment]
> ok @Rjected, no extra commit lines from whitespace now

cool, thanks!

**Review by mattsse — APPROVED** [review]
unfortunate that there's no easy way with clap via possible_values to automate this, that I know of

**Pull request merged**
