### PR TITLE
Decode with EMPTY_STRING_CODE and buf.advance()

### PR DESCRIPTION
**Pull request by jtraglia**
This PR fixes a minor nit I had when reviewing some `decode` functions. It replaces `0x80` with `EMPTY_STRING_CODE` and uses `buf.advance()` instead of the other way, which I didn't find very readable. Also fix a few typos.

### CODE REVIEW

**Review by Rjected — APPROVED** [review]
LGTM! `buf.advance` and `EMPTY_STRING_CODE` are definitely preferred

**Comment by Rjected** [comment]
just needs import fix I think for the trait

**Comment by jtraglia** [comment]
> just needs import fix I think for the trait

Oops. I'll fix this. One minute.

**Review by mattsse — APPROVED** [review]
lgtm, ty

**Pull request merged**
