### PR TITLE
feat(exex): derive serde ser/deser for `ExExNotification`

### PR DESCRIPTION
**Pull request by shekhirin**
Derives `serde::{Serialize, Deserialize}` for the `ExExNotification` and all downstream types.

### CODE REVIEW

**Review by mattsse — CHANGES_REQUESTED** [review]
imo adding support for serialize makes sense given the direction we want to take this.

can we rename everything to camelCase ?

**Comment by DaniPopes** [comment]
No, this is rust :+1:

**Comment by mattsse** [comment]
i meant via serde :)

**Comment by DaniPopes** [comment]
Yes, I mean that too

**Comment by shekhirin** [comment]
> imo adding support for serialize makes sense given the direction we want to take this.
> 
> can we rename everything to camelCase ?

I don't think we should do it for two reasons:
1. We have a separate layer of RPC compatibility where we do `camelCase`
2. We already had a lot of ser/deser implementations for primitive types, and didn't use `camelCase` there

**Review by mattsse — APPROVED** [review]

**Pull request merged**
