### PR TITLE
fix(execution): Increase cache scope, and apply block reward to cache

### PR DESCRIPTION
**Pull request by rakita**
There are two bugs here. Block reward was not applied to cached db as cached db was temporary, and the scope of cached db should have been over all blocks that are executed.

Did some pending cleanup on the transition id in unwind.

updated revm.

### CODE REVIEW

**Review by gakonst — CHANGES_REQUESTED** [review]
Nice - thx for fixing this. Could we add a couple extra tests for these cases as it was not caught before?

**Comment by rakita** [comment]
> Nice - thx for fixing this. Could we add a couple extra tests for these cases as it was not caught before?

Added asserts that would check if the cache is properly set.

**Review by rkrasiuk — APPROVED** [review]
lgtm

**Review by rkrasiuk — APPROVED** [review]
lgtm

**Pull request merged**
