### PR TITLE
feat: add block difficulty calculator 

### PR DESCRIPTION
**Pull request by mvares**
Towards #9476

### CODE REVIEW

**Comment by mvares** [comment]
hey @mattsse, I'm waiting for your review. In addition, I know that some things can better 👍🏻

**Comment by mvares** [comment]
@mattsse can you check out this?

**Comment by emhane** [comment]
pending @mattsse

**Review by mattsse — CHANGES_REQUESTED** [review]
not very familiar with the difficulty stuff, so would like to see some testvectors

**Pull request closed without merging**
