### PR TITLE
chore: export tables macro

### PR DESCRIPTION
**Pull request by Vid201**

### CODE REVIEW

**Comment by onbjerg** [comment]
Can you share some motivation here?

**Review by mattsse — APPROVED** [review]
this makes it easier to define custom tables, I can see this being useful if you want to roll your own db instance, in exex for example

**Review by rkrasiuk — APPROVED** [review]
supportive. note: it would require additional legwork to make custom tables work

**Comment by Vid201** [comment]
> this makes it easier to define custom tables, I can see this being useful if you want to roll your own db instance, in exex for example

this is exactly the use case, we are using custom tables in Silius (it worked on some old commits from one year ago, trying to update deps now). explained here: https://github.com/paradigmxyz/reth/issues/4546

but yeah, some additional legwork is needed next to that

**Pull request merged**
