### PR TITLE
chore(github): run update-book-cli in the lint workflow

### LINKED ISSUE #8333: Update book reference on cli updates automatically
### Describe the feature

This was an idea from @jsvisa in https://github.com/paradigmxyz/reth/pull/8242:
> BTW, should we add make update-book-cli in the github workflows, so anyone updated the cli, the book will be updated simultaneously

It would be great to have this happen automatically, so the book never becomes stale! I can see two decent ways of doing this:
* Similar to the fmt workflow, i.e., `update-book-cli` is run on every PR, and if there is a diff between the current book files and the output of `update-book-cli`, the workflow fails.
* As a nightly auto-opened PR (only if there are non-empty changes to the book) or similar regular workflow, similar to dependency workflows

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jsvisa**
implement and close #8333

### CODE REVIEW

**Comment by DaniPopes** [comment]
This doesn't do anything right now, it should commit and push to the current PR?

**Comment by Rjected** [comment]
> This doesn't do anything right now, it should commit and push to the current PR?

yeah, or check that there is no diff like the `fmt --check` workflow

**Comment by DaniPopes** [comment]
Ok lets do that, git diff with some flags should do it

**Comment by jsvisa** [comment]
Now it's working, after running the `make update-book-cli`, if the git workspace has any diff, the `git diff` will print the diff into the screen, eg: 

https://github.com/paradigmxyz/reth/actions/runs/9207887154/job/25328904977?pr=8335

```
Run git diff --exit-code
diff --git a/book/cli/reth/db/checksum.md b/book/cli/reth/db/checksum.md
index a8147b0..66f0a86 100644
--- a/book/cli/reth/db/checksum.md
+++ b/book/cli/reth/db/checksum.md
@@ -22,6 +22,[9](https://github.com/paradigmxyz/reth/actions/runs/9207887154/job/25328904977?pr=8335#step:6:10) @@ Options:
 
           [default: default]
 
+      --start-key <START_KEY>
+          The start of the range to checksum
+
       --chain <CHAIN_OR_PATH>
           The chain this node is running.
           Possible values are either a built-in chain or the path to a chain specification file.
@@ -31,6 +34,[12](https://github.com/paradigmxyz/reth/actions/runs/9207887154/job/25328904977?pr=8335#step:6:13) @@ Options:
```

**Comment by jsvisa** [comment]
@DaniPopes @Rjected This PR is ready, please take a look, thanks.

**Review by Rjected — APPROVED** [review]
lgtm

**Review by DaniPopes — APPROVED** [review]
Thanks!

**Pull request merged**
