### PR TITLE
add `option_if_let_else` clippy lint

### PR DESCRIPTION
**Pull request by tcoratger**

### CODE REVIEW

**Comment by DaniPopes** [comment]
Personally I prefer `map().unwrap_or()` as it's more readable

**Comment by tcoratger** [comment]
> Personally I prefer `map().unwrap_or()` as it's more readable

Let me know if there is somewhere to modify it was automatic clippy suggestion :)

**Review by mattsse — COMMENTED** [review]
I personally dislike map_or because it looks weird to me and also prefer if let some else or unwrap_or because it's more readable

**Comment by tcoratger** [comment]
> I personally dislike map_or because it looks weird to me and also prefer if let some else or unwrap_or because it's more readable 

Then let us close this and remove this lint from our list in cargo.toml as we don't want it no?

**Comment by tcoratger** [comment]
> I personally dislike map_or because it looks weird to me and also prefer if let some else or unwrap_or because it's more readable

@mattsse Related https://github.com/paradigmxyz/reth/pull/8539

**Comment by tcoratger** [comment]
@mattsse After https://github.com/paradigmxyz/reth/pull/8539 we can close this imo

**Pull request closed without merging**
