### PR TITLE
feat: calc block base reward use block number only

### PR DESCRIPTION
**Pull request by jsvisa**
ref https://github.com/paradigmxyz/reth/pull/8868#discussion_r1641918765

### CODE REVIEW

**Review by onbjerg — DISMISSED** [review]
i don't think the idea was removing the ttd check entirely, just avoiding fetching ttd where possible by checking with the block number first, e.g. if paris is not activated at a specific block number, we'd need to fetch the ttd and check again because it might be a false negative (in the case where we don't know the number of the merge block)

cc @mattsse for clarification

**Comment by jsvisa** [comment]
@onbjerg I have the same thoughts as you, but after some consideration, if the chain has passed merge, it must be set `paris_block_and_final_difficulty`, so I think there's no need to check the ttd again.

**Comment by onbjerg** [comment]
The block is only set if its present in the chain spec, which is not the case for all chains, e.g. if the block is not known, but the TTD is.

**Review by mattsse — CHANGES_REQUESTED** [review]
we can't safely do that, but what we can do this, add a new function that checks the base block reward pre-merge based on the block number

**Comment by jsvisa** [comment]
@mattsse ptal, seems the `is_paris_active_at_block` is missed in #8891, so add back in this pr; and add a simple func `base_block_reward_pre_merge` returns 2,3,5 ETH for blocks before merge. I'll check if the block is after merge or not in https://github.com/paradigmxyz/reth/pull/8868 before invoking `base_block_reward`, so no need to adjust more in this pr, wdyt.

**Comment by mattsse** [comment]
-.- adding back in #8896

**Comment by mattsse** [comment]
nvm, I'll include it here, ty

**Review by mattsse — APPROVED** [review]
lgtm

**Pull request merged**
