### PR TITLE
fix(op): bootnodes

### PR DESCRIPTION
**Pull request by emhane**
OP EL and Base EL both use the same boot nodes

### CODE REVIEW

**Comment by joshieDo** [comment]
Can we instead merge them on:
https://github.com/paradigmxyz/reth/blob/0f9658cfa17cc9dd97ccf8ee3b7ff855757c4b59/crates/primitives/src/chain/spec.rs#L984-L991

With a smol comment

**Comment by emhane** [comment]
> Can we instead merge them on:
> 
> https://github.com/paradigmxyz/reth/blob/0f9658cfa17cc9dd97ccf8ee3b7ff855757c4b59/crates/primitives/src/chain/spec.rs#L984-L991
> 
> With a smol comment

the separation is only based on which org hosts though, it's not a programmatic one. how come you want the separation?

**Comment by joshieDo** [comment]
it's just a preference, i'll let others chime in

**Review by Rjected — CHANGES_REQUESTED** [review]
we should combine the two, see how this has 8 entries
https://github.com/ethereum-optimism/op-geth/blob/84b52dfd2626f5e19da6baa2691d81f4c2299eb5/params/bootnodes.go#L90-L100

`BASE_BOOTNODES` is only 5, so we should extend base bootnodes with op bootnodes

**Review by Rjected — APPROVED** [review]
lgtm!

**Pull request merged**
