### PR TITLE
feat: move calculate_intrinsic_gas_after_merge to tx pool

### LINKED ISSUE #8899: move calculate_intrinsic_gas_after_merge to txpool eth validator
### Describe the feature

this is only used in the eth validator:

https://github.com/paradigmxyz/reth/blob/main/crates/primitives/src/revm/compat.rs#L31-L43

and should be moved there, this means the txpool would need the revm-interpreter dep

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kamuik16**
Closes #8899

### CODE REVIEW

**Comment by kamuik16** [comment]
right now, after these changes getting a warning that revm is an unused crate in reth-primitive but can not remove it because certain features use revm as dep. what to do?

**Comment by kamuik16** [comment]
revm is not used in reth-primitives now, so giving a warning of unused crates but some features use it as a dep and removing revm from features seems to break some things. used allow for now to pass ci.

**Comment by DaniPopes** [comment]
What's breaking ? Ideally we want to remove revm from here, is it maybe usage in tests?

**Comment by kamuik16** [comment]
> What's breaking ? Ideally we want to remove revm from here, is it maybe usage in tests?

I tried to it in https://github.com/paradigmxyz/reth/pull/8914/commits/82b569d94f8775bbd92212db6997b6061e0fdc7e. checkout its ci failures.

**Comment by DaniPopes** [comment]
Oh, I think you just need to propagate the optimism feature to revm-primitives instead of revm in reth-primitives Cargo.toml

**Comment by kamuik16** [comment]
> Oh, I think you just need to propagate the optimism feature to revm-primitives instead of revm
> 
> https://github.com/paradigmxyz/reth/blob/c008a1fa0990089e96c7f7661587ac080fbea4c5/crates/primitives/Cargo.toml#L112-L117

Got a different error now.

**Comment by onbjerg** [comment]
> revm is not used in [reth-primitives](https://linear.app/paradigm-oss/issue/ID--primitives) now, so giving a warning of unused crates but some features use it as a dep and removing revm from features seems to break some things. used allow for now to pass ci.

mark it as optional, and then use `dep:revm` in the features that use it

**Comment by kamuik16** [comment]
> > revm is not used in [reth-primitives](https://linear.app/paradigm-oss/issue/ID--primitives) now, so giving a warning of unused crates but some features use it as a dep and removing revm from features seems to break some things. used allow for now to pass ci.
> 
> mark it as optional, and then use `dep:revm` in the features that use it

still giving me a warning that revm is an unused crate, i tried this earlier too.

**Review by DaniPopes — APPROVED** [review]

**Review by mattsse — APPROVED** [review]

**Pull request merged**
