### PR TITLE
docs: memory profiling and OOM debugging tutorial

### PR DESCRIPTION
**Pull request by Rjected**
This distills some of my previous attempts at fixing memory leaks in reth, so that memory leak debugging can be more accessible.

I aim to give an overview on the process one should go through when faced with a memory related bug or incident, as well as provide some useful intuition for rust and reth-specific debugging. This will be a more advanced tutorial, and will assume some knowledge about linux, memory, and how to set up reth, but should otherwise be a general document that anyone can learn from.

### CODE REVIEW

**Comment by mattsse** [comment]
what to do with this @Rjected ?

**Comment by mattsse** [comment]
bump @Rjected

**Comment by Rjected** [comment]
> bump @Rjected

going to take a small chunk of time soon to finish this up and mark r4r

**Comment by rkrasiuk** [comment]
@Rjected bump :)

**Comment by gakonst** [comment]
This still relevant @Rjected? If so let's merge or clsoe

**Comment by Rjected** [comment]
> This still relevant @Rjected? If so let's merge or clsoe

Should be useful, finished it up, let's merge

**Review by mattsse — APPROVED** [review]

**Pull request merged**
