### PR TITLE
chore: remove unused deps

### PR DESCRIPTION
**Pull request by hai-rise**
A random `cargo machete` run. I keep the formatting changes in since they are pretty straightforward. Can remove if need be.

### CODE REVIEW

**Review by onbjerg — APPROVED** [review]
big if true, and will merge if so

**Review by DaniPopes — APPROVED** [review]

**Review by mattsse — APPROVED** [review]
big

**Review by onbjerg — CHANGES_REQUESTED** [review]
looks like there was a false positive

**Review by onbjerg — APPROVED** [review]

**Comment by hai-rise** [comment]
`machete` got these wrong:
- `[build-dependencies]`
- `test --doc`
- `modular-bitfield`
- `test-fuzz`
- `proptest` & `proptest-arbitrary-interop`
- Few edge cases around features & optional dependencies

~~They clearly need to upgrade to a larger LLM 😅.~~

**Pull request merged**
