### PR TITLE
chore(revm): separate post state crate

### PR DESCRIPTION
**Pull request by rkrasiuk**
Move post state to a separate crate under `revm/`

### CODE REVIEW

**Comment by onbjerg** [comment]
PostState is supposed to be generic, moving it to the revm crate doesnt make sense to me

**Comment by rkrasiuk** [comment]
@onbjerg posting response here for clarity as well. `PostState` is for aggregating execution results. currently, we are fine moving it under revm until we decide on the direction we take with generic executors

**Comment by gakonst** [comment]
I think let's let Bjerg own the PostState-related refactors as it interacts with his work? Or is this something that's blocking you Roman?

**Review by mattsse — COMMENTED** [review]
defining `PostState` inside the `provider` leads to a circular dependencies in some cases, for example:

* crate A adds an implementation of `reth_interfaces::TraitA`
* crate adds test impls for `TraitA` that depend on `PostState`
* now `reth_providers` can't import `crate A`

I'm a bit conflicted where to put this, it doesn't really fit into `revm-primitives` and also skeptical of putting it under `reth_revm`. I'm also not sure if it's worth it to have another crate just for this file.

I'd propose either `reth_poststate` or put it into `reth-blockchain-tree`
but tbh, perhaps not worth doing this at all

**Comment by rkrasiuk** [comment]
alright, i made a workaround for my circular dependency. closing for now

**Pull request closed without merging**
