### PR TITLE
fix: enable missing feature

### PR DESCRIPTION
**Pull request by mattsse**

### CODE REVIEW

**Comment by gakonst** [comment]
Where was this discovered as a problem?

**Comment by mattsse** [comment]
feature gated import was used and did not compile

**Comment by gakonst** [comment]
Just to keep the info around, what was the CI run where things failed?

**Comment by mattsse** [comment]
introduced here https://github.com/paradigmxyz/reth/pull/617

it did not fail in CI because we don't test crates individually and features are additive, so it is enabled for the CI build but fails if you compile primitives standalone

**Comment by gakonst** [comment]
> it did not fail in CI because we don't test crates individually and features are additive, so it is enabled for the CI build but fails if you compile primitives standalone

ah! word. makes total sense.

**Pull request merged**
