### PR TITLE
add `use_self` clippy lint

### PR DESCRIPTION
**Pull request by tcoratger**
- `use_self` clippy lint checks for unnecessary repetition of structure name when a replacement with `Self` is applicable.
- Why is this bad?
     - Unnecessary repetition. Mixed use of `Self` and struct name feels inconsistent.

### CODE REVIEW

**Review by Rjected — CHANGES_REQUESTED** [review]
please remove all semicolons, these should not be allowed with our policy to use `cargo +nightly fmt`. `make pr` may get rid of them, mind trying that?

**Comment by tcoratger** [comment]
> please remove all semicolons, these should not be allowed with our policy to use `cargo +nightly fmt`. `make pr` may get rid of them, mind trying that?

done

**Review by mattsse — APPROVED** [review]
lgtm,

this could perhaps result in a few conflicts, but those can be easily resolved

I'm keeping this open, because we're about to merge a bunch of stuff from devnet-0
once stabilized, we can easily rebase this pr

**Comment by tcoratger** [comment]
> lgtm,
> 
> this could perhaps result in a few conflicts, but those can be easily resolved
> 
> I'm keeping this open, because we're about to merge a bunch of stuff from devnet-0 once stabilized, we can easily rebase this pr

Yes, please let me know when you are able to merge so that I fix conflicts and we directly merge to avoid further conflicts :)

**Review by emhane — APPROVED** [review]

**Review by onbjerg — APPROVED** [review]

**Review by Rjected — APPROVED** [review]

**Review by DaniPopes — APPROVED** [review]

**Comment by mattsse** [comment]
@tcoratger as promised a ton of conflicts hehe

maybe it's easier to start over, does cargo --fix apply these automatically?

**Comment by tcoratger** [comment]
> @tcoratger as promised a ton of conflicts hehe
> 
> maybe it's easier to start over, does cargo --fix apply these automatically?

No problem, done :)

**Review by mattsse — APPROVED** [review]

**Pull request merged**
