### PR TITLE
grafana: add build version,gitsha,timestamp into dashboard

### PR DESCRIPTION
**Pull request by jsvisa**
implement https://github.com/paradigmxyz/reth/issues/6335

and it looks like below:

image

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
I like this, perhaps we can make the box a bit smaller?

wdyt @shekhirin @Rjected

**Comment by rkrasiuk** [comment]
@jsvisa supportive, pls make font size smaller and post resulting screenshot

**Comment by jsvisa** [comment]
@rkrasiuk thanks for the advice, reduce the text size from `auto` to 20. please take another look.


> full screen

image


> half screen


image

**Review by Rjected — APPROVED** [review]
The new font size looks good, lgtm pending @shekhirin

**Review by shekhirin — APPROVED** [review]

**Review by mattsse — APPROVED** [review]
nice

**Pull request merged**
