### PR TITLE
fix the issue of network is not known to be merged

### LINKED ISSUE #6453: Use `terminalTotalDifficultyPassed` to determine "network is known to be merged"
### Describe the feature

Right now we determine the "network is not known to be merged" based on the `TTD { fork_block, .. }` field:
https://github.com/paradigmxyz/reth/blob/37a8780a4d71856fddc09a9146823d00a2ed0201/crates/primitives/src/chain/spec.rs#L1478-L1482

This is incorrect because this is not enabled for mainnet:
https://github.com/paradigmxyz/reth/blob/37a8780a4d71856fddc09a9146823d00a2ed0201/crates/primitives/src/chain/spec.rs#L1346-L1351

This causes reth to incorrectly show "network is not known to be merged".

Instead we should use the `terminal_total_difficulty_passed` parameter if parsing from `genesis.json`, and introduce a parameter in `ChainSpec` for this. Then we can use that field to determine this messsage.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jsvisa**
close https://github.com/paradigmxyz/reth/issues/6453

### CODE REVIEW

**Comment by jsvisa** [comment]
@Rjected PTAL

**Review by mattsse — COMMENTED** [review]
hmm, perhaps this is the easiest solution.

but we only need this for displaying, and adding an additional field just for that seems a bit odd, especially if we already have something like this on the Chainspec struct:

https://github.com/paradigmxyz/reth/blob/6204ec7298212ffc7c2b3b2418bce39fa6a73e6a/crates/primitives/src/chain/spec.rs#L606-L608

perhaps we use that in `DisplayHardforks` instead for the None case?
wdyt @Rjected

**Review by Rjected — CHANGES_REQUESTED** [review]
yeah, as I mentioned in the issue, we should be using `paris_block_and_total_difficulty`

**Comment by jsvisa** [comment]
> yeah, as I mentioned in the issue, we should be using `paris_block_and_total_difficulty`

@Rjected Sorry, I missed the previous comments. I would like to confirm if I truly understand what you mean, is that correct? We can pass `paris_block_and_total_difficulty` to `DisplayHardforks::new`, something like below:

```rust
impl DisplayHardforks {
    /// Creates a new [`DisplayHardforks`] from an iterator of hardforks.
    pub fn new(hardforks: &BTreeMap<Hardfork, ForkCondition>, ttd: U256) -> Self {
        Self::from_iter(hardforks.iter().map(|(fork, condition)| (fork, condition, ttd)))
    }
}

impl<'a, 'b> FromIterator<(&'a Hardfork, &'b ForkCondition)> for DisplayHardforks {
    fn from_iter<T: IntoIterator<Item = (&'a Hardfork, &'b ForkCondition, U256)>>(iter: T) -> Self {
        let mut pre_merge = Vec::new();
        let mut with_merge = Vec::new();
        let mut post_merge = Vec::new();

        for (fork, condition, ttd) in iter {
            let display_fork =
                DisplayFork { name: fork.to_string(), activated_at: *condition, eip: None, ttd };

            match condition {
                ForkCondition::Block(_) => {
                    pre_merge.push(display_fork);
                }
                ForkCondition::TTD { .. } => {
                    with_merge.push(display_fork);
                }
                ForkCondition::Timestamp(_) => {
                    post_merge.push(display_fork);
                }
                ForkCondition::Never => continue,
            }
        }

        Self { pre_merge, with_merge, post_merge }
    }
}
```

**Comment by mattsse** [comment]
yeah, we can remove the from iter impl, and add `known_paris_block: Option<u64>` to that

and we can add `displayforks(&self)` function to the chainspec type

**Comment by jsvisa** [comment]
@mattsse thanks for the advice, adjusted, and PTAL

**Review by mattsse — APPROVED** [review]
lgtm

pending @Rjected + lint fixes

**Review by Rjected — APPROVED** [review]
this looks good to me, thanks!

**Pull request merged**
