### PR TITLE
Change `SegmentHeader` to deal with fields instead of ranges

### LINKED ISSUE #6185: Change `SegmentHeader` to deal with fields instead of ranges
Change `SegmentHeader` to deal with `X_start` and `X_end`  instead of ranges

ref  https://github.com/paradigmxyz/reth/pull/5733#discussion_r1455908651_

### PR DESCRIPTION
**Pull request by tcoratger**
Should close #6185.

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
I don't have enough context here

ptal @shekhirin

**Comment by joshieDo** [comment]
definitely still relevant, should pick this up and point it to `feat/static-files` soon

**Comment by joshieDo** [comment]
there are some changes that I need to to do, so I'll be taking this forward. Thanks for the initial work @tcoratger !

**Comment by tcoratger** [comment]
> there are some changes that I need to to do, so I'll be taking this forward. Thanks for the initial work @tcoratger !
> 
> edit: continued here #6446

Sure np

**Pull request closed without merging**
