### PR TITLE
feat(sync): add storage hashing state

### PR DESCRIPTION
**Pull request by lambdaclass-user**
Linked: https://github.com/paradigmxyz/reth/issues/634

This PR adds the `StorageHashingStage` stage.

### CODE REVIEW

**Comment by gakonst** [comment]
Is it right that we want to re-hash the entire state for every historical block? That is the main thing that felt weird on reading this PR. makes sense that we need to hash it before the merklization, just unclear to me if this happens on every block.

**Comment by MegaRedHand** [comment]
As you said, re-hashing the state for every block would be expensive, so we only update entries in `StorageChangeSet`, unless there are more than a _configurable_ threshold amount of transitions in the block range or we are just starting the sync.

**Comment by gakonst** [comment]
Hey folks - had a chance to sync with @rakita re: this. We love the tests you wrote and would like to integrate them as they are. For the logic, there's some parts we may use but we'd rather go with Dragan's implementation/approach which we had aligned on..hope that's OK? 

Love the energy / appreciate you guys pushing this forward, naturally. Would be good to sometimes wait for us to maybe ACK an approach in the issue so we avoid getting into each other's legs..

Lmk what you think. If OK I'll close this PR and we'll integrate parts of it in Dragan's PR.

**Comment by rakita** [comment]
Closing it as changes are merged in this PR: https://github.com/paradigmxyz/reth/pull/756

**Pull request closed without merging**
