### PR TITLE
chore(ci): book lint

### PR DESCRIPTION
**Pull request by shekhirin**

### CODE REVIEW

**Review by onbjerg — CHANGES_REQUESTED** [review]
I'd add lint as a dependency of either `build` or `deploy`

**Comment by shekhirin** [comment]
> I'd add lint as a dependency of either `build` or `deploy`

Not sure why, it took 4 seconds and you instantly new that something's off with the lint and not the build/deploy process.

**Comment by onbjerg** [comment]
> I'd add lint as a dependency of either build or deploy

Because if it's a dep of build, then the order is lint -> build -> deploy, and if its a dep of deploy then the order is lint -> deploy. basically I am asking to gate deployment based on lints (don't deploy if lints don't pass) :)

**Comment by onbjerg** [comment]
I think I just worded it poorly/didn't include the actual intent 😄

**Review by onbjerg — APPROVED** [review]

**Pull request merged**
