### PR TITLE
chore(primitives): derive `Compact` for `StageUnitCheckpoint`

### PR DESCRIPTION
**Pull request by shekhirin**
Made possible by https://github.com/paradigmxyz/reth/pull/3419

### CODE REVIEW

**Comment by joshieDo** [comment]
Would wait on https://github.com/paradigmxyz/reth/pull/3341#issuecomment-1611831489 since it's related

**Review by mattsse — APPROVED** [review]
lgtm,

blocking PR is merged,

> It's a breaking change, @joshieDo tested it.

oh should we hold off merging this then?

**Comment by onbjerg** [comment]
@mattsse yeah hold off

**Comment by shekhirin** [comment]
emphasised the do not merge message in pr desc

**Review by onbjerg — APPROVED** [review]
good to merge into breaking changes branch

**Pull request merged**
