### PR TITLE
refactor: phase out ether genesis in primitives

### LINKED ISSUE #2293: Phase out EthersGenesis in primitives
### Describe the feature

we currently use two genesis types (ethers,reth)

Used by chainspec:

https://github.com/paradigmxyz/reth/blob/0761bb42f7c2425d2d4d18f4e5ea991d13a72ef2/crates/primitives/src/chain/spec.rs#L9-L9

during serde

## TODO

* get rid of `EthersGenesis` entirely
* add missing ChainConfig to `reth::Genesis`

### Additional context

_No response_

### LINKED ISSUE #3200: Support ChainConfig type in `Genesis`
### Describe the feature

Add ChainConfig type to reth's genesis type:

https://github.com/paradigmxyz/reth/blob/5e0508b973458e3ff0cfcf28f608d76c0b37e712/crates/primitives/src/genesis.rs#L15-L18

see existing ethers type which already has it

### Additional context

related https://github.com/paradigmxyz/reth/pull/2311

_No response_

### PR DESCRIPTION
**Pull request by i-m-aditya**
Fixes #2293
Closes #3200

### CODE REVIEW

**Comment by i-m-aditya** [comment]
@mattsse We can't remove ethers-core::utils::Genesis from the codebase entirely because there are some places where ethers-core::utils is being used, which internally uses ethers-core::utils::Genesis, so for that, I have implemented the From trait for reth_primitives::Genesis for conversions.

**Comment by Rjected** [comment]
Thanks for picking this up!

I think what we want here is the reduce reliance on `ethers_core::utils::Genesis` across the codebase, ideally so we can use types from primitives to deserialize a geth `genesis.json` for example. So creating some tests showing we can still deserialize a geth-formatted `genesis.json` would be ideal. ethers should have some example `genesis.json`s in tests if there aren't already test vectors in primitives!

**Comment by mattsse** [comment]
@i-m-aditya any update on this?
I really don't to try to get this over the line, this has been open for a while now

**Comment by mattsse** [comment]
@Rjected what's missing here?

**Comment by Rjected** [comment]
> @Rjected what's missing here?

We should move the ser/deser tests from the ethers Genesis here, since we need to be compatible with the geth `genesis.json`, and it is surprisingly hard to hit all of the cases:
https://github.com/gakonst/ethers-rs/blob/97f891fc321e68164a4bd0a6c422be33c3482864/ethers-core/src/utils/genesis.rs#L353-L361

Other than that, this does reduce reliance on the ethers `Genesis` type, although we still borrow the ethers `ChainConfig` / `GenesisAccount` (this is probably fine).

**Comment by mattsse** [comment]
@Rjected this has been open for a while now, 
should we close?
I'm not exactly sure what changes this still requires.

**Comment by mattsse** [comment]
this has been open for way too long...

I finally completed this, ptal @Rjected

**Review by Rjected — APPROVED** [review]
awesome, thx for taking this over the line! lgtm

**Pull request merged**
