### PR TITLE
asm-keccak added

### PR DESCRIPTION
**Pull request by lordshashank**
- resolving https://github.com/paradigmxyz/reth/issues/5874
- enabling asm-keccak implementation in reth primitives and CI.

### CODE REVIEW

**Comment by lordshashank** [comment]
@DaniPopes sorry for being late. I have added asm-keccak to reth primitives and CI, I looked into ```keccak256``` implementation it already has check and impementation for asm-keccak feature. I think ```cargo build --release``` would enable asm-keccak now. Let me know if my interpretaion is wrong and what else is to be done.

**Comment by Rjected** [comment]
To make sure this gets run in the release CI workflow this should probably include `asm-keccak`
https://github.com/paradigmxyz/reth/blob/8edce6d764fb605d4292b1ea98da02a971785755/Makefile#L234

**Comment by lordshashank** [comment]
> To make sure this gets run in the release CI workflow this should probably include `asm-keccak`
> 
> https://github.com/paradigmxyz/reth/blob/8edce6d764fb605d4292b1ea98da02a971785755/Makefile#L234
Done @Rjected , Let me know if something else is needed.

**Comment by lordshashank** [comment]
Hey can someone help me, why the checks failed? I am not able to get this.

**Comment by Rjected** [comment]
> Hey can someone help me, why the checks failed? I am not able to get this.

I think this is a failure in the crates.io API, let me re-run the workflows

**Comment by gakonst** [comment]
cc @DaniPopes ptal

**Review by DaniPopes — APPROVED** [review]
Thanks!

I have updated the features paragraph in the installing from source chapter and made the feature optional.

For future reference, the `asm-keccak` feature is not very portable since the assembly itself isn't. Please see the [target table here](https://github.com/DaniPopes/keccak-asm?tab=readme-ov-file#support) for all the supported targets of this feature.

**Pull request merged**
