### PR TITLE
`reth-primitives`: Hide `alloy-consensus/arbitrary` behind `reth-primitives/arbitrary`

### PR DESCRIPTION
**Pull request by citizen-stig**
So proptest dependencies are not compiled by default

### CODE REVIEW

**Comment by citizen-stig** [comment]
Will rebase on latest master to double-check. Because make pr passed on my machine.

**Comment by citizen-stig** [comment]
Guys, I can address clippy warnings, but it looks like they are unrelated to changes I did.

What would be the best way?

**Comment by DaniPopes** [comment]
Rebase after https://github.com/paradigmxyz/reth/pull/8822

**Comment by citizen-stig** [comment]
@DaniPopes , thank you sir!

done!

**Review by DaniPopes — APPROVED** [review]

**Pull request merged**
