### PR TITLE
feat: metric of reorg depth of blockchain tree

### PR DESCRIPTION
**Pull request by int88**
fixes part of #3817

### CODE REVIEW

**Comment by int88** [comment]
test result:

```bash
root@test:~# curl http://127.0.0.1:9001 | grep latest_reorg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27701  100 27701    0     0  13.2M      0 --:--:-- --:--:-- --:--:-- 13.2M
# HELP reth_blockchain_tree_latest_reorg_depth The latest reorg depth
# TYPE reth_blockchain_tree_latest_reorg_depth gauge
reth_blockchain_tree_latest_reorg_depth 0
```

@Rjected PTAL

**Comment by onbjerg** [comment]
cc @rkrasiuk / @Rjected / @rakita PTAL

**Comment by rkrasiuk** [comment]
hmm, i'd rather use a Histogram and plot it as a histogram over time on the dashboard. curious to hear your thoughts @onbjerg

**Comment by Rjected** [comment]
It would be good to know the specific deficiencies with `Histogram` since it's also relevant to this PR: #3865

**Review by Rjected — CHANGES_REQUESTED** [review]
nit: could we add a method on the tree for updating both reorg metrics? It could have `depth` as a parameter

**Comment by int88** [comment]
> nit: could we add a method on the tree for updating both reorg metrics? It could have `depth` as a parameter

@Rjected updated!

**Review by onbjerg — APPROVED** [review]
lgtm, @Rjected ?

**Review by Rjected — APPROVED** [review]
nice! lgtm

**Pull request merged**
