### PR TITLE
refactor: rename cursor functions

### PR DESCRIPTION
**Pull request by lambdaclass-user**
Ref #755 

Renames cursor functions:
* cursor -> cursor_read
* cursor_dup -> cursor_dup_read
* cursor_mut -> cursor_write
* cursor_dup_mut -> cursor_dup_write

### CODE REVIEW

**Review by onbjerg — COMMENTED** [review]
Will leave this one for @mattsse and perhaps others, I am not too keen on this change personally but I don't feel strongly either way, mostly a stylistic choice :) Code-wise looks fine to me, thanks for picking it up. If this is merged, could we also update the doc comments with something more descriptive than e.g. "DupCursor mut" in `crates/storage/db/src/abstraction/transaction.rs`? (old code debt so not a blocker)

**Review by mattsse — APPROVED** [review]
lgtm,

pending @rakita

**Review by rakita — APPROVED** [review]
lgtm, for `_mut` expectation for fn was different, read/write is more straightforward

**Comment by lambdaclass-user** [comment]
done :)

**Pull request merged**
