### PR TITLE
feat(eth-wire): Implement `p2p` stream

### PR DESCRIPTION
**Pull request by Rjected**
WIP meant to implement #64, specifically the `p2p` connection part

TODO:
 - [x] complete `p2p` handshake
 - [x] finish `Stream` and `Sink` implementations
   - [x] transform message id based on shared capabilities
 - [x] complete p2p state task
 - [x] implement test on top of `ECIESStream` and another stream type
 - [x] implement `EthStream` test on top of `P2PStream`
 - [ ] consider moving some types out of `p2pstream.rs`

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
let's allow dead_code for now, otherwise, this is a bit hard to review in the browser.

**Review by mattsse — CHANGES_REQUESTED** [review]
nice progress.

I think the main loop is halfway there, but since Ping/Pong are part of the message protocol, we can simplify how they are tracked

**Review by gakonst — COMMENTED** [review]
love the direction

**Review by mattsse — CHANGES_REQUESTED** [review]
great progress.

some comments re Stream+Sink and codec.

**Review by mattsse — COMMENTED** [review]
this looks very good now, some parts are not quite complete yet, but I'd suggest merging this now and do smaller iterations moving forward? Because I think the stream-type interfaces are somewhat stable now. 
we only really need Stream+Sinkand handshake function I believe.

wdyt @Rjected

**Review by gakonst — APPROVED** [review]
Really clean

**Pull request merged**
