### PR TITLE
feat(grafana): use reth_info to query Reth instances

### PR DESCRIPTION
**Pull request by jsvisa**
Currently, we are using `up` metric to filter reth instances, but it produces all the Prometheus instances, see below:

image

I think we can use `reth_info` instead to get accurate results.

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
not familiar with these settings but sounds reasonable

ptal @shekhirin

**Review by onbjerg — CHANGES_REQUESTED** [review]
At first glance I do not think this works, the reason we use the `up` metric is that Prometheus inserts it, and it has the following shape:

```
up{job="<job-name>", instance="<instance-id>"}: 1 if the instance is healthy, i.e. reachable, or 0 if the scrape failed.
```

We then get the `instance` label on the metric which is what the filter is actually using (see the regex).

**Comment by jsvisa** [comment]
> the reason we use the up metric is that Prometheus inserts it

Yes, Prometheus will insert `up` for each scraped job, such as I have the following two jobs:

```yaml
  - job_name: 'go-ethereum'
    scrape_interval: 10s
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets:
          - '127.0.0.1:4540'
  - job_name: 'reth'
    scrape_interval: 10s
    metrics_path: /
    static_configs:
      - targets:
          - '127.0.0.1:5550'
```

So if we use `up` in reth's dashboard, it will contain the two instances:

```
127.0.0.1:4540
127.0.0.1:5550
```

But go-ethereum(127.0.0.1:4540)'s metrics don't contain any reth's metrics, and the dashboard is empty, something like below:

image


In this PR, I prefer to use `reth_info` instead, because only reth's instances will contain the correct results.

**Comment by onbjerg** [comment]
My point is that the `instance` label does not exist on the `reth_info` metric, so I'd like to know that this works. Did you test it? I'd assume it doesn't work because the regex for the dropdown still refers to the instance label

**Review by onbjerg — APPROVED** [review]
i'm satisfied this will work, and the change makes sense. thanks for the patience (and the pr) :)

**Review by shekhirin — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
