### PR TITLE
rpc: rm useless `alloy_rpc_types` reexport

### PR DESCRIPTION
**Pull request by tcoratger**
Related https://github.com/paradigmxyz/reth/issues/11067

### CODE REVIEW

**Review by emhane — APPROVED** [review]

**Review by mattsse — APPROVED** [review]

**Comment by mattsse** [comment]
you will keep getting a ton of conflicts if you try to do this concurrently ;)

**Comment by tcoratger** [comment]
> you will keep getting a ton of conflicts if you try to do this concurrently ;)

let us merge https://github.com/paradigmxyz/reth/pull/11095 and I'll handle the conflicts here, no problem :)

**Comment by tcoratger** [comment]
@mattsse I wanted to keep individual PRs for easier review, type by type, don't know if it was the best idea ahah

**Comment by emhane** [comment]
> > you will keep getting a ton of conflicts if you try to do this concurrently ;)
> 
> let us merge #11095 and I'll handle the conflicts here, no problem :)

imo, nicer to stack these types of prs onto each other so base branch automatically changes to main and no conflicts (usually)

**Comment by tcoratger** [comment]
@emhane should be ok now fyi

**Pull request merged**
