### PR TITLE
fix: use helper to deserialize mainnet TTD

### PR DESCRIPTION
**Pull request by Rjected**
Followup to #5290, using behavior from https://github.com/gakonst/ethers-rs/pull/2617/ instead of find/replace to deserialize the mainnet TTD.

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
hmm, this is now baked into the jsonu256 helper type, but we only need this for genesis, right?

I think we should instead use an annotation there

**Comment by Rjected** [comment]
> hmm, this is now baked into the jsonu256 helper type, but we only need this for genesis, right?
> 
> I think we should instead use an annotation there

ah right, yeah, an annotation would be better so we can just do this hack for TTD rather than for everything

**Review by mattsse — APPROVED** [review]

**Comment by mattsse** [comment]
@Rjected test fails in CI for some reason, couldn't reproduce locally in reth-rpc-types

**Comment by Rjected** [comment]
hmm, I'm only able to repro with nextest run on the entire repo, but at least I can repro

**Comment by Rjected** [comment]
hmm, apparently it's possible for `is_f64`, `is_u64`, `is_i64` to all return false:

```
running 1 test
val: Number(58750000000000000000000), u64: false, f64: false, i64: false
test serde_helpers::json_u256::test::deserialize_ttd ... FAILED
```

Should be able to fix though

**Comment by Rjected** [comment]
@mattsse we can actually use `as_str` from `Number`, and pass that into `U256::from_str_radix`

**Comment by Rjected** [comment]
nevermind, that's only for arbitrary precision

**Pull request merged**
