### PR TITLE
feat: Alloy migration

### PR DESCRIPTION
**Pull request by DaniPopes**
Migrate all primitive types, ABI, RLP, and EIP-712 logic to [Alloy](https://github.com/alloy-rs/core).

See tracking issue #4715.

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
lgtm

awesome work!

**Comment by DaniPopes** [comment]
cc @gakonst

**Comment by mattsse** [comment]
@DaniPopes new conflicts -.-

**Review by gakonst — APPROVED** [review]
send it once conflicts resolved. amazing...

**Pull request merged**
