### PR TITLE
feat: switch to composable executor for Ethereum

### PR DESCRIPTION
**Pull request by fgimenez**
Towards #11274

* Removes module `reth_evm_ethereum::execute` and renames `reth_evm_ethereum::strategy` -> `reth_evm_ethereum::execute`
* Adds helper type `EthExecutorProvider` that offers the same API as the old provider type to minimize the impact of the change.
* Changes to use composable executor types `BasicBlockExecutorProvider` and `EthExecutionStrategyFactory` where needed.

Successful executions of hive https://github.com/paradigmxyz/reth/actions/runs/11388193195 and kurtosis  https://github.com/paradigmxyz/reth/actions/runs/11388196289

### CODE REVIEW

**Review by Rjected — APPROVED** [review]
nice! I like the new abstraction / implementation a lot

**Comment by Rjected** [comment]
Let's wait until https://github.com/paradigmxyz/reth/pull/11865 is merged to merge this, marking this as blocked for now

**Comment by onbjerg** [comment]
This is no longer blocked @Rjected @fgimenez :)

**Review by mattsse — APPROVED** [review]
nice, pending smol conflicts

**Pull request merged**
