### PR TITLE
feat(bin): show snapshots in `db stats`

### PR DESCRIPTION
**Pull request by shekhirin**
Snapshot stats per segment, similar to database stats per table:
```console
➜  reth (alexey/db-stats-snapshots) cargo run --bin reth -- db stats --chain holesky                                                                                                                                                                                                                                          ✭
    Finished dev [unoptimized + debuginfo] target(s) in 0.40s
     Running `target/debug/reth db stats --chain holesky`
| Segment      | Block Range     | Transaction Range  | Shape        | Data Size | Index Size | Offsets Size | Config Size | Total Size |
|--------------|-----------------|--------------------|--------------|-----------|------------|--------------|-------------|------------|
| Headers      | 0..=499999      | N/A                | 3 x 500000   | 270.1 MiB | 0 B        | 11.4 MiB     | 54 B        | 281.5 MiB  |
| Headers      | 500000..=834214 | N/A                | 3 x 334215   | 181.9 MiB | 0 B        | 7.6 MiB      | 54 B        | 189.5 MiB  |
| Transactions | 0..=499999      | 0..=1903501        | 1 x 1903502  | 664.1 MiB | 0 B        | 14.5 MiB     | 70 B        | 678.7 MiB  |
| Transactions | 500000..=850110 | 1903502..=26189416 | 1 x 24285915 | 5.4 GiB   | 0 B        | 185.3 MiB    | 70 B        | 5.6 GiB    |
| Receipts     | 0..=499999      | 0..=1903501        | 1 x 1903502  | 89.3 MiB  | 0 B        | 14.5 MiB     | 70 B        | 103.8 MiB  |
| Receipts     | 500000..=850110 | 1903502..=26189416 | 1 x 24285915 | 824.2 MiB | 0 B        | 185.3 MiB    | 70 B        | 1009.5 MiB |
| ------------ | --------------- | ------------------ | ------------ | --------- | ---------- | ------------ | ----------- | ---------- |
| Total        |                 |                    |              | 7.4 GiB   | 0 B        | 418.7 MiB    | 388 B       | 7.8 GiB    |


| Table Name        | # Entries | Branch Pages | Leaf Pages | Overflow Pages | Total Size |
|-------------------|-----------|--------------|------------|----------------|------------|
| AccountChangeSet  | 22848833  | 30988        | 233306     | 0              | 1 GiB      |
| AccountHistory    | 15796642  | 13149        | 915204     | 2568           | 3.6 GiB    |
| AccountsTrie      | 1346150   | 415          | 89748      | 0              | 352.2 MiB  |
| BlockBodyIndices  | 850111    | 23           | 4931       | 0              | 19.4 MiB   |
| BlockOmmers       | 0         | 0            | 0          | 0              | 0 B        |
| BlockWithdrawals  | 841398    | 538          | 120150     | 0              | 471.4 MiB  |
| Bytecodes         | 10886     | 19           | 1014       | 23383          | 95.4 MiB   |
| CanonicalHeaders  | 849545    | 163          | 20024      | 0              | 78.9 MiB   |
| HashedAccount     | 15793454  | 4885         | 299445     | 0              | 1.2 GiB    |
| HashedStorage     | 10099254  | 4374         | 188538     | 0              | 753.6 MiB  |
| HeaderNumbers     | 850111    | 270          | 15299      | 0              | 60.8 MiB   |
| HeaderTD          | 849545    | 20           | 4186       | 0              | 16.4 MiB   |
| Headers           | 849545    | 1795         | 206807     | 0              | 814.9 MiB  |
| PlainAccountState | 15793454  | 2503         | 234574     | 0              | 926.1 MiB  |
| PlainStorageState | 10099254  | 4169         | 185959     | 0              | 742.7 MiB  |
| PruneCheckpoints  | 1         | 0            | 1          | 0              | 4 KiB      |
| Receipts          | 25775366  | 1144         | 255656     | 99069          | 1.4 GiB    |
| StorageChangeSet  | 13072606  | 28481        | 192555     | 0              | 863.4 MiB  |
| StorageHistory    | 10340037  | 20559        | 714852     | 736            | 2.8 GiB    |
| StoragesTrie      | 973113    | 6118         | 65747      | 0              | 280.7 MiB  |
| SyncStage         | 14        | 0            | 1          | 0              | 4 KiB      |
| SyncStageProgress | 1         | 0            | 1          | 0              | 4 KiB      |
| TransactionBlock  | 685732    | 21           | 4396       | 0              | 17.3 MiB   |
| Transactions      | 0         | 0            | 0          | 0              | 0 B        |
| TxHashNumber      | 26189417  | 8161         | 485665     | 0              | 1.9 GiB    |
| TxSenders         | 26024907  | 1088         | 243227     | 0              | 954.4 MiB  |
| ----------------- | --------- | ------------ | ---------- | -------------- | ---------- |
| Tables            |           |              |            |                | 18.1 GiB   |
| Freelist          | 1974764   |              |            |                | 7.5 GiB    |
```

Can also show only total size per snapshot segment with `--only-total-size` argument:
```console
➜  reth (alexey/db-stats-snapshots) cargo run --bin reth -- db stats --chain holesky --only-total-size                                                                                                                                                                                                                        ✭
    Finished dev [unoptimized + debuginfo] target(s) in 0.40s
     Running `target/debug/reth db stats --chain holesky --only-total-size`
| Segment      | Block Range     | Transaction Range  | Shape        | Size       |
|--------------|-----------------|--------------------|--------------|------------|
| Headers      | 0..=499999      | N/A                | 3 x 500000   | 281.5 MiB  |
| Headers      | 500000..=834214 | N/A                | 3 x 334215   | 189.5 MiB  |
| Transactions | 0..=499999      | 0..=1903501        | 1 x 1903502  | 678.7 MiB  |
| Transactions | 500000..=850110 | 1903502..=26189416 | 1 x 24285915 | 5.6 GiB    |
| Receipts     | 0..=499999      | 0..=1903501        | 1 x 1903502  | 103.8 MiB  |
| Receipts     | 500000..=850110 | 1903502..=26189416 | 1 x 24285915 | 1009.5 MiB |
| ------------ | --------------- | ------------------ | ------------ | ---------- |
| Total        |                 |                    |              | 7.8 GiB    |


| Table Name        | # Entries | Branch Pages | Leaf Pages | Overflow Pages | Total Size |
|-------------------|-----------|--------------|------------|----------------|------------|
| AccountChangeSet  | 22848833  | 30988        | 233306     | 0              | 1 GiB      |
| AccountHistory    | 15796642  | 13149        | 915204     | 2568           | 3.6 GiB    |
| AccountsTrie      | 1346150   | 415          | 89748      | 0              | 352.2 MiB  |
| BlockBodyIndices  | 850111    | 23           | 4931       | 0              | 19.4 MiB   |
| BlockOmmers       | 0         | 0            | 0          | 0              | 0 B        |
| BlockWithdrawals  | 841398    | 538          | 120150     | 0              | 471.4 MiB  |
| Bytecodes         | 10886     | 19           | 1014       | 23383          | 95.4 MiB   |
| CanonicalHeaders  | 849545    | 163          | 20024      | 0              | 78.9 MiB   |
| HashedAccount     | 15793454  | 4885         | 299445     | 0              | 1.2 GiB    |
| HashedStorage     | 10099254  | 4374         | 188538     | 0              | 753.6 MiB  |
| HeaderNumbers     | 850111    | 270          | 15299      | 0              | 60.8 MiB   |
| HeaderTD          | 849545    | 20           | 4186       | 0              | 16.4 MiB   |
| Headers           | 849545    | 1795         | 206807     | 0              | 814.9 MiB  |
| PlainAccountState | 15793454  | 2503         | 234574     | 0              | 926.1 MiB  |
| PlainStorageState | 10099254  | 4169         | 185959     | 0              | 742.7 MiB  |
| PruneCheckpoints  | 1         | 0            | 1          | 0              | 4 KiB      |
| Receipts          | 25775366  | 1144         | 255656     | 99069          | 1.4 GiB    |
| StorageChangeSet  | 13072606  | 28481        | 192555     | 0              | 863.4 MiB  |
| StorageHistory    | 10340037  | 20559        | 714852     | 736            | 2.8 GiB    |
| StoragesTrie      | 973113    | 6118         | 65747      | 0              | 280.7 MiB  |
| SyncStage         | 14        | 0            | 1          | 0              | 4 KiB      |
| SyncStageProgress | 1         | 0            | 1          | 0              | 4 KiB      |
| TransactionBlock  | 685732    | 21           | 4396       | 0              | 17.3 MiB   |
| Transactions      | 0         | 0            | 0          | 0              | 0 B        |
| TxHashNumber      | 26189417  | 8161         | 485665     | 0              | 1.9 GiB    |
| TxSenders         | 26024907  | 1088         | 243227     | 0              | 954.4 MiB  |
| ----------------- | --------- | ------------ | ---------- | -------------- | ---------- |
| Tables            |           |              |            |                | 18.1 GiB   |
| Freelist          | 1974764   |              |            |                | 7.5 GiB    |
```

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
I think more info/columns is better, though I think we should print the static files table first before the db

**Comment by rkrasiuk** [comment]
agree w/ @mattsse

**Comment by shekhirin** [comment]
@mattsse @rkrasiuk do you think we should display a detailed breakdown of static file sizes by default?

**Review by mattsse — APPROVED** [review]
> do you think we should display a detailed breakdown of static file sizes by default?

I think so

**Review by onbjerg — APPROVED** [review]

**Pull request merged**
