### PR TITLE
feat: adds eth request panels to grafana

### LINKED ISSUE #8334: Integrate eth request metrics into grafana dashboard
### Describe the feature

We have the following metrics for the different `eth` request types:
https://github.com/paradigmxyz/reth/blob/6b14cbc5e75b12efcbf5e7085ad6ac25a82f4ee3/crates/net/network/src/metrics.rs#L309-L324

These should be added to the grafana dashboard, so we can observe in real time how many of each type of request we receive.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by d3or**
Adds eth request panels to grafana dashboard.

Fixes #8334

### CODE REVIEW

**Comment by d3or** [comment]
How does this look? 
image

**Review by mattsse — APPROVED** [review]
that's awesome, tysm

we could perhaps drop the `Eth ` prefix from the panels

pending @Rjected

**Review by onbjerg — APPROVED** [review]

**Review by onbjerg — DISMISSED** [review]
actually, i'd prefer if it was not just a line that goes up forever, can we turn it into a `rate()` instead and set the unit to req/s

**Comment by Rjected** [comment]
> actually, i'd prefer if it was not just a line that goes up forever, can we turn it into a `rate()` instead and set the unit to req/s

yeah, agree with this

**Review by mattsse — APPROVED** [review]

**Pull request merged**
