### PR TITLE
perf(rpc): remove full block lookup

### PR DESCRIPTION
**Pull request by rkrasiuk**
## Description

Avoid looking up full block data on `eth_getLogs`

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
I don't see how this saves anything

**Comment by rkrasiuk** [comment]
@mattsse we skip either ommers or withdrawals lookup depending on the block

**Comment by mattsse** [comment]
> we skip either ommers or withdrawals lookup depending on the block as well as duplicate retrieval of block header from the database

I don't see how this is relevant here, this change only changes what we get from the cache, no?

**Comment by rkrasiuk** [comment]
@mattsse i see now that the cache requests transactions as a full block. wasn't obvious at first. are you open to modifying the behavior? otherwise we do a lot of redundant lookups by always calling `block_by_hash`

**Comment by mattsse** [comment]
open to it, but will complicate caching further

**Comment by rkrasiuk** [comment]
closing for now

**Pull request closed without merging**
