### PR TITLE
feat(net): ignore transactions during sync

### LINKED ISSUE #701: Discard incoming broadcasts in sync mode
### Describe the feature

part of #680

when the network is syncing, discard incoming transactions.

the easiest way would be in the transaction manager and simply do nothing on incoming requests/broadcasts if `network.is_syncing()`:

example:

https://github.com/paradigmxyz/reth/blob/93b6ce597ad192e6ee6b7ef60fdaa030d0a16a51/crates/net/network/src/transactions.rs#L265

`if network.is_syncing() {return;}`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mattsse**
Closes #701

* ignore incoming tx broadcasts
* don't propagate tx

while syncing

### CODE REVIEW

**Review by gakonst — CHANGES_REQUESTED** [review]
Nice. Would like a test as well for each of these if's just so we don't regress in the future.

**Review by rkrasiuk — APPROVED** [review]
lgtm pending @gakonst's comment about tests

**Comment by gakonst** [comment]
Also another thought:

This still uses up the pool channel...so should we instead leave it to be `None` while it's syncing? Maybe it is already? If it is, I'm surprised at why we get so much ingress from bot nodes.

**Comment by mattsse** [comment]
> This still uses up the pool channel...so should we instead leave it to be None while it's syncing? 

this makes setup more complicated because then we'd need to wire the components on the fly. 

the only thing that's extra work here is the `network -> tx` channel delegate, we're always decoding the message from the tcpstream.

**Comment by gakonst** [comment]
> this makes setup more complicated because then we'd need to wire the components on the fly.

Mhm. I guess it's OK. The diff would be if we were filtering on the TcpStream directly w/o decoding, which is a bit further away from where we're at right now. 

Let's merge this to get thru the bots, and let's add a test as a follow-up.

**Comment by mattsse** [comment]
> Mhm. I guess it's OK. The diff would be if we were filtering on the TcpStream directly w/o decoding, which is a bit further away from where we're at right now.

imo, this is really not worth adding selective partial decoding to the stream, just increases complexity

**Pull request merged**
