### PR TITLE
fix(executor): wiped postate storage

### LINKED ISSUE #1848: bug(executor): wiped storage handling
The way that the `PostState` keeps track of wiped storage is wrong
https://github.com/paradigmxyz/reth/blob/f6bd0bc57e929ba191d08dfeb74232c224299911/crates/storage/provider/src/post_state.rs#L406-L416

Consider a scenario where within a single batch of blocks the account was destroyed and recreated. Then the storage in the database wouldn't be cleared.
https://github.com/paradigmxyz/reth/blob/f6bd0bc57e929ba191d08dfeb74232c224299911/crates/storage/provider/src/post_state.rs#L527-L556

There are more scenarios like this that would involve storage changes after account recreation, but, in the end, would also lead to an incorrect database state.

### PR DESCRIPTION
**Pull request by rkrasiuk**
Potentially, fixes #1848. Keeping as a draft for now

### CODE REVIEW

**Comment by gakonst** [comment]
Tested it and doesn't seem to fix the issue. @onbjerg pls confirm this is a bug

**Comment by rkrasiuk** [comment]
@gakonst i'll keep this PR as draft until u finish resyncing

**Review by onbjerg — APPROVED** [review]
This is definitely a bug, so LGTM, however I do not know if it is directly related to the sync bug we are experiencing. Regardless, this should be good to merge.

@rkrasiuk Can you validate that I understood the bug correctly by approving the test I added?

**Review by rkrasiuk — COMMENTED** [review]
test lgtm ❤️

**Pull request merged**
