### PR TITLE
test: `CanonChainTracker` implementation for `BlockchainProvider2`

### LINKED ISSUE #10352: Test `CanonChainTracker` implementation of `BlockchainProvider2<DB>`

### PR DESCRIPTION
**Pull request by greged93**
Adds tests for the `CanonChainTracker` implementation of the `BlockchainProvider2` and closes #10352.

### CODE REVIEW

**Comment by shekhirin** [comment]
Is this ready for review? We merged a bunch of other tests and helper functions into main, can you please merge it into your branch?

**Comment by greged93** [comment]
Was waiting for the helper to get merged, will rebase

**Comment by greged93** [comment]
@shekhirin should be ready now

**Review by mattsse — APPROVED** [review]

**Comment by mattsse** [comment]
smol conflict

**Review by shekhirin — APPROVED** [review]
LGTM

**Pull request merged**
