### PR TITLE
fix code label_pr.js

### PR DESCRIPTION
**Pull request by teenager-ETH**
# Pull Request: Fix Code `label_pr.js`

## Title
**fix code label_pr.js**

---

## Description
Add your description here...

Be sure to include:
- A summary of the changes made.
- The reason for the changes.
- Any relevant details for reviewers.

---

## Checklist
Please ensure the following before submitting the pull request:
- [ ] The code adheres to the project's [contributing guidelines](link-to-guidelines).
- [ ] Security vulnerabilities have been addressed or reported as per the [security policy](link-to-security-policy).
- [ ] All changes have been tested locally.

---

## Commit Details
**Commits on Dec 23, 2024**
- `fix code label_pr.js`  
  **Author**: @teenager-ETH  
  **Summary**: Showing 5 changes: 3 additions and 2 deletions in the file `.github/assets/label_pr.js`.

---

## Code Changes
**File**: `.github/assets/label_pr.js`

**Modifications**:
```javascript
// Original code
const urlPattern = new RegExp(`(close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved) ${repoUrl}/issues/(?<issue_number>\\d+)`, 'i');
const issuePattern = new RegExp(`(close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved) \#(?<issue_number>\\d+)`, 'i');

// Updated code
const urlPattern = /(close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved) https:\/\/repoUrl\/issues\/(?<issue_number>\d+)/i;
const issuePattern = /(close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved) \#(?<issue_number>\d+)/i;

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
what's an url where the previous pattern is insufficient?

**Comment by teenager-ETH** [comment]
What do you mean?

**Comment by mattsse** [comment]
unclear what this fixes, do you have an example URL that demonstrates the fix?

**Comment by mattsse** [comment]
closing this because the existing regex looks fine to me

**Pull request closed without merging**
