### PR TITLE
feat(metrics): derive with dynamic scope

### LINKED ISSUE #782: Allow setting metric scope at the time of instantiation
### Describe the feature

Currently, our `metrics-derive` crate allows setting a "scope" used to describe a struct containing metrics when defining the struct.

This precludes us from being able to use multiple instances of a metrics struct in different places.

Ideally, the `metrics-derive` crate would expose some way to set the scope of a metrics struct at the time of instantiation, so multiple instances won't all have the same metric name.

### Additional context

This is required by #140 and #738

### PR DESCRIPTION
**Pull request by rkrasiuk**
closes #782 

Provide additional `dynamic` kv entry for `Metrics` derive macro. If `dynamic = true`, the macro will generate fns for dynamic scope instead of operating on a preset one.

Examples
```rust
#[derive(Metrics)]
#[metrics(scope = "some_scope")]
struct StaticScopeMetrics {
     // fields...
}

// Describe
StaticScopeMetrics::describe();
// Instantiate
let metrics = StaticScopeMetrics::default();

#[derive(Metrics)]
#[metrics(dynamic = true)]
struct DynamicScopeMetrics {
     // fields...
}

let local_scope = "some_scope";
// Describe
StaticScopeMetrics::describe(local_scope);
// Instantiate
let metrics = DynamicScopeMetrics::new(local_scope);
```

NOTE: still need to update the docs.

### CODE REVIEW

**Comment by akirillo** [comment]
Ok, this is making sense to me at a high level, and LGTM as it's passing tests!

A couple **non-blocking** questions from a Rust newbie:

1. It feels like there's a lot of duplicate code between the `MetricsScope::Static` and `MetricsScope::Dynamic` branches, the only differences being how `metric_name` is constructed and what the final `quote!` block is that's returned - I'm curious, why not  just `match` against the `MetricScope` enum when defining these two variables, instead of around the entire iteration over `metric_fields`? I guess the way you do it here avoids branching within each iteration, which is nice.
2. In line with this, why move the generation of `metric_name` outside of the `impl Metric` block in `metric.rs`, and into `derive` in `expand.rs`? Doesn't change the API so it doesn't matter much, I guess

**Review by akirillo — APPROVED** [review]

**Review by gakonst — COMMENTED** [review]
@joshieDo wanna take this over the line once you have some bandwidth from the proptests? @rkrasiuk is sprinting on the new downloader in #881

**Comment by rkrasiuk** [comment]
@akirillo expressed interest in taking it over as well

**Comment by rkrasiuk** [comment]
we simply need to fix some docs & comments here, that's it

**Comment by akirillo** [comment]
yup, will take over on this

**Comment by gakonst** [comment]
Ah ACK!

**Comment by akirillo** [comment]
@rkrasiuk added a quick usage example to `lib.rs`, any other areas of documentation I should touch on? Couldn't see anything else at a glance

**Pull request merged**
