### PR TITLE
Implement compact codec for alloy eip access_list

### PR DESCRIPTION
**Pull request by ghost**
Ref https://github.com/paradigmxyz/reth/issues/7050

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
this is equivalent, the `AccessListFlags` is a zst

```rust
impl Compact for AccessListItem {
        fn to_compact<B>(self, buf: &mut B) -> usize
        where
            B: bytes::BufMut + AsMut<[u8]>,
        {
            let mut flags = AccessListItemFlags::default();
            let mut total_length = 0;
            let mut buffer = bytes::BytesMut::new();
            let address_len = self.address.to_compact(&mut buffer);
            let storage_keys_len = self.storage_keys.specialized_to_compact(&mut buffer);
            let flags = flags.into_bytes();
            total_length += flags.len() + buffer.len();
            buf.put_slice(&flags);
            buf.put(buffer);
            total_length
        }
        fn from_compact(mut buf: &[u8], len: usize) -> (Self, &[u8]) {
            let (flags, mut buf) = AccessListItemFlags::from(buf);
            let (address, new_buf) = Address::from_compact(buf, buf.len());
            buf = new_buf;
            let (storage_keys, new_buf) = Vec::specialized_from_compact(buf, buf.len());
            buf = new_buf;
            let obj = AccessListItem {
                address: address,
                storage_keys: storage_keys,
            };
            (obj, buf)
        }
    }


impl Compact for AccessList {
        fn to_compact<B>(self, buf: &mut B) -> usize
        where
            B: bytes::BufMut + AsMut<[u8]>,
        {
            let mut flags = AccessListFlags::default();
            let mut total_length = 0;
            let mut buffer = bytes::BytesMut::new();
            let _len = self.0.to_compact(&mut buffer);
            let flags = flags.into_bytes();
            total_length += flags.len() + buffer.len();
            buf.put_slice(&flags);
            buf.put(buffer);
            total_length
        }
        fn from_compact(mut buf: &[u8], len: usize) -> (Self, &[u8]) {
            let (flags, mut buf) = AccessListFlags::from(buf);
            let (placeholder, new_buf) = Vec::from_compact(buf, buf.len());
            buf = new_buf;
            let obj = AccessList(placeholder);
            (obj, buf)
        }
    }
```

**Review by mattsse — APPROVED** [review]
lgtm, pending @joshieDo

**Review by mattsse — CHANGES_REQUESTED** [review]
awesome, could you please extract the last commit with withdrawals to a new pr?

**Comment by mattsse** [comment]
I'd prefer this in a separate pr

**Comment by 0xqd** [comment]
> I'd prefer this in a separate pr

kk, will do. I will create new pr and revert this soon.

**Comment by mattsse** [comment]
appreciate it, will merge [8e9cbf4](https://github.com/paradigmxyz/reth/pull/7554/commits/8e9cbf4e00d872b3021947c3880ce14ffcb5c0a9) then

**Comment by mattsse** [comment]
separately, 
if you want you can submit a pr that does retire reth-primitives::Log and switches everything to alloy-primitives::Log

**Review by mattsse — APPROVED** [review]

**Review by joshieDo — APPROVED** [review]

**Pull request merged**
