### PR TITLE
fix: store eof bytecode with header in compact

### PR DESCRIPTION
**Pull request by onbjerg**
Cherry-picked from frontiers changes

### CODE REVIEW

**Review by shekhirin — APPROVED** [review]
LGTM, and let's create an issue to fix this hack

**Comment by onbjerg** [comment]
Will adjust the test after I open up the remaining cherry pick PRs and create a follow up issue to resolve before Prague is live

**Comment by rkrasiuk** [comment]
@onbjerg requires revm bump?

**Comment by onbjerg** [comment]
yep..

**Comment by onbjerg** [comment]
Superseded by https://github.com/paradigmxyz/reth/pull/10537

**Pull request closed without merging**
