### PR TITLE
feat: move crate cli/runner to cli-runner

### PR DESCRIPTION
**Pull request by jsvisa**

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
this was specifically moved there

**Comment by mattsse** [comment]
not planned

**Comment by jsvisa** [comment]
> there's more coming to `cli`, because we need an entire CLI abstraction, so all the abstractions etc will go there

thanks for the explanation, does this means we will move more implies from [bin/reth](bin/reth) to the [crates/cli](crates/cli) crate? If so, is there any issue or roadmap to track it. and is there anything that I can help with, I'm happy to try it :)

**Comment by mattsse** [comment]
yes, something like this!

scoping out proper tasks by eow.

that'd be great! mind reaching out on tg @mattsse and I'll keep you up to date

**Comment by jsvisa** [comment]
@mattsse, I'm sorry, it seems like I can't send dm to you in tg, could you please add my account [@delweng](https://t.me/delweng), or could you share your discord account with me(or add my id `.j8j`), thanks.

**Pull request closed without merging**
