### PR TITLE
fix(op): custom testinprod receipt encoding

### PR DESCRIPTION
**Pull request by emhane**
- Moves receipt decoding into codec scope
- Renames custom testinprod receipt codec type to `HackReceiptFileCodec`
- Adds test for `ReceiptFileClient`

### CODE REVIEW

**Comment by Rjected** [comment]
will merge this once it succeeds, then merge the other one, then approve the initial receipts import PR because we have enough evidence that it works now

**Comment by Rjected** [comment]
hmm, getting this for the final call to `write_to_storage`
```
2024-05-03T18:04:57.910719Z TRACE downloaders::file: Initialized receipt file client blocks=338256 total_receipts=338256
2024-05-03T18:04:57.970487Z  INFO reth::cli: Importing receipt file chunk first_receipts_block=104896808 total_receipts_chunk=338256
thread 'tokio-runtime-worker' panicked at /home/ubuntu/reth-dan/crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs:354:26:
receipt should not be filtered when saving to static files.
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_failed
   3: reth_provider::bundle_state::bundle_state_with_receipts::BundleStateWithReceipts::write_to_storage
   4: reth::commands::import_receipts::ImportReceiptsCommand::execute::{{closure}}
   5: tokio::runtime::park::CachedParkThread::block_on
   6: tokio::runtime::context::runtime::enter_runtime
   7: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
   8: tokio::runtime::task::core::Core<T,S>::poll
   9: tokio::runtime::task::raw::poll
  10: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at /home/ubuntu/reth-dan/crates/cli/runner/src/lib.rs:91:63:
Failed to join task: JoinError::Panic(Id(49), ...)
stack backtrace:
   0: rust_begin_unwind
```

**Comment by Rjected** [comment]
it looks like the receipts can't be `None` unfortunately

**Comment by emhane** [comment]
> it looks like the receipts can't be `None` unfortunately

is there an EIP that says blocks cannot have zero transactions now? if so will change the code in import command, otherwise in `write_to_storage` cause it's actually a bug, since that function calculates block number by `first-block + index-in-receipts-list`

**Comment by Rjected** [comment]
> is there an EIP that says blocks cannot have zero transactions now

Blocks can still have zero transactions, but a `None` receipt represents a pruned receipt:
https://github.com/paradigmxyz/reth/blob/1c73777bf8cbd5c304e248c2ae2d83607395d72c/crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs#L31

So, I'd say this is less of a bug and more of an assumption - we should just filter out the `None` receipt values before passing it to `write_to_storage`.

To get to that point in `write_to_storage`, we need to be iterating over a non-empty `receipts`, and encounter a `None` receipt value here:
https://github.com/paradigmxyz/reth/blob/1c73777bf8cbd5c304e248c2ae2d83607395d72c/crates/storage/provider/src/bundle_state/bundle_state_with_receipts.rs#L335-L337

**Pull request merged**
