### PR TITLE
feat: add support for wrapping the allocator with tracy

### PR DESCRIPTION
**Pull request by DaniPopes**
Useful for profiling memory usage w/ backtraces at allocation and deallocation of every object.

New deps in Cargo.lock are unreachable because of `cfg(loom)`.

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
cool, lgtm pending @Rjected

**Review by emhane — APPROVED** [review]
nice

**Comment by DaniPopes** [comment]
Example:
image

**Review by Rjected — APPROVED** [review]
nice, lgtm

**Pull request merged**
