### PR TITLE
ci: pass `--locked` and use path deps in book

### PR DESCRIPTION
**Pull request by onbjerg**
We were updating the lockfile in some CI workflows which breaks if e.g. Alloy has breaking changes.

To fix the book workflow, we use path dependencies

### CODE REVIEW

**Comment by onbjerg** [comment]
This currently does not fix the merge queue issues because of https://github.com/paradigmxyz/reth/blob/6e5176221ff8b5cacea12c86dc52feba0de1593a/.gitignore#L54-L55

**Review by mattsse — APPROVED** [review]

**Comment by mattsse** [comment]
the arg is also provided multiple times

**Review by shekhirin — APPROVED** [review]

**Comment by onbjerg** [comment]
This actually won't unblock CI as is, but will unblock CI for #11986. We should probably just roll the path patch into that PR 🙃 Alternatively we can force merge this and rebase that PR on top, but it's blocked by revm release

**Comment by onbjerg** [comment]
Rolled into the alloy bump pr

**Pull request closed without merging**
