### PR TITLE
feat: support skip attribute in RlpEncodable derive macro

### LINKED ISSUE #1102: Support `skip` attribute in RlpEncodable derive macro
### Describe the feature

There are use cases where being able to skip fields during rlp encoding is useful:

https://github.com/paradigmxyz/reth/issues/1101

Currently, we don't support this in the `RlpEncodable` derive macro.

## TODO

add `rlp(skip)` field attribute support for `RlpEncodable` macro that should work the same as `serde(skip)`.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by leruaa**
Closes #1102

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
lgtm

**Comment by leruaa** [comment]
@mattsse I think This PR can't be merged yet, the skipped fields are still taken into account in `RlpMaxEncodedLen`

**Comment by onbjerg** [comment]
Converting to a draft, feel free to move out of draft when this is ready for review!

**Comment by leruaa** [comment]
It's ready to be reviewed 👍

**Review by mattsse — APPROVED** [review]

**Pull request merged**
