### PR TITLE
test(provider): `RequestsProvider` of `BlockchainProvider2`

### LINKED ISSUE #10343: Test `RequestsProvider` implementation of `BlockchainProvider2<DB>`

### PR DESCRIPTION
**Pull request by shekhirin**
Closes https://github.com/paradigmxyz/reth/issues/10343

The change turned out to be more invasive than expected because I added an argument for randomly generating requests into `random_block` and `random_block_range`.

### CODE REVIEW

**Review by VersoriumX — APPROVED** [review]

**Review by emhane — APPROVED** [review]
lgtm

**Review by emhane — COMMENTED** [review]
how about otherwise making new function for when new param is used? seems like most calls take `None` for that param, so mainly not needed. this can be done easily by adding a third function, with the body of the current function, so that the function body of the original function, can just call `my_func(arg1, arg2, .., None)`

**Comment by shekhirin** [comment]
> how about otherwise making new function for when new param is used? seems like most calls take `None` for that param, so mainly not needed. this can be done easily by adding a third function, with the body of the current function, so that the function body of the original function, can just call `my_func(arg1, arg2, .., None)`

yeah makes sense, agreed. Maybe we can just pass a struct instead of fields one by one, and the struct will have a `Default` implementation.

**Comment by shekhirin** [comment]
hmm, actually we have just one optional field now which is `requests_count`. I think we should leave it as-is and refactor into a struct when needed.

**Review by mattsse — APPROVED** [review]

**Pull request merged**
