### PR TITLE
feat: add CachedReads and CachedReadsDbRef

### PR DESCRIPTION
**Pull request by mattsse**
ref #2381

This adds a `DatabaseRef` impl that caches all disk reads and can be used for payload building via `CacheDB`.

During the creation of the payload, the same transactions are executed over and over again. always on top of the same state (parent hash of payload is determined).

This will prevent Disk io for subsequent payload build attempts which can use cached reads instead.

### CODE REVIEW

**Comment by mattsse** [comment]
> This seems ok but it is unclear how this would be integrated with the current executor because of the API surface. 

this will be integrated with the payloadbuilder, which repeatedly executes the same transactions against the same state, for which this is the perfect usecase.

for example:
1. payload job is trigger
2. empty cachedreads instance is created
3. first payload build attempt is triggered -> fills `CachedReads`
4. ...
5. second payload build attempt is triggered -> reuses `CachedReads` and extends it
6. repeat until payload resolved

**Comment by onbjerg** [comment]
@mattsse I am not disagreeing with the main idea of this PR, I am more trying to convey that this implementation is not currently easy to integrate with the executor as it is in it's current form as it expects a `SubState<DB> where DB: StateProvider`:

https://github.com/paradigmxyz/reth/blob/ab55ea5e04292f21a60a83eeed5b8542f9c55d09/crates/revm/src/executor.rs#L57

Instead, it might be better to have the cache be at the state provider level as it is easier to integrate, which is what I did in #2487 - i.e. instead of wrapping `CacheDB`, wrap `StateProvider`. Does that make sense?

**Comment by mattsse** [comment]
> is not currently easy to integrate with the executor

this is only intended for payload building not block executing. Unclear why or how this should be integrated with `Executor`.

payload building does not use the executor.

**Comment by onbjerg** [comment]
@mattsse My thoughts were more that we want to transition out of using revm directly in the RPC and instead make sure our executor abstraction is good enough to use there, so building stuff directly for revm and not for the executor would be a net loss in the longer run, but it's not a big deal and we can merge it in this state if we want

**Comment by mattsse** [comment]
I see, for RPC in general this would be ideal, yes.

payload building is perhaps a more special case because this needs a lot of flexibility that's perhaps not reasonable for the executor.

**Review by gakonst — COMMENTED** [review]
Shouldn't this cache be present for all RPC related stuff as well?

**Comment by mattsse** [comment]
> Shouldn't this cache be present for all RPC related stuff as well?

unsure what you're referring to here.
this makes the most sense for payload building because we're repeatedly executing a lot of the same transactions on top of a fixed state.

I can't think of anything in rpc where we can know for sure this will be the case and caching (state -> reads) is worth it.

I really want this for payload building, how to proceed with this?

**Comment by gakonst** [comment]
Yeah not a blocker go for it.

**Review by gakonst — APPROVED** [review]
Nit needs metrics for optimizing the builder later on based on how much it caches

**Pull request merged**
