### PR TITLE
refactor: rename StateProvider structs

### LINKED ISSUE #639: Rename `StateProviderImplHistory` to `HistoricalStateProvider `
Ref https://github.com/paradigmxyz/reth/pull/631#discussion_r1058501328

### PR DESCRIPTION
**Pull request by TechieBoy**
Made all StateProvider Impls have a consistent name.
`StateProviderImplHistory` -> `HistoricalStateProvider`
`StateProviderImplLatest` -> `LatestStateProvider`

`StateProviderImplRefHistory` -> `HistoricalStateProviderRef`
`StateProviderImplRefLatest` -> `LatestStateProviderRef`

Closes #639

### CODE REVIEW

**Review by rkrasiuk — APPROVED** [review]
lgtm afa this PR's concerned. on a sidenote, i'd investigate if we can get rid of the `*Ref` providers, seems like unnecessary duplication at first glance

**Comment by gakonst** [comment]
Yeah that's what I thought as well re Ref. @rakita was there any reason?

**Review by gakonst — APPROVED** [review]
Nice thanks!

**Comment by rakita** [comment]
I didnt want to drop transaction after Provider is done, so I made wrapper that takes Ref

**Pull request merged**
