### PR TITLE
feat: generic receipt ExecuteOutput

### LINKED ISSUE #12945: Generic receipt `ExecuteOutput`
### Describe the feature

Make `ExecuteOutput` generic over receipt type as `ExecuteOutput<T>`
https://github.com/paradigmxyz/reth/blob/47245642ca481c58da60e698381981c1edcbb264/crates/evm/src/execute.rs#L175-L182

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hoank101**
Closes #12945

### CODE REVIEW

**Review by emhane — APPROVED** [review]
nice, thanks!

**Review by mattsse — COMMENTED** [review]
cool, this could potentially conflict with #12994

so holding off here until that one is merged

**Review by Rjected — COMMENTED** [review]
@hoank101 mind fixing conflicts? otherwise this should be good

**Comment by hoank101** [comment]
hi @Rjected resolved

**Review by mattsse — APPROVED** [review]

**Pull request merged**
