### PR TITLE
ci: chores

### PR DESCRIPTION
**Pull request by DaniPopes**
- unpin nightly
- update `actions/checkout`
- use `dtolnay/rust-toolchain` everywhere
- extract Geth installer to its own script
- install `cargo-udeps` and `cross` using `taiki-e/install-action`
- remove:
  - Fuzz workflow. Hasn't been run in over a year (https://github.com/paradigmxyz/reth/pull/559), and doesn't look like it ever will. Should probably also remove the macro automatically-generated fuzz tests. This should also be removed from PR requirements.
  - bench-success: should be removed from PR requirements since it doesn't do anything because benches run during merge groups.
  - sanity/dep-version-constraints: don't understand its purpose, it's just integration tests with a `cargo update`, but we update at the very least every week so this shouldn't be a problem. This also fails very often.
- run success jobs on ubuntu-latest, not on reth runners

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
lgtm, pending @onbjerg

**Comment by mattsse** [comment]
hmm, some success jobs are now waiting?

**Comment by DaniPopes** [comment]
Need to remove from PR requirements. I don't have access to it

**Review by onbjerg — APPROVED** [review]

**Comment by onbjerg** [comment]
the reason the actions were named "lint success" etc instead of just success is that github's ui will not differentiate them when adding required actions in the dropdown, making it near impossible to add them. plz keep the old names for that reason

**Comment by DaniPopes** [comment]
Figured, though I thought it would be the ID not the name. Updated

**Pull request merged**
