### PR TITLE
ci: use sccache

### LINKED ISSUE #1350: Investigate sccache
### Describe the feature

[sccache] has an integration with the GitHub actions cache, so it might be worth considering using this for builds.

The main advantage of sccache over the cache we use now is that sccache is safely shareable across different workflows and branches, since caching is done per dependency/build flags pair. A bit of investigation is needed to figure out if this is still the case with GitHub's cache, or if an external cache would be needed

[sccache]: https://github.com/mozilla/sccache

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by onbjerg**
Replaces our current cache with sccache. See the issue for the benefits.

Currently, this is slower than expected. It is not entirely clear to me why that is - the number of entries in the cache is considerably smaller here than locally

Closes #1350

### CODE REVIEW

**Comment by gakonst** [comment]
I've never managed to make sccache faster than the default config FWIW.

**Comment by onbjerg** [comment]
@gakonst It is a lot faster for me locally and the cache stats in CI are vastly different than for me locally, see https://github.com/mozilla/sccache/issues/1485#issuecomment-1430484540

It is probably just that the github cache is slow.

**Comment by onbjerg** [comment]
Trying with an S3 bucket (this one is on DigitalOcean, so not *really* S3) to see if it is just GH being slow.

**Comment by gakonst** [comment]
Closing as it feels like a big timesink to further investigate and we have higher prios right now, open to re-exploring later maybe by a 3rd party contrib

**Pull request closed without merging**
