### PR TITLE
feat: add canonicalization latency metric

### LINKED ISSUE #3815: Metrics for `make_canonical` latency when processing forkchoice updates
The Engine API `forkchoiceUpdated` call has one main expensive operation, which is the `make_canonical` blockchain tree method call:
https://github.com/paradigmxyz/reth/blob/01e1344cc1175b7c7110498db6e5319329b62472/crates/consensus/beacon/src/engine/mod.rs#L628-L671

We should measure the latency for this method call expose it as a metric. Maybe we should include the following cases as separate metrics to distinguish between different cases:
* `make_canonical` returns `CanonicalOutcome::AlreadyCanonical`
* `make_canonical` returns `CanonicalOutcome::Committed`
* `make_canonical` returns an error
* latency metric for _any_ outcome (any `CanonicalOutcome` or error)

### PR DESCRIPTION
**Pull request by cjeva10**
Closes #3815

### CODE REVIEW

**Review by Rjected — CHANGES_REQUESTED** [review]
Logic wise this looks great! I wonder if we can do something like the following though:
```rust
        let start = Instant::now();
        let make_canonical_result = self.blockchain.make_canonical(&state.head_block_hash);
        self.record_make_canonical_latency(start, make_canonical_result);
        let status = match make_canonical_result {
        // ... rest
```
where `record_make_canonical_latency` does a match:
```rust
let elapsed = start.elapsed();
self.metrics.make_canonical_latency.record(elapsed);
match outcome {
    Ok(MakeCanonicalOutcome::AlreadyCanonical) => self.metrics.make_canonical_already_canonical_latency.record(elapsed),
    // the AlreadyCommitted case
    Err(_) => // the err case
}
```
does that make sense? I think then, we don't have to intersperse the metrics `record` calls in the match for other logic.

**Comment by Rjected** [comment]
this also needs to be rebased / merged with the latest main since we made some fixes to CI

**Comment by cjeva10** [comment]
Perfect, yes makes sense - I wasn't sure if I should restructure the flow on the main match statement but what you have there makes sense. Will push shortly

**Comment by cjeva10** [comment]
@Rjected I put in the changes you asked for - please let me know if the branch looks ok.

**Comment by Rjected** [comment]
cool - just going to clean up the merge a little bit

**Review by Rjected — APPROVED** [review]
great work - thank you!

**Pull request merged**
