### PR TITLE
refactor: extract peer types to net/types

### LINKED ISSUE #7907: extract peer types to net/types
we should move the peer types defined in:

https://github.com/paradigmxyz/reth/blob/57d09e84beaa4dafa505461db733d672163e4d99/crates/primitives/src/peer.rs#L5-L5

these are network specific and we can move them to a standalone crate like `reth-network-types` or into the common crate: https://github.com/paradigmxyz/reth/blob/57d09e84beaa4dafa505461db733d672163e4d99/crates/net/common/Cargo.toml#L2-L2

but a standalone crate sounds cleaner

### PR DESCRIPTION
**Pull request by andrzejSulkowski**
There is one thing I am not sure though...
At `crates/net/reth-network-types/Cargo.toml` I included `secp256k1` with ` features = ["global-context", "recovery", "rand"]` but I can not determine if they are required.

Closes #7907

### CODE REVIEW

**Comment by onbjerg** [comment]
Please resolve the merge conflicts either by rebasing or merging main into the branch and then I will take a look 😊

**Comment by andrzejSulkowski** [comment]
Currently, when I run `make pr` on the main branch or on my merged branch I get some errors regarding the optimism crate. At first I thought this is related to my code, but it seems like not. 

error: external crate `reth_consensus` unused in `reth_optimism_consensus`: remove the dependency or add `use reth_consensus as _;`
 --> crates/optimism/consensus/src/lib.rs:1:1

**Review by mattsse — CHANGES_REQUESTED** [review]
something went wrong here while rebasing, there are unrelated changes included here

**Comment by andrzejSulkowski** [comment]
Alright! I will notify you as soon as I am finished

**Comment by andrzejSulkowski** [comment]
A cfg line of code from the fix for the Issue #7848 caused `make pr`'s linting check (lint-reth inside Makefile) to fail due to unused imported libs inside `optimism/consensus`. The fix is inside this branch. 

Furthermore, I imported `reth-network-types` inside `crates/stages` as a dev-dependency only to use `PeerId` inside the documentation of the crate (which seems wrong, but idk. what else to do).

**Review by mattsse — APPROVED** [review]

**Pull request merged**
