### PR TITLE
feat(rpc): add blob support for TransactionRequest

### LINKED ISSUE #5118: add blob support in TransactionRequest
### Describe the feature

Currently the imp of TransactionRequest doesn't have blob support
https://github.com/paradigmxyz/reth/blob/33df4e57664425a3df06fd8f06a21c1526257f40/crates/rpc/rpc-types/src/eth/transaction/request.rs#L46

Todo : 

Adding support for blob

I'am happy to take this one :) 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by itsdevbear**
Closes: https://github.com/paradigmxyz/reth/issues/5118

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
nice, I doubt this will be used often but nice to have

**Comment by itsdevbear** [comment]
thanks @mattsse could you explain the changes you made with the matching (I am in the process of learning rust).

if there are any other easy tasks to hit lmk (I know geth in an out)  so it's been a lot of pattern matching

**Comment by mattsse** [comment]
sure,

so this one just collapses the two variants:

https://github.com/paradigmxyz/reth/pull/5382/commits/7e4aa31362f5c1b688ff72c2acfa49c04b289273#diff-d299afe14807edd91a3823e375bf3c57a950e6149370edf075375464b65a6b0aR113-R116

we don't care about fees here in this call because we will set them separately.

and for blob transactions we require all fields because we can't set any of them manually
https://github.com/paradigmxyz/reth/pull/5382/commits/7e4aa31362f5c1b688ff72c2acfa49c04b289273#diff-d299afe14807edd91a3823e375bf3c57a950e6149370edf075375464b65a6b0aR138-R142

**Comment by itsdevbear** [comment]
makes sense, thanks dude

**Comment by mattsse** [comment]
> if there are any other easy tasks to hit lmk (I know geth in an out) so it's been a lot of pattern matching

hehe, yeah it do be like that

I don't have anything specific, but adding the eth_blobGasPrice function would be an easy task, even if perhaps premature

https://twitter.com/TimBeiko/status/1722637396792189234

ref:

https://github.com/paradigmxyz/reth/blob/d108c757405363b7a29055cb9caa8b0aa67041fd/crates/rpc/rpc-api/src/eth.rs#L197-L197

the implementation should just return "unimplmented" for now

**Pull request merged**
