### PR TITLE
chore(lint): use stable toolchain for `make lint`

### PR DESCRIPTION
**Pull request by emhane**
Switches to stable toolchain in Makefile lint commands

### CODE REVIEW

**Comment by shekhirin** [comment]
Why? We use nightly clippy in CI https://github.com/paradigmxyz/reth/blob/15e3e0e110f4a57311422f535025aff69b4ed858/.github/workflows/lint.yml#L34-L49

**Comment by emhane** [comment]
I'm getting a bunch of errors running `make lint` @shekhirin 
```
error: unneeded `return` statement
```

**Comment by shekhirin** [comment]
I see, I think mine is good because it's a more dated nightly version.

I still don't think we should use stable because it will cause diffs between local and CI. Should we just wait until it's fixed in the nightly and until then recommend using a pinned version of nightly Clippy?

**Review by mattsse — COMMENTED** [review]
it's fine if the local nightly is broken, because we also check in ci
and i don't think we should install additional toolchains locally

**Pull request closed without merging**
