### PR TITLE
chore(node,payload,txpool): rm notused crates to speed up building

### PR DESCRIPTION
**Pull request by jsvisa**
similar to #6882

### CODE REVIEW

**Comment by DaniPopes** [comment]
@jsvisa can you please merge all your PRs into one and enable `#![cfg_attr(not(test), warn(unused_crate_dependencies)]`?

**Comment by jsvisa** [comment]
> @jsvisa can you please merge all your PRs into one and enable `#![cfg_attr(not(test), warn(unused_crate_dependencies)]` in all crate roots?

Of course, I can cherry-pick those commits into one. but wouldn't it be too large for one PR?

**Comment by DaniPopes** [comment]
Nope it's fine

**Comment by jsvisa** [comment]
@DaniPopes seems `unused_crate_dependencies` maybe create FP results, so I'm trying to add the `cfg` in another PR, and in this series, I'll rm the notused crates. Is that ok, if it is I'll see you in #6882 :)

**Comment by DaniPopes** [comment]
Sure. About false positives, they should be gone with the `cfg(test)`, if not you can remove it in that specific crate

**Pull request closed without merging**
