### PR TITLE
Introduce `HashedPostStateProvider`

### PR DESCRIPTION
**Pull request by frisitano**
Replacement for https://github.com/paradigmxyz/reth/pull/11872

### CODE REVIEW

**Comment by frisitano** [comment]
False negative on failing tests due to https://github.com/paradigmxyz/reth/pull/12893

**Review by mattsse — APPROVED** [review]
all of these make sense to me

pending @klkvr and @rkrasiuk

**Review by rkrasiuk — APPROVED** [review]
not a fan of having to initialize hashed post state via provider, but otherwise lgtm

**Comment by frisitano** [comment]
I accidentally merged some unrelated work but reset and removed those commits back to the previous reviewed state.

**Review by klkvr — APPROVED** [review]
lgtm, although wondering if we could move the `HashedPostState` construction to `StateRootProvider` implementation? it looks like `from_bundle_state` is called pretty much always before invoking it.

That way we'll unify code paths and make sure that hashing is only done by the type that knows the configured state commitment impl

**Comment by klkvr** [comment]
pending ci and conflicts

**Comment by frisitano** [comment]
> lgtm, although wondering if we could move the `HashedPostState` construction to `StateRootProvider` implementation? it looks like `from_bundle_state` is called pretty much always before invoking it.
> 
> That way we'll unify code paths and make sure that hashing is only done by the type that knows the configured state commitment impl

I would be in support of this idea. However, I need to do some analysis to ensure this is practical for all code paths and evaulate what changes would need to be made. I would suggest we proceed with the current direction and add this as an issue to review and refactor once we have the current implementation stabilized. What do you think?

**Review by mattsse — APPROVED** [review]

**Pull request merged**
