### PR TITLE
feat(rlp): support deriving optional fields

### PR DESCRIPTION
**Pull request by rkrasiuk**
Add support for deriving trailing optional fields.

### CODE REVIEW

**Review by mattsse — COMMENTED** [review]
don't we have this already with `rlp(skip)` and `rlp(default)`?

**Comment by rkrasiuk** [comment]
@mattsse `skip` and `default` fields are ignored during rlp encoding whereas this PR introduces support for trailing `Option`s, which will be encoded if `Some`

**Comment by mattsse** [comment]
I see, understood, but I'd feel safer if we had a container attribute for this instead of matching the type like `rlp(trailing)`

**Comment by rkrasiuk** [comment]
the safer, the better :) totally for it, adding now

**Review by mattsse — APPROVED** [review]
great I can use that in discv4

**Review by gakonst — APPROVED** [review]

**Pull request merged**
