### PR TITLE
fix: use `body.recover_signers_unchecked` instead on `try_with_senders_unchecked`

### PR DESCRIPTION
**Pull request by joshieDo**
alternative to https://github.com/paradigmxyz/reth/pull/12666

`Block::try_with_senders_unchecked` was not using an unchecked recovery method

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
makes sense

**Comment by alessandromazza98** [comment]
I'm checking if this fixes my problem, again thanks a lot for being so fast to reply. will update here shortly

**Comment by alessandromazza98** [comment]
with this PR I still have the same problem, with my (now closed) PR i don't have it

**Comment by alessandromazza98** [comment]
> SealedBlock which is used in this request actually needed to be changed as well (not just Block). Can you try again?
> 
> Tbh, I'm still unsure on what causes the issue. It should not matter if it's unchecked or not, since TxDeposit are "caught" on :
> 
> https://github.com/paradigmxyz/reth/blob/02a90e1c0b48c0af5842b92a49860e8446b5a0e2/crates/primitives/src/transaction/mod.rs#L892-L902

tried but still same error. I'm going to investigate a bit more why I have this error, thanks

**Pull request merged**
