### PR TITLE
chore(deps): bump ethers to 2.0.14, enr to 0.10, unpin discv5

### LINKED ISSUE #6006: Update `enr`, `discv5` dependencies
### Describe the feature

`enr = "0.10"` and `discv5 = "0.4.0"` (rather than git)

This is blocked by alloy migration of tests, since Ethers will be using an older enr version.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by emhane**
Bump enr to latest version.

Closes #6006

### CODE REVIEW

**Review by Rjected — APPROVED** [review]
LGTM

**Comment by Rjected** [comment]
ah rip, breaking change, looks like a builder rename

**Comment by emhane** [comment]
> ah rip, breaking change, looks like a builder rename

yepp, I'm on it. tbh, I outsourced compiling to ci this time, but will have new hw soon.

**Comment by emhane** [comment]
depends on https://github.com/gakonst/ethers-rs/pull/2741

**Comment by DaniPopes** [comment]
cc https://github.com/paradigmxyz/reth/issues/6006

**Review by mattsse — APPROVED** [review]

**Comment by emhane** [comment]
waiting now on ethers-rs to cut new release

**Review by DaniPopes — APPROVED** [review]

**Pull request merged**
