### PR TITLE
clippy: rm outdated clippy allow

### PR DESCRIPTION
**Pull request by tcoratger**

### CODE REVIEW

**Comment by DaniPopes** [comment]
Can you please remove all the other `non_local_definitions` too?

**Comment by tcoratger** [comment]
> Can you please remove all the other `non_local_definitions` too?

Seems like the merge of https://github.com/proptest-rs/proptest/pull/427 didn't solve all of it, is it normal?

**Comment by DaniPopes** [comment]
the proptest-derive crate must be updated

**Comment by tcoratger** [comment]
> the proptest-derive crate must be updated as well

Done

**Review by mattsse — APPROVED** [review]

**Pull request merged**
