### PR TITLE
chore(sdk): Add InMemorySize as super trait

### LINKED ISSUE #12589: `InMemorySize` super trait
### Describe the feature

Add `InMemorySize` as super trait for `reth-primitives-traits` traits: `Receipt`, `SignedTransaction` and `TxType`.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by htiennv**
Closes #12589.

### CODE REVIEW

**Comment by Gerson2102** [comment]
Seems like in this project there is no one with a minimum of respect when an issue is already assigned. @htiennv

**Comment by htiennv** [comment]
ah sorry, i didn't see anyone assigned before doing this pr

**Review by mattsse — APPROVED** [review]
lgtm

**Comment by mattsse** [comment]
sorry about this @Gerson2102, happens sometimes

**Comment by htiennv** [comment]
sorry @Gerson2102

**Pull request merged**
