### PR TITLE
feat(pruning): fair pruning

### LINKED ISSUE #7343: chore(prune): segment ring for fair pruning
### Describe the feature

Segment pruning always starts with the same segment. Last segments in the iterator, risk not being pruned if the prune limit is small so it's often reached before pruning is done. We should implement a ring here: add a field to `Pruner` where we save the index in the chained segments iterator, of the last pruned segment. Upon calling `prune_segments` next time, the iterator should skip until the saved index + 1.

https://github.com/paradigmxyz/reth/blob/c04dbe6e9bd05be5da3a5d541adbf76166c14a08/crates/prune/src/pruner.rs#L141-L145

This will probably require modifying `static_file_segments` method, since it's important that no segments that need pruning are dropped when the iterator skips ahead to the last pruned segment.

https://github.com/paradigmxyz/reth/blob/c04dbe6e9bd05be5da3a5d541adbf76166c14a08/crates/prune/src/pruner.rs#L215-L243

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by emhane**
Closes https://github.com/paradigmxyz/reth/issues/7343, related to pruner interruption ref https://github.com/paradigmxyz/reth/issues/6770.

- Models exhaustive list of prunable tables as a ring.
- Implements a segment iterator, that generates a cycle of segments, wrt to given start table.
- Saves last pruned table between prune jobs. This ensures fair pruning, as the next job can pick up where the last one left off.
- Has support for starting with random segment, to ensure fairness over time, if that should show itself to be needed

Screenshot 2024-07-02 at 12 37 48
Storage history is catching up, hasn't been pruned in a while

### CODE REVIEW

**Comment by emhane** [comment]
still have to build some tests

**Comment by shekhirin** [comment]
> Saves last pruned table between prune jobs

I am not sure if we need it, what is the case when we want to continue pruning some table inside a segment, and not the whole segment from the beginning?

**Comment by emhane** [comment]
> It feels a bit overcomplicated, can we just have a `VecDeque` of segments that we pop/push from/to?
> 
> How I see it:
> 
> 1. `VecDeque` of segments initialized when the pruner is initialized
> 2. When we prune, we pop segments from the `VecDeque` one by one until there's none left
> 3. When a limit (with timeout or items deleted) is hit, push segments that we ran to the end of the `VecDeque`
> 4. On the next run, pop will return segments that we didn't run first
> 
> WDYT?

No need to reallocate memory, easiest is to just save the index we would have pruned next in the `Vec<Box<dyn Segment>>`. 

True that there is no need to generate the segments, other than for static files, on each call to `prune_segments`. On second look, I saw that `PruneMode::Before` is not used in the static allocation of `Vec<Box<dyn Segment>>` which is built using `PruneMode`s.

**Comment by emhane** [comment]
> > Saves last pruned table between prune jobs
> 
> I am not sure if we need it, what is the case when we want to continue pruning some table inside a segment, and not the whole segment from the beginning?

checkpoints are saved when pruning stops

**Comment by shekhirin** [comment]
> No need to reallocate memory, easiest is to just save the index we would have pruned next in the `Vec<Box<dyn Segment>>`.

up to you, I'd prefer a `VecDeque` for a more intuitive API. Since all segments are `Box`, it's not a big overhead. Also, `VecDeque` doesn't have a requirement for the elements to be contiguous in memory.

"Since VecDeque is a ring buffer, its elements are not necessarily contiguous in memory." – from https://doc.rust-lang.org/std/collections/struct.VecDeque.html

**Comment by emhane** [comment]
don't think it makes that big difference now that this is implemented + tested

**Comment by emhane** [comment]
blocked by db background task design, cc @Rjected

**Pull request closed without merging**
