### PR TITLE
fix(chainspec): remove fork block from `active_at_block` check

### PR DESCRIPTION
**Pull request by rkrasiuk**
The `fork_block` is currently used for sepolia only and doesn't actually point to the Merge block, but rather to merge_net_split_block. Thus, it should be removed from fork activation check at certain block number

### CODE REVIEW

**Review by onbjerg — APPROVED** [review]

**Review by Rjected — APPROVED** [review]
lgtm, I guess this comment:
https://github.com/paradigmxyz/reth/blob/fe91be06ca51d7cc316f7f454f66fa2715c040bc/crates/primitives/src/chain/spec.rs#L487-L488

should be changed. Definitely worth documenting this

**Comment by Rjected** [comment]
hmm, wonder if `transaction::test::insert_get_take_multiblocks` is related or if it's a flake

**Review by mattsse — APPROVED** [review]

**Comment by gakonst** [comment]
```
--- STDERR:              reth-primitives chain::spec::tests::sepolia_forkids ---
thread 'chain::spec::tests::sepolia_forkids' panicked at 'assertion failed: `(left == right)`
  left: `ForkId { hash: ForkHash("b96cbd13"), next: 1677557088 }`,
 right: `ForkId { hash: ForkHash("fe3366e7"), next: 1735371 }`: Expected fork ID ForkId { hash: ForkHash("b96cbd13"), next: 1677557088 }, computed fork ID ForkId { hash: ForkHash("fe3366e7"), next: 1735371 } at block 1735371', crates/primitives/src/chain/spec.rs:604:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Rjected** [comment]
guess we should close this?

**Comment by gakonst** [comment]
@rkrasiuk what should we do here?

**Comment by rkrasiuk** [comment]
some docs need to be added

**Comment by rkrasiuk** [comment]
closing because it breaks fork ids

**Pull request closed without merging**
