### PR TITLE
feat: add scroll as named networks

### PR DESCRIPTION
**Pull request by RamanSB**

### CODE REVIEW

**Comment by gakonst** [comment]
Think we don't want to get into adding chains we cannot run?

And the existing non ethereum chains are debt which should be removed?

**Comment by RamanSB** [comment]
I had noticed the only mention of Arbitrum was that it had been added to the NamedChain enum, so I thought it would be useful to also include the scroll network(s).

Are you suggesting removing the non ethereum chains (L2s) that cannot run like Arbitrum?

Please let me know the intended update and I am happy to make the commit.

**Review by mattsse — CHANGES_REQUESTED** [review]
we should instead replace all of this with the chains dependency

https://github.com/alloy-rs/chains

ref #5429

**Comment by onbjerg** [comment]
Closing this per the above; feel free to open a PR w the proposed change by @mattsse

**Pull request closed without merging**
