### PR TITLE
chore: pin git dependencies to specific revs

### LINKED ISSUE #4537: Lock `git` dependency to a revision in Cargo.toml
### Describe the bug

Currently, importing any crate using a tag like `v0.1.0-alpha.8` fails to build because of breaking changes in `c-kzg`.

See TG discussion starting from: <https://t.me/paradigm_reth/14004>

### Steps to reproduce

New Cargo project with

```toml
[dependencies]
reth-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v0.1.0-alpha.8" }
```

### Node logs

_No response_

### Platform(s)

_No response_

### What version/commit are you on?

_No response_

### What database version are you on?

_No response_

### If you've built Reth from source, provide the full command you used

_No response_

### Code of Conduct

- [X] I agree to follow the Code of Conduct

### PR DESCRIPTION
**Pull request by DaniPopes**
Closes #4537

### CODE REVIEW

**Review by mattsse — APPROVED** [review]
I think this is reasonable, even if this requires manual updates now, but if it helps to prevent issues for dependant crates sgtm

**Comment by DaniPopes** [comment]
I also pinned `revm` instead of using `crates.io` patch in ff51ac032c384ed9b4cf447d00c9b72e028dd05a.
This also fixes the need for users to patch as well, as long as we don't depend on other crates that depend on revm `crates.io` themselves.

**Comment by mattsse** [comment]
good call, getting tired of answering that question why it does not compile

**Comment by mattsse** [comment]
@DaniPopes let's switch to boa 0.17 from crates?

**Review by mattsse — APPROVED** [review]

**Pull request merged**
