### PR TITLE
feat(nat): add None Natresolver

### PR DESCRIPTION
**Pull request by mattsse**
Add `None` variant and missing FromStr and Display impl

### CODE REVIEW

**Review by onbjerg — APPROVED** [review]
The `extip` in geth and erigon also take an IP `extip:<ip>`, I think this is because you can technically have multiple public IPs and route them on your internal network according to forwarding rules. We should note this down and support `extip` which auto-resolves and `extip:<ip>` which is manual later on

**Comment by mattsse** [comment]
ah I see, will cahnge and make this explicit that this uses an external IP resolver service

**Comment by mattsse** [comment]
added `extip:<IpAddr>` variant

**Review by gakonst — APPROVED** [review]
makes sense

**Pull request merged**
