### PR TITLE
Add `missing_const_for_fn` clippy lint

### PR DESCRIPTION
**Pull request by tcoratger**

### CODE REVIEW

**Review by emhane — APPROVED** [review]
this is super useful

**Comment by emhane** [comment]
@tcoratger is there a lint for removing redundant trait bounds on impl bodies?

**Comment by tcoratger** [comment]
> @tcoratger is there a lint for removing redundant trait bounds on impl bodies?

I don't think so or maybe I don't know it yet.

**Review by mattsse — APPROVED** [review]
lgtm

**Pull request merged**
